### ISSUE TITLE
[BUG] Moths cannot eat Wool/leather/paper/books

### ISSUE THREAD

**Issue by Sockomo** [itsdinkd/AQM2#10]
**Modpack Version**
1.1.2

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Non-edible foods that moths can eat won’t work

**Steps to reproduce the behavior:**
I don’t know? Try to eat them as a moth and see?

**Expected behavior**
To gain food and saturation from the 4 items

**Comment by FederAndInk** [comment]
You now need to craft them into Fibrous String and Book Bite:
![Screenshot_20220514_135802](https://user-images.githubusercontent.com/24270152/168424693-a6554962-caca-4267-a80c-b10d1b7a199b.png)
![Screenshot_20220514_135915](https://user-images.githubusercontent.com/24270152/168424717-998c17f6-57c6-4dde-8d29-d54144f3c574.png)

**Comment by itsdinkd** [comment]
This would need to be brought up to the developer.
