### ISSUE TITLE
[BUG] AE2 Inscriber output transformed into mana

### ISSUE THREAD

**Issue by Madfish5415** [itsdinkd/AQM2#100]
**Modpack Version**
1.5.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
I use a small automation for AE2 in order to craft automatically some processors (logic, engineering, calculation) but at the export time (export bus -> Pattern provider) the processor is changed to a "mana" item. It's not even the botania one, it's a "minecraft:mana" item.

**Steps to reproduce the behavior:**
I just build a basic automation process an "infinite" channel configuration for AE2.

**Expected behavior**
To get the processor

**Screenshots**
https://ibb.co/1vJ47kv
https://ibb.co/rtmkKyY

**Crash log or latest.log.log**
[latest.log](https://pastebin.com/sYyqXHwd)

**Comment by itsdinkd** [comment]
Update the modpack
