### ISSUE TITLE
[BUG] Atlan's Enchatibility too low

### ISSUE THREAD

**Issue by ASum5** [itsdinkd/AQM2#100]
Modpack Version
2.0.1

Minecraft Version
1.18.1

Describe the crash or bug
Atlan Trident  does not have increased enchantibility (from Impaled mod)
-Enchantibility stat is set to 1 when it should be similar to gold items of 22
https://minecraft.fandom.com/wiki/Enchanting_mechanics

Interact w/ enchanting table, stat for enchantibility should appear
enchant a trident and atlan and compare. Enchants are of same quantity and quality

Expected behavior
The Atlan should receive significantly more enchants than other tridents

Screenshots
![image](https://user-images.githubusercontent.com/98622816/151633025-01f927dc-c2c6-4420-b45f-c3529c37a32b.png)
![image](https://user-images.githubusercontent.com/98622816/151633061-b0a218e2-c147-428e-a6a1-992d38c30a20.png)

Crash log or latest.log.log
N/A

Additional context
I don't know what the intended value is or if it was intentionally set to 1, couldn't find other references to Atlan due to trident rarity so a bug it is.

**Comment by itsdinkd** [comment]
This is more of a suggestion than a bug. Also, this would be something for the developer of Impaled.
