### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Donut678** [itsdinkd/AQM2#101]
**Modpack Version**
AQM2 v1.6
**Minecraft Version**
1.18.2 fabric

**Describe the crash or bug**
Texture pack failing to load

**Steps to reproduce the behavior:**
Open resource packs with 8 gigabytes allocated on atlauncher and press done.
**Expected behavior**
The resource/texture pack will reload the game multiple times and then fail to load.

**Screenshots**

**Crash log or latest.log.log**
[latest.log](https://github.com/itsdinkd/AQM2/files/9539139/latest.log)

**Additional context**
I've attempted to use open loader and other mods and it still fails. in this latest log open loader is enabled. 
Here is my settings.
[options.txt](https://github.com/itsdinkd/AQM2/files/9539147/options.txt)

Pc specs:
16gb ram
intel core if-7400 CPU
NVidia GeForce gtx 670

**Comment by Donut678** [comment]
[latest.log](https://github.com/itsdinkd/AQM2/files/9539399/latest.log)
**_Updated log._**
 I force closed the game after the following.

 I was attempting to load new default plus texture pack on main menu. it failed then preceded to enter my singleplayer world. I attempted to load default dark mode texture pack and it failed again.

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
