### ISSUE TITLE
[BUG] Croptosis Potash and Apatite not increasing crop growth rate

### ISSUE THREAD

**Issue by Supergod99** [itsdinkd/AQM2#102]
**Modpack Version**

AQM2 1.6

**Minecraft Version**

1.18.2

**Describe the crash or bug**

Croptosis Potash and Apatite not increasing crop growth rate

**Steps to reproduce the behavior:**

1. Apply potash or apatite to farmland

**Expected behavior**

Crop growth rate should increase 

**Screenshots**
/

**Crash log or latest.log.log**
/

**Additional context**

I did many side by side tests of unfertilized farmland vs fertilized farmland using both carrots and leather seeds. This ensures it is not just a problem with modded seeds.

EDIT: Upon further testing, it actually appears to be significantly slowing down the growth rate.

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
