### ISSUE TITLE
[BUG] Non-BE end ores ONLY generate in vanilla end biomes

### ISSUE THREAD

**Issue by Archiplex** [itsdinkd/AQM2#103]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18

**Describe the crash or bug**
Currently, only Thallasium and Ender ores will generate in modded biomes, with many other mods only generating their ores in vanilla biomes. As a majority of biomes in the end ARE BE-tagged biomes, it makes it very difficult to hunt out these ores.

Known ores affected: End gobber, Tungsten, Peridot, some other weird ores i cant remember the names of from MI.

**Steps to reproduce the behavior:**
Take a ring of mining and mine a ton in BE-biomes. Then, take a ring of mining and mine in midlands/the End biomes

**Expected behavior**
More ores!!

**Comment by itsdinkd** [comment]
Fabric Api's update should fix this, closing. update to 2.0.2
