### ISSUE TITLE
[BUG] Pressure Plate not deactivating

### ISSUE THREAD

**Issue by PhaedrusXY** [itsdinkd/AQM2#103]
**Modpack Version**
1.6

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Pressure Plate not deactivating. It's part of an automatic dispenser. It was working fine, I replaced a few blocks nearby (not directly in contact with the circuit, like 2 blocks away, and it was water and some stone) and now it does not deactivate unless it is removed and replaced. Once it has been activated, it stays that way even when nothing is on it. I believe this may be a vanilla bug, as I saw a report of this behavior there also. https://bugs.mojang.com/browse/MCPE-47509 I tried removing the original pressure plate and replacing it (with a different kind, even). It still had the same problem. It has a power level 15 right next to it, and when you use f3 and look at it, it says "powered" even though nothing is on it. There are no other redstone components nearby that could be powering it, and as I said, it was working fine before. 

**Steps to reproduce the behavior:**
I'm not sure. It seems to only happen in that one exact spot. I moved the same pressure plate and it worked fine, even if it was only 1 block higher. There was a couple of furnaces that had a lot of experience orbs "stored" up inside, because hoppers had been pulling out their products. However, I tried "emptying" them of XP and that didn't seem to fix it (it's known that having these around can cause weird issues somehow). 

**Expected behavior**
Pressure plate deactivates

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
