### ISSUE TITLE
[BUG] Bronze dust recipe missing.

### ISSUE THREAD

**Issue by Archiplex** [itsdinkd/AQM2#104]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18

**Describe the crash or bug**
You can currently convert tin/copper ingots into bronze ingots, as well as tiny piles of dust into a tiny pile of bronze dust, but not regular sized piles of dust into bronze dusts.

Also, the recipe for unpacking tin dust into tiny piles of tin dust in an unpacker is disabled.

**Comment by itsdinkd** [comment]
Fixed in 2.0.2
