### ISSUE TITLE
[BUG] Server Freezing

### ISSUE THREAD

**Issue by Craftler** [itsdinkd/AQM2#105]
**Modpack Version**
2.0a and 2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The Server kicks everyone with "Timeout" and then the console freezes and i am not able to do anything. 

**Steps to reproduce the behavior:**
-

**Expected behavior**
-

**Screenshots**
![grafik](https://user-images.githubusercontent.com/69083432/151712141-b1f155ce-7ce1-4eca-9c35-200931cacb3f.png)

**Crash log or latest.log.log**
[latest.log](https://github.com/itsdinkd/AQM2/files/7966611/latest.log)

**Additional context**
Any additional context?

**Comment by Craftler** [comment]
No, i set up the server with Minecraft 1.18.1 with the Modpackversion 2.0a and tried to upgrade to 2.0.1. The Problem occours in both Versions, interesting is that the problem discontinued since we had an power outage two days ago. Since then the Server had not a single crash, before that i crashed approximatley 2-3 times a hour. 
Even if the Problem is solved, i wonder what caused the crashes.

**Comment by itsdinkd** [comment]
hm. yeah that is really odd. i have never received this on the official servers, nor on my single player instances. I'll close it though since I am releasing 2.0.2 and valley is also updated, if it happens again on 2.0.2 I will reopen if you comment back and tell me

**Comment by Craftler** [comment]
Today the problems came back, because of that I updated the server from 2.0a to 2.0.2. I added the latest.log of two tries, maybe you find a connection between them. I couldn't figure out anything useful, if you need any data just tell me where to find it.
[latest.log](https://github.com/itsdinkd/AQM2/files/7997605/latest.log)
[latest.log](https://github.com/itsdinkd/AQM2/files/7997664/latest.log)
