### ISSUE TITLE
[BUG] Deep Learner not counting skeletons killed

### ISSUE THREAD

**Issue by PhaedrusXY** [itsdinkd/AQM2#105]
**Modpack Version**
1.6

**Minecraft Version**
1.18.2
![2022-09-13_23 40 46](https://user-images.githubusercontent.com/80270989/190054858-aa0823eb-3fe8-4eef-89a6-70e4d5536db0.png)

**Describe the crash or bug**
The Deep Learner from the Deep Mob Learning mod not counting skeletons killed. I have the proper card in it, and killed several skeletons, but it still says 0/12. I was using the platinum machete you can get by crafting it with a single stick, if that matters.

**Additional context**
on Zion public server

**Comment by itsdinkd** [comment]
This would need to be reported to the developer, nothing I can do to fix the mod not counting kills.
