### ISSUE TITLE
[BUG] Grass only dropping wheat seeds

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#106]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Grass only dropping wheat seeds when broken.

**Expected behavior**
Grass should drop the other modded seeds, not only wheat

**Comment by Sebas-Re** [comment]
Also, kinda related, you can't get Cabbage seeds from farmer's delight

You only get the croptopia seed recipe, there's no recipe for farmer's delight seeds, so you can't place Farmer's Delight Cabbage unless you find them on grass (which won't occur due to the bug above).
![image](https://user-images.githubusercontent.com/32151264/151721153-da37a1fc-7114-4282-8687-be526352a34f.png)

**Comment by Sebas-Re** [comment]
Also tried breaking grass using a hoe and got the same results.

**Comment by itsdinkd** [comment]
Fixed in 2.0.2
