### ISSUE TITLE
[Feature Request] Mystical Index

### ISSUE THREAD

**Issue by NickMesser** [itsdinkd/AQM2#107]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
I would like to add a new mod.

**Why do we need this feature?**
I play this modpack personally and would love to see my own mod in it. It adds cool storage options and I plan to add a lot more :)

**Link to the modpage if mod?**
https://www.curseforge.com/minecraft/mc-mods/mystical-index

**Additional context**
Very configurable and can be changed to fit the scale of the progression.

**Comment by itsdinkd** [comment]
Cool mod though we already have tons of storage options
