### ISSUE TITLE
[BUG] Crash when use anvil on Mc Dungeons Weapon

### ISSUE THREAD

**Issue by Flashacker-Neo** [itsdinkd/AQM2#108]
**Modpack Version**
AQM 2 v1.6

**Minecraft Version**
1.18.2

**Describe the crash or bug**
When I tried to add an enchantment to an "MC Dungeons Weapons" item, the game crash.
I tried with other mod items and that work. But the "MC Dungeons Weapons" enchanted book seem to work fine with other equipment.

**Steps to reproduce the behavior:**
Have 3 items : Minecraft Anvil, Sword and Enchanted Book from MC Dungeons Weapons.
Tried to add the enchantment to the weapon. May not crash at the first try.

**Expected behavior**
Add the enchantment to the weapon.

**Crash log or latest.log.log**
https://pastebin.com/Bk27eEY0

**Comment by itsdinkd** [comment]
Unfortunately this is out of my control and would have to be reported to the developer

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
