### ISSUE TITLE
[BUG] Drinking a health potion with "Surprise Gift" enchantment on a piece of armor closes the world

### ISSUE THREAD

**Issue by Easyidle123** [itsdinkd/AQM2#108]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
When you drink a health potion while having any level of the "Surprise Gift" enchantment on any piece of armor, the world will close with the message "Server closed".

**Steps to reproduce the behavior:**

- Create a new world with cheats on
- Give yourself a diamond helmet _(/give @s diamond_helmet)_
- Enchant it with Surprise Gift _(/enchant @s mcda:surprise_gift)_, and put it on
- Get a health potion from the creative menu and drink it
- You will receive an additional random potion, but the world closes immediately after

**Expected behavior**
You receive an additional random potion and the world does not close

**Crash log or latest.log.log**
https://pastebin.com/BgkrFY8A

**Comment by Archiplex** [comment]
This is just https://github.com/itsdinkd/AQM2/issues/84

On a multiplayer server, the user is disconnected and the potion(s) from Surprise Gift fall on the ground.

**Comment by Easyidle123** [comment]
Duplicate of #84
