### ISSUE TITLE
[BUG] Tin dust

### ISSUE THREAD

**Issue by Novik4201** [itsdinkd/AQM2#109]
**Modpack Version**
AQM2 v2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
tin dust from resourceful tools cant be smelted or used for crafting

**Steps to reproduce the behavior:**
use a cracked hammer on raw tin ore

**Comment by itsdinkd** [comment]
Resourceful Tools does not have its own tin dust.
