### ISSUE TITLE
[Suggestion] An in-game solution to Zombified Piglins permanently aggravated nature

### ISSUE THREAD

**Issue by DadBackFromWalmart** [itsdinkd/AQM2#109]
The DOOM Mod makes the Nether more like a true living, breathing Hell. I get that as the intent. However, the permanently aggro'd Zombified Piglins make it near impossible to exist in the Nether. It would be nice if there was a way to be able to neutralize their aggression (until of course you accidentally strike one of them).

Talking with some folks int he server, they suggest doing away with the perma-aggro entirely. I think it would be enough to, say, have the Glimmering enchant from the mod Fabric Enchantments (that's part of the modpack) work against Zombified Piglins as well as Normal Piglins. That way, they ZP's are still perma aggro'd, but you can EARN a way to neutralize them.

I'm in the support server as Railblade#7700 if you have any questions on this proposal, but I think overall this would make the modpack a lot better / more playable.

**Comment by itsdinkd** [comment]
You cannot just change the way enchantments work. The developer would have to offer that feature. 

Anyways, I removed aggro zombie piglins in 1.6.1
