### ISSUE TITLE
[BUG] Fluid Tanks uncraftable

### ISSUE THREAD

**Issue by fallinforya** [itsdinkd/AQM2#11]
**Modpack Version**
1.1.2

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Fluid Tanks are not craftable due to Recipes stacking on each other I guess

**Steps to reproduce the behavior:**
craft

**Expected behavior**
craft sucessfully

**Screenshots**
![bug](https://user-images.githubusercontent.com/22235101/168417929-c44b757e-6266-4a4b-867a-481cf5910d43.png)

**Crash log or latest.log.log**
/

**Additional context**
/

**Comment by FederAndInk** [comment]
the recipe needs 4 copper ingot between the tanks, try that it should work, I think its an REI bug

**Comment by fallinforya** [comment]
yeah thanks that does work :)
