### ISSUE TITLE
[BUG] fix thanks.

### ISSUE THREAD

**Issue by killerkitt** [itsdinkd/AQM2#110]
**Modpack Version**
What modpack version 2.0.1

**Minecraft Version**
What mc version 1.18.1

**Describe the crash or bug**
no idea for the crash log one i dont know what happened i wasnt doing anything at the time.

**Steps to reproduce the behavior:**
there have been a memory leak it builds up over time and then crashs
the current crash log is unknown one but there has been multiple crashs for lots of reasons
1 being the launchpad if you set the value to high... obviously i see why that crashs
2. the current one someone joined the server and another mined a block and got the achievement defensive spell.
3. i keep getting log spammed with Server thread/ERROR Recoverable errors when loading section [322, 14, 37]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: terralith:stony_spires -> using default) amd ^^^ numbers change like it checking chunks..
4. aswell as Recoverable errors when loading section [316, -2, 42]: (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: terralith:cave/fungal_caves -> using default); (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: terralith:fractured_savanna -> using default); (Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: terralith:cave/andesite_caves -> using default) in that error messages.

**Expected behavior**
What is the expected outcome?
launch pad dont crash
and people play without crash?

**Screenshots**
no screens needed i dont know how it crashed i just typed what the last 2 events were

**Crash log or latest.log.log**
https://pastebin.com/Q52ASvWY

**Additional context**

https://pastebin.com/9CHay8gs

**Comment by itsdinkd** [comment]
this is not how issues work. 

You can create 1 issue per issue. not bunch them together.
