### ISSUE TITLE
Claim Bug

### ISSUE THREAD

**Issue by DaddySangradorBugFinder** [itsdinkd/AQM2#110]
Claims going over one month to delete, since I’m way further than spawn and haven’t log in in like 2 months, I found out my claim wasn’t gone, so I think that as long as the chunk of my claim inst loaded by a player, the timer for the 1 month won’t start therefore, not deleting the claim!
PS: please don’t delete my claim I’m coming back next week :(
X2 PS: I love dinkus

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
