### ISSUE TITLE
[Feature Request] Nullscape mod.

### ISSUE THREAD

**Issue by vydax** [itsdinkd/AQM2#111]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Potentialy adding mod. Nullscape

**Why do we need this feature?**
more verticality and more biomes in the nether akin to terralith. and made by the same creator
uses only vanilla blocks so no added blocks or items.
i know this has small chance to be added since we already have the other end mod with the biomes but i figured i'd still post it.|

the biomes in this mod are a bit more eerie and mysterious, as for the other biome mod they are a bit more alien/fantasy so its all up to what style you would prefer.

**Link to the modpage if mod?**
https://www.curseforge.com/minecraft/mc-mods/nullscape-end-reborn

**Additional context**
https://i.imgur.com/2PKWtXd.png

https://www.youtube.com/watch?v=R_xWPYNsrq0
little video review of it here if you wanna see more of it.

**Comment by itsdinkd** [comment]
Nullscape is for the End, not the nether. We already have Better End and Better Nether mods. 1 huge datapack is taxing enough, adding another would kill performance. Thank you for your suggestion though.
