### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by novamanticore** [itsdinkd/AQM2#112]
**Modpack Version**
What modpack version
1.6.1a 
**Minecraft Version**
What mc version
1.18.2
**Describe the crash or bug**
Don't know how this happened or what caused it but can't break spruce logs or normal grass blocks.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

**Expected behavior**
What is the expected outcome?
Cannot break any spruce logs or grass blocks
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log
https://paste.ubuntu.com/p/4Y2wjpY6CB/
Pastbin said i exceeded the maximum so i used another one if thats okay

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
most likely its the origin you chose. read the pros and cons of it
