### ISSUE TITLE
[BUG] Game-breaking (wrt AE2/Tech Reborn at least) clientside block vanishing

### ISSUE THREAD

**Issue by klassekatze** [itsdinkd/AQM2#112]
**Modpack Version**
AQM2 2.0.2

**Minecraft Version**
1.18.1

**Describe the crash or bug**
AE2, Tech Reborn, and possibly other mod blocks vanishing when block updates.

**Steps to reproduce the behavior:**
1. Log into official server Abyss
2. teleport to 3690, 152, 1946 - a room with frequently block updating tech reborn & ae2 machinery
3. observe blocks flickering in and out.

Alternatively:
AE2: Place a Fluix ME Glass Cable anywhere in the world, then another AE2 Fluix ME Glass Cable adjacent. They should both vanish when the 2nd is placed, or possibly just when the first is.

Tech Reborn: Place a Insulated Gold Cable anywhere in the world, then another Insulated Gold Cable adjacent. They should both vanish when the 2nd is placed.

**Expected behavior**
Blocks don't vanish.

**Screenshots**
before
![image](https://user-images.githubusercontent.com/10589097/152235856-c9208898-555d-4ade-a0f5-e714959babcc.png)
after place 1 cable
![image](https://user-images.githubusercontent.com/10589097/152235891-cd95f8b0-91d8-489b-aa01-f3bfe13a75e2.png)

**Crash log or latest.log.log**
pastebin says You have exceeded the maximum paste size of 512 kilobytes per paste. :|

**Additional context**
Before the update, there were already small infrequent issues with singular blocks failing to update properly, most notably with mossy stone but even things like mined stone, and sometimes placed machine blocks/cables. This could be related, maybe?

**Comment by klassekatze** [comment]
problem persists in 2.0.2a for both AE2 and Tech Reborn

**Comment by DragonLight** [comment]
Same issues with both mods, but starting to effect other mods like Spectrum also. Models randomly appearing appearing disappearing right clicking on them as well. have to log off server and log back on and its a 50/50 shot at weather the client can see all the blocks again or not. Definitely a game breaking bug effecting multiple mod packs now.

**Comment by itsdinkd** [comment]
> Same issues with both mods, but starting to effect other mods like Spectrum also (put a Radiating Ender block down and it disappears, have to log off and back on to see it). 2.0.2a did not fix. Models randomly appearing and disappearing right clicking on them as well. have to log off server and log back on and its a 50/50 shot at weather the client can see all the blocks again or not. Definitely a game breaking bug effecting multiple mod packs now.

Most likely a fabric api issue if its affecting other modpacks.

**Comment by itsdinkd** [comment]
My suggestions until this is figured out by fabric is try refreshing chunks using F3+A in game,

Try removing Indium
Try removing Iris if indium does not fix it
If those fail, then unfortunately there's nothing we can do except wait.

**Comment by recon88** [comment]
> > Same issues with both mods, but starting to effect other mods like Spectrum also (put a Radiating Ender block down and it disappears, have to log off and back on to see it). 2.0.2a did not fix. Models randomly appearing and disappearing right clicking on them as well. have to log off server and log back on and its a 50/50 shot at weather the client can see all the blocks again or not. Definitely a game breaking bug effecting multiple mod packs now.
> 
> Most likely a fabric api issue if its affecting other modpacks.

If that's the case, then why has nobody opened an issue ticket on Fabric's page yet? Can't seem to find anything that relates to the said bug. They can't fix what they don't know is broken. Just "waiting" doesn't help here.

**Comment by klassekatze** [comment]
> If that's the case, then why has nobody opened an issue ticket on Fabric's page yet? Can't seem to find anything that relates to the said bug. They can't fix what they don't know is broken. Just "waiting" doesn't help here.

Honestly? I'm going to tell it like I sees it. The recommended, release version of the most popular modpack has two major mods that have been recipe-tweaked to gate away even _more_ modded items... in a broken state. As in, you effectively cannot access major swathes of content in the recommended version. To add insult to injury, someone may not even become aware of the depth (or even the existence) of the problem until they / their players have invested significant time into a server, because common sense would dictate that a 'release-viable' pack wouldn't have entire major mods this screwed over.

Saying 'there's nothing to do but wait' is misleading at best, because as we know, the problem didn't exist prior to this update.

But if we just say "oh, nothing can be done", then it's okay to do, well, nothing. And doing nothing is a lot easier than actually investigating the problem and determining the cause, which, to be clear, would not require _any_ programming knowledge because we have a version of the pack that does not have the problem.

If anyone is interested in actually solving it--
1. Download and set up the server and client. Remove all mods except tech reborn and AE2 and their prerequisites, moving the others into separate folders.
2. Start up server and client. Connect to localhost server. 
3. Check if bug exists via repro above - placing cable. If bug does *not* exist... gasp, it isn't Fabric, and it isn't TR/AE2.

These initial steps are pretty easy, which is why the only excuse to not do them is pretty much literally "I don't feel like it." Which is everyone's right, but it's not a professional way to address such a wide issue. Especially when this pack has had other sporadic block update issues - determining the cause of this problem could end up solving a lot more.

If the bug does not exist in the TR/AE2 only 'pack', the next step is binary search in the same vein as github bisect.
1. Add half the mods back to the server and client.
2. Start up server and client. Connect to localhost server. Test if bug exists.
3a. If bug doesn't exist, go to step 1.
3b. If bug exists, the cause is in the mods just added. _Remove_ half of them without removing TR/AE2 or prereqs.
3a1. If the bug still exists, continue to remove half until it doesn't.

By following this kind of process, the mod causing the bug can be narrowed down from ~350 mods in approximately 8 iterations of testing at most. That's still _annoying_, but it's not some daunting hell-task.

**Comment by itsdinkd** [comment]
> > > Same issues with both mods, but starting to effect other mods like Spectrum also (put a Radiating Ender block down and it disappears, have to log off and back on to see it). 2.0.2a did not fix. Models randomly appearing and disappearing right clicking on them as well. have to log off server and log back on and its a 50/50 shot at weather the client can see all the blocks again or not. Definitely a game breaking bug effecting multiple mod packs now.
> > 
> > 
> > Most likely a fabric api issue if its affecting other modpacks.
> 
> If that's the case, then why has nobody opened an issue ticket on Fabric's page yet? Can't seem to find anything that relates to the said bug. They can't fix what they don't know is broken. Just "waiting" doesn't help here.

No one is "waiting". Go away.

**Comment by itsdinkd** [comment]
> > > Same issues with both mods, but starting to effect other mods like Spectrum also (put a Radiating Ender block down and it disappears, have to log off and back on to see it). 2.0.2a did not fix. Models randomly appearing and disappearing right clicking on them as well. have to log off server and log back on and its a 50/50 shot at weather the client can see all the blocks again or not. Definitely a game breaking bug effecting multiple mod packs now.
> > 
> > 
> > Most likely a fabric api issue if its affecting other modpacks.
> 
> If that's the case, then why has nobody opened an issue ticket on Fabric's page yet? Can't seem to find anything that relates to the said bug. They can't fix what they don't know is broken. Just "waiting" doesn't help here.

What exactly are you doing to contribute other than posting on a issue for the first time complaining? This is being looked into. If you don't see an issue on fabric api, why don't you create one, since it's bothering so much to the point where you feel the need to tell people what helps and doesn't help? I will create my own issue when i know for a fact what the cause is. Please leech elsewhere.

**Comment by itsdinkd** [comment]
> > If that's the case, then why has nobody opened an issue ticket on Fabric's page yet? Can't seem to find anything that relates to the said bug. They can't fix what they don't know is broken. Just "waiting" doesn't help here.
> 
> Honestly? I'm going to tell it like I sees it. The recommended, release version of the most popular modpack has two major mods that have been recipe-tweaked to gate away even _more_ modded items... in a broken state. As in, you effectively cannot access major swathes of content in the recommended version. To add insult to injury, someone may not even become aware of the depth (or even the existence) of the problem until they / their players have invested significant time into a server, because common sense would dictate that a 'release-viable' pack wouldn't have entire major mods this screwed over.
> 
> Saying 'there's nothing to do but wait' is misleading at best, because as we know, the problem didn't exist prior to this update.
> 
> But if we just say "oh, nothing can be done", then it's okay to do, well, nothing. And doing nothing is a lot easier than actually investigating the problem and determining the cause, which, to be clear, would not require _any_ programming knowledge because we have a version of the pack that does not have the problem.
> 
> If anyone is interested in actually solving it--
> 
>     1. Download and set up the server and client. Remove all mods except tech reborn and AE2 and their prerequisites, moving the others into separate folders.
> 
>     2. Start up server and client. Connect to localhost server.
> 
>     3. Check if bug exists via repro above - placing cable. If bug does _not_ exist... gasp, it isn't Fabric, and it isn't TR/AE2.
> 
> 
> These initial steps are pretty easy, which is why the only excuse to not do them is pretty much literally "I don't feel like it." Which is everyone's right, but it's not a professional way to address such a wide issue. Especially when this pack has had other sporadic block update issues - determining the cause of this problem could end up solving a lot more.
> 
> If the bug does not exist in the TR/AE2 only 'pack', the next step is binary search in the same vein as github bisect.
> 
>     1. Add half the mods back to the server and client.
> 
>     2. Start up server and client. Connect to localhost server. Test if bug exists.
>        3a. If bug doesn't exist, go to step 1.
>        3b. If bug exists, the cause is in the mods just added. _Remove_ half of them without removing TR/AE2 or prereqs.
>        3a1. If the bug still exists, continue to remove half until it doesn't.
> 
> 
> By following this kind of process, the mod causing the bug can be narrowed down from ~350 mods in approximately 8 iterations of testing at most. That's still _annoying_, but it's not some daunting hell-task.

The "other broken block updates" you referred to are not the cause. Mossy stone and all mossy variants from Valley were due to the mod itself, which the developer fixed. But you probably think the cause was because of recipe changing. Most of the bugs that have became solved are 9/10 due to the mod itself. But I don't expect you to know this. 

Why do people think editing recipes means breaking things? If you do not understand how.recipes are modified, or how a recipe serialized and datapacks work, please do not comment on it. Placing potential blame on customizing recipes which has absolutely zero to do with Rendering doesn't work for me. 

It doesn't matter if it worked before, this last update updated over 70 mods, including fabric API, which made major changes. Sorry I can't spend 40 hours testing every mod  every interaction possible before release, it's just me making this modpack. Sorry I have teo kids, a full time job, and another modpack and servers to maintain. My bad man, I'll be sure to make sure everything is perfect for you on next release.

**Comment by klassekatze** [comment]
> The "other broken block updates" you referred to are not the cause. Mossy stone and all mossy variants from Valley were due to the mod itself, which the developer fixed. But you probably think the cause was because of recipe changing. Most of the bugs that have became solved are 9/10 due to the mod itself. But I don't expect you to know this.
> 
> Why do people think editing recipes means breaking things? If you do not understand how.recipes are modified, or how a recipe serialized and datapacks work, please do not comment on it. Placing potential blame on customizing recipes which has absolutely zero to do with Rendering doesn't work for me.
> 
> It doesn't matter if it worked before, this last update updated over 70 mods, including fabric API, which made major changes. Sorry I can't spend 40 hours testing every mod every interaction possible before release, it's just me making this modpack. Sorry I have two kids, a full time job, and another modpack and servers to maintain. My bad man, I'll be sure to make sure everything is perfect for you on next release.

I don't think it is because of recipes - I only mentioned recipes because the fact that late-game AE2 and TR items are now needed in other mods means that bugs affecting AE2/TR consequently make it more difficult to get those things too. This doesn't change the bug, but it means that the impact of the bug is broader.

The issue is not a rendering issue, because when AE2/TR things vanish, they're not there on the client at all, including physically - you can walk into the space only to get reset back by the server in the same way as in other situations where a block exists on the server but isn't reflected in the client. If I had to speculate, it's an issue with some mod running code on block updates and causing a fail state when 'updating' these things but not when putting them in place of air, causing the observed 'flip flopping'.

I'm sorry if you took offense to what I said. To be frank, my salt was never about you being obligated to fix anything, but how quickly the issue was closed on the basis of (presumably) not being fixable, rather than that you didn't have time or what-have-you.

Regardless, you're right - you don't owe me or anybody else a thing. Which is why when it was originally closed I didn't say anything more until this chap showed up, and while I was passive aggressive about it all my suggestions were directed as much at him as anybody else.

I can't throw stones when I can't be arsed to investigate it myself, after all.

**Comment by itsdinkd** [comment]
> > The "other broken block updates" you referred to are not the cause. Mossy stone and all mossy variants from Valley were due to the mod itself, which the developer fixed. But you probably think the cause was because of recipe changing. Most of the bugs that have became solved are 9/10 due to the mod itself. But I don't expect you to know this.
> > Why do people think editing recipes means breaking things? If you do not understand how.recipes are modified, or how a recipe serialized and datapacks work, please do not comment on it. Placing potential blame on customizing recipes which has absolutely zero to do with Rendering doesn't work for me.
> > It doesn't matter if it worked before, this last update updated over 70 mods, including fabric API, which made major changes. Sorry I can't spend 40 hours testing every mod every interaction possible before release, it's just me making this modpack. Sorry I have two kids, a full time job, and another modpack and servers to maintain. My bad man, I'll be sure to make sure everything is perfect for you on next release.
> 
> I don't think it is because of recipes - I only mentioned recipes because the fact that late-game AE2 and TR items are now needed in other mods means that bugs affecting AE2/TR consequently make it more difficult to get those things too. This doesn't change the bug, but it means that the impact of the bug is broader.
> 
> The issue is not a rendering issue, because when AE2/TR things vanish, they're not there on the client at all, including physically - you can walk into the space only to get reset back by the server in the same way as in other situations where a block exists on the server but isn't reflected in the client. If I had to speculate, it's an issue with some mod running code on block updates and causing a fail state when 'updating' these things but not when putting them in place of air, causing the observed 'flip flopping'.
> 
> I'm sorry if you took offense to what I said. To be frank, my salt was never about you being obligated to fix anything, but how quickly the issue was closed on the basis of (presumably) not being fixable, rather than that you didn't have time or what-have-you.
> 
> Regardless, you're right - you don't owe me or anybody else a thing. Which is why when it was originally closed I didn't say anything more until this chap showed up, and while I was passive aggressive about it all my suggestions were directed as much at him as anybody else.
> 
> I can't throw stones when I can't be arsed to investigate it myself, after all.

Understood. I didn't know it was server side as I've been getting told it disappeared and as this issue says, vanished. 

I probably should not have closed the issue so suddenly. I agree with you. I was planning however for someone to get back to me on my suggestion with removing indium and iris, though that's my fault for expecting that and not specifically saying that, not that it would have fixed anything since it Is server side as well.  But please understand behind the scenes, we've been discussing this and I'm getting some help on the testing front to solve this and also the issue with structures. That's the shitty thing about large updates, it's a pain in the ass to debug when you have 60 to 80 mods update. Long story short, we're investigating the matter and as soon as the cause is solved (structures missing has been pretty much found out, it's a issue with bclib, terraliths 2.0.12 update, and Better End / better nether mods. The developers are all aware. Pretty sure SeedFix is the cause) I will be creating the issues so get the problem sorted out. 

I'd archive 2.0.2+ but at this point I cannot since many servers are using it. I do not want to screw over their players not being able to join and forcing them to downgrade. 

I as well should not have been so passive aggressive as I mainly took out what he said on you. Apologies.

**Comment by itsdinkd** [comment]
Found the cause.

Graves 2.0r1 dependency, Polymer is the cause. newer versions of polymer is the culprit. to fix, downgrade graves to graves-2.0.0-beta.4.2+1.18.1
