### ISSUE TITLE
Hostile mobs don't spawn exept for mob spawners[BUG]

### ISSUE THREAD

**Issue by Ruelfighter** [itsdinkd/AQM2#113]
**Modpack Version**
1.6.2

**Minecraft Version**
1.18

**Describe the crash or bug**
Hostile mobs don't seem ti spawn. We explored many caves without encontering mobs of any type except bosses and mobs from spawners

**Comment by itsdinkd** [comment]
did you check the mob spawn game rule

**Comment by LiGyH** [comment]
I also do not have enemy mobs, in server properties set  spawn-monsters=true

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
