### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by JesusDeLupa** [itsdinkd/AQM2#114]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**

I just wish we had more machines and stuff like that, i love the modpack, but i miss some industry things, like create mod, industrial foregoing or cyclic.

**Why do we need this feature?**

To increase the power of making farms and all that stuff

**Link to the modpage if mod?**
This is required if you are suggesting a mod to add
https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing
https://www.curseforge.com/minecraft/mc-mods/create
https://www.curseforge.com/minecraft/mc-mods/refined-storage
https://www.curseforge.com/minecraft/mc-mods/cyclic
https://www.curseforge.com/minecraft/mc-mods/bonsai-trees
https://www.curseforge.com/minecraft/mc-mods/forestry

**Additional context**

**Comment by itsdinkd** [comment]
Did you just like find mods you like without seeing if they are for the proper modloaders / mc versions? 90% of these are for forge, 1 is for 1.16, and the last, bonsai tree's, we already have in aqm2
