### ISSUE TITLE
[BUG] game gets stuck on 100% 

### ISSUE THREAD

**Issue by Llama0319** [itsdinkd/AQM2#114]
**Modpack Version**
The latest, version, 1.6.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
world gets stuck on loading at 100%

**Steps to reproduce the behavior:**
try to load a world

**Expected behavior**
world gets stuck loading on 100%

**Screenshots**
![image_2022-10-21_215427470](https://user-images.githubusercontent.com/73070350/197311389-627a0f89-a573-4018-97d6-2c1c1793bb65.png)

**Crash log or latest.log.log**
(https://pastebin.com/suC00cvf)

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/197320482-2a5bdab7-7462-4e2b-b50e-5ade847be5b9.png)
Forgot probably the most important part. What is the version of the modpack

**Comment by Llama0319** [comment]
The latest, version, 1.6.3

**Comment by Llama0319** [comment]
is this fixed yet?

**Comment by itsdinkd** [comment]
> is this fixed yet?

Nope. I cannot recreate so I don't know what there is to fix. Seems like this is only happening to you. my guess is your world is corrupted, try creating a new world and see if it that works.

**Comment by Llama0319** [comment]
it does work perfectly fine, and that's ok, ill just make a new world
