### ISSUE TITLE
Blacksmith Origin Bugged

### ISSUE THREAD

**Issue by BlackInkBlood** [itsdinkd/AQM2#115]
I'm playing on a private server and use the blacksmith origin. At first it worked, but now no matter the "rarity" of the armor I craft, it has the same stats. If I change origins to something other than blacksmith, it works perfectly. Version 1.6.1.

**Comment by xErrorAmelie** [comment]
I can confirm that. https://github.com/apace100/origins-classes/issues/66

**Comment by itsdinkd** [comment]
Nothing i can do on my end except for remove blacksmith from being a choice in the next update. I recommend changing your class, also please use the bug template that is provided when creating a issue.
