### ISSUE TITLE
Mobz crash for pillager boss[BUG]

### ISSUE THREAD

**Issue by chrisyoda** [itsdinkd/AQM2#115]
**Modpack Version**
What modpack version
2.0.2a
**Minecraft Version**
What mc version
1.18.1
**Describe the crash or bug**
When using the  sacrifice knife on the totem to summon the boss it crashes the users  of knight and if on server it crashes the server 

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
 use  sacrifice knife on totem for pillager boss
**Expected behavior**
What is the expected outcome?
crash game and close completely
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log
https://pastebin.com/JAeL5X7r
**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
does this still happen on latest version? if it does, let me know and I will re-open
