### ISSUE TITLE
[BUG] Diorite in a grinder produces gravel instead of diorite dust

### ISSUE THREAD

**Issue by OlliWare** [itsdinkd/AQM2#116]
**Modpack Version**
1.6.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Bug, putting a block of diorite in tech reborn's grinder produces gravel and not diorite dust.

**Steps to reproduce the behavior:**
Put a block of diorite into a powered grinder.

**Expected behavior**
Diorite dust.

**Screenshots**
![diorite](https://user-images.githubusercontent.com/40526145/198835495-c3a61b16-2d7b-4d4f-98da-45a4b3545cba.png)
![javaw_HVnxCW1Taf](https://user-images.githubusercontent.com/40526145/198835418-5903885c-521d-45b0-97f7-bece3881dd32.gif)

**Crash log or latest.log.log**
--

**Additional context**
If possible, please make it so a blockus:marble block also produces marble dust in the techreborn:grinder, since that is also missing a recipe.

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
