### ISSUE TITLE
[BUG] Crash stops rejoining world

### ISSUE THREAD

**Issue by Celeaxy** [itsdinkd/AQM2#117]
**Modpack Version**
1.6.2a and 1.6.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
After putting a magicite into the magitek armor, game crashes and stops rejoining to the world. 

**Steps to reproduce the behavior:**
Putting a magicite into a magitek armor will do the trick. Happened on my server and does the same in local game. Tried with 1.6.3 and 1.6.2a.

Log to big for pastebin:
[latest.log](https://github.com/itsdinkd/AQM2/files/9895657/latest.log)

**Comment by xErrorAmelie** [comment]
https://gitlab.com/DigiDigi/mtmechs/-/issues/17 I reported it on the github from that mod, looks like the dev will fix it soon :)

**Comment by xErrorAmelie** [comment]
Oh and they fixed it now

**Comment by Celeaxy** [comment]
wow that was fast

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
