### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eyesoffaith** [itsdinkd/AQM2#118]
**Modpack Version**
2.0.2

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Not really a bug but the End Goblin add-on config file is included in the pack but the .jar for the mod is not.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Download the pack and check the /mods folder.

**Expected behavior**
What is the expected outcome?
end-goblin-traders-1.4.2.jar visible in /mods folder

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
This is because end goblin traders was removed. Don't pay too much attention to configs that exist and their mods not. I need to do a clean up.
