### ISSUE TITLE
[BUG] Server crashes when using a Buter Wucket on a Brewer with hopper :)

### ISSUE THREAD

**Issue by berni1212** [itsdinkd/AQM2#118]
**Modpack Version**
1.6.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
When having a Brewer with a Hopper under it and placing the Buter Wucket in it on the Water slot the server instand crashes :)

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Place a Bater Wucket in the Tank slot of the Brewer from Adorn
**Expected behavior**
Expected behavior would be not to crash the server and leave the Bater Wucket in the slot

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
https://gist.github.com/11bbe363e37b13c07e642fd67e241e47

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
