### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nocaremc** [itsdinkd/AQM2#119]
**Modpack Version**
What modpack version
AQM2-2.0.2a

**Minecraft Version**
What mc version
1.18.1

**Describe the crash or bug**
Teeny Torches allows for imbalanced torch creation.

**Steps to reproduce the behavior:**
1. Craft 1 Stick into 9 Teeny Sticks
2. Craft 1 Coal into 9 Teeny Coal
3. Craft 9 Teeny Stick and 9 Teeny Coal into 324 Teeny Torches
4. Craft 324 Teeny Torches into 36 Torches

**Expected behavior**
What is the expected outcome?
While I like cheap torches I would expect this closer to 4 than 36. Even 8 or 12 would be a little better given time spent crafting.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
I found this while playing on the abyss server.

**Comment by itsdinkd** [comment]
This isn't a bug but a feature request.
