### ISSUE TITLE
[BUG] Client-Crash rendering Mystic Mounts (while Join Server)

### ISSUE THREAD

**Issue by Baromeus** [itsdinkd/AQM2#119]
**Modpack Version**
1.6.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Client Crashes while connecting to Server
(start of rendering the scene) while a Mystic mount is in Render-Distance

**Steps to reproduce the behavior:**
Log in while Mount is in Redner distance (seems to not happen to anyone)

**Expected behavior**
Connect to Server without crashing i guess

**Screenshots**
Sorry, not Fast enough to press F2 in that one Frame that is rendered

**Crash log or latest.log.log**
https://pastebin.com/aB4wDQ2p

**Additional context**
Crash does not happen always - for example:
if I put the mount on my yard, logging out of server and reconnect (without restarting Minecraft) I don't have a problem.
If i restart Minecraft as a whole and reconnect it will Crash. 

I had this Crash with the Lizard and the Moth but it will most likely happen with any mount of Mystic Mounts

**Comment by itsdinkd** [comment]
this should be reported to the developer of mythic mounts. also a crash log would help as there isn't any crash occurring in the log provided
