### ISSUE TITLE
[BUG][1.1.2] spawners can't be picked with silk touch anymore

### ISSUE THREAD

**Issue by FederAndInk** [itsdinkd/AQM2#12]
**Modpack Version**
1.1.2

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Spawners can't be picked with silk touch anymore, tried  with silktouch pickaxe (even end gobber one) and steam mining drill

**Steps to reproduce the behavior:**
mine a spawner with silk touch

**Expected behavior**
the spawner should drop intact

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Should be fixed in 1.2
