### ISSUE TITLE
[Feature Request] Wolf Pelts

### ISSUE THREAD

**Issue by vydax** [itsdinkd/AQM2#120]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
a crafting recipe to change Better animal wolf pelts into MC dungeon wolf pelts, since its armor is uncraftable atm.

**Why do we need this feature?**
MC Dungeon Wolf armor is uncraftable aswell as its upgrade to black wolf armor since its pelts dont drop from wolfs because Better Animals overwrites wolf drops withtheir pelts.

**Additional context**
https://i.imgur.com/cQH777Y.png

**Comment by itsdinkd** [comment]
Is this still occuring?
