### ISSUE TITLE
[BUG] Vanilla item animations don't work / are buggy

### ISSUE THREAD

**Issue by xErrorAmelie** [itsdinkd/AQM2#120]
**Modpack Version**
1.6.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
The animation from the vanilla bow, crossbow and fishing rod in the toolbar don't work. 
Also held bows don't show the loaded arrow in first person and third person, same with the fishing rod and their cast status.
This bug doesn't happen with modded items.

**Steps to reproduce the behavior:**
Use one of the named items.

**Expected behavior**
Normally the HUD shows the state of the bow, from tensioned to not.
Also the bow shows the arrow when it is loaded on the character model and HUD.
The fishing rod should show if it is cast or not. Both in the HUD and character.

**Screenshots**
https://www.youtube.com/watch?v=Yj36onpRiGg
Comparison between vanilla item animation and modded item animation.

**Crash log or latest.log.log**
The log shows nothing relevant.
https://mclo.gs/vqf0zSS

**Additional context**
This got reported in the AQM Discord by another user. I tested everything on the official AQM2 Server

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
