### ISSUE TITLE
[BUG] Disabled MCDoom Items are still lootable

### ISSUE THREAD

**Issue by xErrorAmelie** [itsdinkd/AQM2#121]
**Modpack Version**
1.6.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
After some player reports, it seems that the disabled mcdoom items are still lootable in chests etc. for example the soul cube and the daisy's foot. This got reported for private servers and the official servers.

**Steps to reproduce the behavior:**
Search lootable containers for the items.

**Expected behavior**
Disabled items shouldn't be findable.

**Comment by itsdinkd** [comment]
seems a newer doom update added more loot tables to generate the items in. the effects should be disabled though

**Comment by itsdinkd** [comment]
ill create a kubejs script though to remove it from all chests this time around. thanks for the report
