### ISSUE TITLE
REI not showing recipes and crashes if you search for specific items.

### ISSUE THREAD

**Issue by SergieXD** [itsdinkd/AQM2#123]
1.18.2

REI does not show how to craft the Fluid Pipe from "@create. I just randomly found out how to craft them pls fix.
And if you go on page 4 or 5 the game crashes.(picture)
The recipe to build the charger from "@Applied Energistics 2 is missing also.
![2023-01-01_16 46 50](https://user-images.githubusercontent.com/85365458/210184217-c4774bc1-1dd1-4fdb-b56e-8649d24191f5.png)

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
.

I will re-open if this still occurs
