### ISSUE TITLE
[BUG]Can't connect to server after enabling Night Vision Goggles from Gear Reborn

### ISSUE THREAD

**Issue by thesphealdeal** [itsdinkd/AQM2#124]
**Modpack Version**
What modpack version
1.0
**Minecraft Version**
What mc version
1.19.2
**Describe the crash or bug**
Can't connect to server after enabling Night Vision Goggles from Gear Reborn

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Turn on NVGs
**Expected behavior**
What is the expected outcome?
Immediate disconnect from server

**Comment by itsdinkd** [comment]
NVG Has been disabled in v1.1
