### ISSUE TITLE
[BUG] Silver Ore from tech reborn converts to industrial revolution ingots

### ISSUE THREAD

**Issue by xErrorAmelie** [itsdinkd/AQM2#125]
**Modpack Version**
1.0 

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When smelting tech reborn silver ore it converts to industrial revolution ingots, which makes it impossible to craft the tech reborn silver armor.

**Steps to reproduce the behavior:**
Smelt silver ore, try to craft silver armor out of the ingots.

**Expected behavior**
The silver ore should be a silver ingot from tech reborn after smelting.

**Screenshots**
Smelting tech reborn silver:
![grafik](https://user-images.githubusercontent.com/51492094/210396210-05cbdfbf-2487-4973-bb5b-ca8730f38277.png)

Crafting the chestplate with industrial revolution ingots, doesn't work:
![grafik](https://user-images.githubusercontent.com/51492094/210386720-c21aea79-efcf-44a8-8830-b22b426de8e5.png)

The recipe viewed in REI:
![grafik](https://user-images.githubusercontent.com/51492094/210386735-4945fd2e-c01c-49b0-aed7-eb3f430b30b3.png)

**Crash log or latest.log.log**
https://mclo.gs/eVKQqkB

**Comment by xErrorAmelie** [comment]
Even funnier is that silver ingots from industrial revolution don't exist in REI
![grafik](https://user-images.githubusercontent.com/51492094/210397533-5e2decac-3bf5-4d2e-9d30-1882122f481e.png)

**Comment by itsdinkd** [comment]
Fixed in 1.0.1

**Comment by itsdinkd** [comment]
By the way, all ingots are unified. so regardless of what the recipe says in REI, if you actually place all the ingots in you will be able to craft the armor you want.
![image](https://user-images.githubusercontent.com/35115304/210676421-80234a1a-bc4d-49b8-a23d-f322c0d9692b.png)

**Comment by xErrorAmelie** [comment]
I thought that too, but the picture where I said "Crafting the recipe with industrial ingots..." is actually my try of crafting it with the industrial silver ingots, where it didn't work. I played on bouji when I tried that.
