### ISSUE TITLE
Tech reborn chunk loader

### ISSUE THREAD

**Issue by T-HomesJr** [itsdinkd/AQM2#126]
Chunk loader doesn't work
- only shows 1 chunk radius
- not able to configure the radius with the buttons in the hud 
- you are able to put tech reborn upgrades(oc upgrade etc) into it?!

I'm running a server on Bisecthosting v2.0.3.
If you want pictures for the named issue, I can provide you these.

**Comment by itsdinkd** [comment]
This is a known bug with TR Chunk Loader. I don't care about it since I disabled all chunk loaders, I would recommend reporting this to Tech Reborn.
