### ISSUE TITLE
[BUG] The Nether will crash your game currently

### ISSUE THREAD

**Issue by xErrorAmelie** [itsdinkd/AQM2#129]
**Modpack Version**
1.0.1hf

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Hellhounds from bewitchment are crash-looping the client currently, so going to the nether is not possible right now.
Disabling the hellhound mob could be a solution to that.

**Steps to reproduce the behavior:**
Go to the nether and find a hellhound in your render distance

**Additional context**
https://github.com/MoriyaShiine/bewitchment/issues/342

**Comment by itsdinkd** [comment]
Can you provide crash report?

**Comment by xErrorAmelie** [comment]
crash-report: https://mclo.gs/Zv85yYp

**Comment by itsdinkd** [comment]
Fixed in next version
