### ISSUE TITLE
[Suggestion] Vampirism

### ISSUE THREAD

**Issue by ZakuPilotHiggs** [itsdinkd/AQM2#13]
**Is your feature request/suggestion related to a problem? Please describe.**
Not really a problem, just wanted more things to do as a vampire.

**Describe the suggestion you'd like**
Either a way for the Origin Vampire to be compatible or a replacement so being a vampire has more fun choices.

**If this is a request to add a mod, what is the curseforge link?**
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire

**Why do you think this would benefit the modpack?**
Since there's coffins and whatnot, I know there's the vampire Origin, but this one would be more advance, if anything maybe a replacement? I didn't knew that this mod was still being developed until recently and thought it would be a nice fit with Bewitchment mod.

**Additional context**
Add any other context or screenshots about the feature request/suggestion here.

**Comment by SpinHarmony** [comment]
Vampirism is a Forge-exclusive.
