### ISSUE TITLE
[BUG] Chiseled Block + Carryon crash

### ISSUE THREAD

**Issue by mashironn** [itsdinkd/AQM2#130]
**Modpack Version**
AQM2 V1.0.1hf (1.19.2)(1.19.3)

**Minecraft Version**
1.19.3?

**Describe the crash or bug**
when you pick up chiseled block and if it tried to render it'll crash
but if the chiseled block dont render it wont crash

**Steps to reproduce the behavior:**
chiseled a block then Shift + Right Click to pick it up then if it still doesn't crash try F5 

**Expected behavior**
Crash

**Screenshots**
https://media.discordapp.net/attachments/970214826271965194/1062130217658884137/2023-01-09_15.05.57.png?width=955&height=502

**Crash log or latest.log.log**
https://pastebin.com/0h7FvEQY

**Additional context**
It only crash when the game tried to render the chiseled block that you pick up

**Comment by xErrorAmelie** [comment]
Perfect, thanks

**Comment by itsdinkd** [comment]
```
at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:596)
at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:475)
at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:801)
at net.minecraft.class_761.handler$hlh000$iris$renderTerrainShadows(class_761.java:18536)
```

looks to be an issue with Carry On and Iris? i'd recommend reporting to them

**Comment by mashironn** [comment]
> ```
> at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:596)
> at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:475)
> at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:801)
> at net.minecraft.class_761.handler$hlh000$iris$renderTerrainShadows(class_761.java:18536)
> ```
> 
> looks to be an issue with Carry On and Iris? i'd recommend reporting to them

can I link this thread to Carry On and Iris bug report ?

**Comment by xErrorAmelie** [comment]
https://github.com/Tschipp/CarryOn/issues/445 forwarded it to CarryOn

**Comment by itsdinkd** [comment]
in the mean time i blacklisted bits and chisels
