### ISSUE TITLE
[BUG] Enchanted Sheep Mc Dungeon Artifacts Crash

### ISSUE THREAD

**Issue by itsdinkd** [itsdinkd/AQM2#130]
**Modpack Version**
2.0.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Using enchanted grass to spawn a sheep and having said sheep attack a mob crashes client/

**Steps to reproduce the behavior:**
1. Use Enchanted Grass
2. Attack Mob
3. Sheep attacks > Crash.

**Comment by busterbrown1999** [comment]
Fixed in 2.0.5
