### ISSUE TITLE
[Feature Request] Paradise Lost

### ISSUE THREAD

**Issue by vydax** [itsdinkd/AQM2#131]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Adding Paradise Lost , because the  Aether ofcourse its currently in beta 1.18.1 but can be downloaded and all already

**Why do we need this feature?**
adds the aether to the modpack

**Link to the modpage if mod?**
https://www.curseforge.com/minecraft/mc-mods/paradise-lost

**Comment by itsdinkd** [comment]
Not enough content yet
