### ISSUE TITLE
[BUG] Crash when spreading items on crafting bench

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#131]
**Modpack Version**
AQM2 1.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Slid a stack of copper ingots across the top row of crafting bench (for pickaxe)

**Steps to reproduce the behavior:**
As above

**Expected behavior**
3 evenly split stacks

**Screenshots**
*none*

**Crash log or latest.log.log**
https://pastebin.com/GefvRMJg

**Additional context**
Never had an issue with this before, so it may be difficult to reproduce, hopefully the crashlog has something useful

**Comment by itsdinkd** [comment]
This was mainly because of Create's porting lib
```
at net.minecraft.class_1309.handler$zcg000$port_lib$spawnDropsTAIL(class_1309.java:5701)
```

which has been downgraded in 1.2 as that version of porting lib was causing a lot of crashes. closing for now
