### ISSUE TITLE
Steam drill does not collect redstone of any sort from 'nether redstone ore' [BUG]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#133]
**Modpack Version**
v1.1 

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When using a steam drill on nether redstone ore it does not collect anything. I have tried this in both silktouch and standard mode and both are the same result, block breaks and no returns. Mining with a standard diamond pickaxe returns redstone as one would expect.

**Steps to reproduce the behavior:**
Use a steam drill on 'nether redstone ore' and check for restone or blocks in inventory.

**Expected behavior**
redstone ore of some sort

**Screenshots**
![image](https://user-images.githubusercontent.com/26475624/212501993-851b8bc7-3595-4a46-9daa-977c65099482.png)

**Crash log or latest.log.log**
-

**Additional context**
-

**Comment by itsdinkd** [comment]
bno has been removed
