### ISSUE TITLE
[Feature Request] Macaw's Decoration mods

### ISSUE THREAD

**Issue by vydax** [itsdinkd/AQM2#134]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Macaw has a lot of decoration mods which might be nice for the people looking more for the decoration side of the modpack.
Lights and lamps, walls and fences, trapdoors etc.

dont have to add but for the builders out there this is a nice addition.

**Why do we need this feature?**
all the extra decoration items.

**Link to the modpage if mod?**
- Light and Lamps https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps
- Fences and Walls https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls
- Trapdoors https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors
- Paintings https://www.curseforge.com/minecraft/mc-mods/macaws-paintings
- doors https://www.curseforge.com/minecraft/mc-mods/macaws-doors
- Furniture https://www.curseforge.com/minecraft/mc-mods/macaws-furniture

**Comment by itsdinkd** [comment]
Added a couple
