### ISSUE TITLE
[BUG] Can't craft AE2 seeds

### ISSUE THREAD

**Issue by Cookiedust** [itsdinkd/AQM2#135]
**Modpack Version**
AQM 2 1.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
I'm unable to craft fluix seeds or certus quartz seeds (they don't seem to exist) which means that I can't complete the quest "Growing Crystals".

**Steps to reproduce the behavior:**
Attempt to craft fluix crystal seed or certus quartz seed. Look in REI, no recipe.

**Expected behavior**
AE2 seeds exist, can be crafted and the quest completed.

**Screenshots**
![image](https://user-images.githubusercontent.com/48491154/212542380-a266bc0c-fad1-46b4-960b-1ccded9e40b9.png)
![image](https://user-images.githubusercontent.com/48491154/212542422-f7466b2b-17d7-4aa6-8789-bcb9d3a56ca1.png)
![image](https://user-images.githubusercontent.com/48491154/212542447-051bc732-22e9-4999-8166-2b3f41611472.png)

**Crash log or latest.log.log**
N/A

**Additional context**
N/A

**Comment by itsdinkd** [comment]
Yikes. yes i have to change this quest. these both now grows crystals in the world, you cant use seeds anymore.

**Comment by itsdinkd** [comment]
fixed in 1.2.1
