### ISSUE TITLE
[BUG] "Wildlife" mod fish do not work for making Aqua Cerate

### ISSUE THREAD

**Issue by ToastedEggplant** [itsdinkd/AQM2#136]
**Modpack Version**
V 1.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
None of the fish from the mod "Wildlife" work for making Aqua Cerate from the mod Bewitchment. The likely need to be added to the proper ore dictionary

**Comment by itsdinkd** [comment]
added in 1.2.1
