### ISSUE TITLE
[Feature Request] Neutrino Mod

### ISSUE THREAD

**Issue by FrostWizard4** [itsdinkd/AQM2#136]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
A while back I noticed that Curseforge said my mod was in AQM2, I decided to try it out and enjoy playing on it a lot. Neutrino adds miscellaneous items & blocks that are meant to enhance the vanilla Minecraft experience. For example, a Scarecrow was added for Halloween, an Alarm Clock lets you choose when you want to wake up, and many more different features that have been added over time.

**Why do we need this feature?**
I think the mod enhances the vanilla experience, and makes the game more enjoyable, the configuration allows for disabling many features as well, such as the MC Dungeons Items, which I noticed are in your modpack. I don't know if the mod was ever in your pack, but if there was any reason behind removing it that I can change so it could be added back in, please let me know!

**Link to the modpage if mod?**
[Neutrino](https://www.curseforge.com/minecraft/mc-mods/neutrino)

**Additional context**
<img src="https://raw.githubusercontent.com/FrostWizard4/Neutrino/1.17.1/Wiki-Images/main-page.png" width="500">

**Comment by itsdinkd** [comment]
It was in a unreleased version but I noticed the duplicate items from MCDAR so I removed the mod. There were a couple issues with artifacts as well that threw me off, though I can't remember which ones at this time as it was a while ago.

**Comment by srwxr-xr-x** [comment]
I assumed it would be duplicates in MCDAR, and the artifacts have been buggy, so that makes sense, the MCD items are able to be disabled in the mod's config. Thanks for the reply.
