### ISSUE TITLE
Add the Backslots and Backslots Addon mods

### ISSUE THREAD

**Issue by Boinglegs** [itsdinkd/AQM2#137]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
It's adding a couple of mods that add a couple more slots for tools/weapons.

**Why do we need this feature?**
You don't really need this feature, I've just been playing on a server with this pack with these two mods added into it and it really makes things a lot better considering all the different tools that are in this modpack.

**Link to the modpage if mod?**
Backslot: [https://www.curseforge.com/minecraft/mc-mods/backslot](url)
BackslotAddon: [https://www.curseforge.com/minecraft/mc-mods/backslotaddon](url)

**Comment by itsdinkd** [comment]
Had it in 1.17 aqm2, wasnt a fan.
