### ISSUE TITLE
Crash report for crash when collecting quest reward for emerald block (spelunkery?) [BUG]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#138]
**Modpack Version**
AQM2 1.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Collecting the quest item reward for the emerald block (for Spelunkery mod?) and the game crashed the moment I clicked it.

**Steps to reproduce the behavior:**
Collected reward with the picture of the emerald block

**Expected behavior**
What is the expected outcome?

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
https://pastebin.com/aBKX1EG1

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Same as your other report. stack trace is saying this is porting lib, creates library.
