### ISSUE TITLE
[BUG] Game crashes when killing the Enderdragon

### ISSUE THREAD

**Issue by Laizaz** [itsdinkd/AQM2#139]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
The Game crashes when the Enderdragon dies

**Steps to reproduce the behavior:**
To get the crash kill the Enderdragon in single player

**Expected behavior**
World crashes and sends you to server list

**Crash log or latest.log.log**
[crash-2022-02-18_05.56.52-server.txt](https://github.com/itsdinkd/AQM2/files/8094254/crash-2022-02-18_05.56.52-server.txt)

**Comment by itsdinkd** [comment]
Next time please follow the template on the part you deleted "upload logs to pastebin.com". I do not want to download 100s of logs a day. 

You are on such a old version, try updating. Haven't had this report in recent versions.
