### ISSUE TITLE
[Feature/Suggestion]

### ISSUE THREAD

**Issue by Familiarityy** [itsdinkd/AQM2#14]
**Is your feature request/suggestion related to a problem? Please describe.**
Curseforge is often down and has problems
**Describe the suggestion you'd like**
The addition of AQM to modrinth.com
**If this is a request to add a mod, what is the curseforge link?**
N/A
**Why do you think this would benefit the modpack?**
It would possibly bring in more users, and would give a less buggy way to update the modpack
**Additional context**
Add any other context or screenshots about the feature request/suggestion here.
I personally find modrinth a lot better than curseforge, and have only used curseforge for modpacks. Now that modrinth has modpacks on their website, I think it would be helpful to also upload the modpack there, where I believe it's simpler to update and where there aren't as many server errors as with curseforge.

**Comment by fallinforya** [comment]
havent seen this one yet, but if it supports spacebars i am absolutely in (try searching for an unknown modpack that has the same word at the start as a few big ones, no way you will find it since only the first letters until a spacebar comes will be registered by curseforge...)

**Comment by itsdinkd** [comment]
I will not be doing this unless modrinth has a tool that allows me to upload 600mb in minutes.  with curseforges new API and taking away the old one, it now takes me half an hour to just upload the server pack and set up how I need it to be set up for curseforge. Modrinth will require something different.

**Comment by itsdinkd** [comment]
Another thing is curseforge has author credits, modrinth does not.
