### ISSUE TITLE
[BUG] Cannot produce AE2's engineering/logical processor using Create mod

### ISSUE THREAD

**Issue by MartianSheep** [itsdinkd/AQM2#140]
**Modpack Version**
1.6.5

**Minecraft Version**
1.18.2

**Describe the crash or bug**
In this mod, AE2's processors can only produce by Create mod's recipe sequence (deploy, press...). Note that though "inscriber" is an option in REI, but the crafting recipe of the inscriber is removed.
But after some simple experience we found out that the sequence always produces calculation processors, instead of engineering processor or logic processor. We also found out that, after the first deploy the game can still distinguish the difference between the silicon circuit deployed with different printed circuits, but after the second deploy (where the deployer deploys a redstone) the game can no longer distinguish them. Thus, the press always produce a calculation circuit.
We know that there's a 80/20 chance the press produces something not expected, but we think that the program have no clue what is the "80% result" if it cannot tell those different inputs apart.

**Steps to reproduce the behavior:**
1. Build a simple Create mod's crafting recipe sequence, with 2 deployer and 1 press.
2. At the second deployer, put redstone in.
3. At the first deployer put a printed calculation/engineering/logic circuit in. Put a printed silicon on the first depot, obtain the printed silicon after the deploy.
4. Put the deployed circuit on the second depot, obtain the results.
5. Repeat 3-4 with different printed circuits. You will discover all the outcomes can stack, which means that the game cannot tell those deployed printed silicons apart.
6. Put all your deployed printed circuits on the third depots. After the press, you got tons of calculation processor, instead of engineering/logic processor.

**Expected behavior**
The game should be able to distinguish different printed silicons, since they are deployed with different printed circuits. So the program is able to decide what is the "80% chance" outcome.

**Screenshots**
Instead of screenshots we provide you with a video recording:
https://youtu.be/LdHbrxa8gsA
(BTW sorry for the bad audio)

**Comment by itsdinkd** [comment]
These are now crafted via Botania mana pools as the last patch note mentioned.

Check REI again and look for the botania recipe.
