### ISSUE TITLE
[BUG] Copper pickaxe mines rough diamond ore

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#141]
**Modpack Version**
1.2

**Minecraft Version**
1.19

**Describe the crash or bug**
Copper pickaxe mines rough diamond ore from diamond blocks, even though it shows as being unmineable in the info (at top of window)

**Steps to reproduce the behavior:**
mine copper ore with pickaxe

**Expected behavior**
nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/26475624/213004603-95c0e5dd-0c11-447d-a6ce-ee5ba1544a90.png)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
which copper pickaxe is this? there's multiple. is this indrev?

**Comment by NyarlathotepZERO** [comment]
![image](https://user-images.githubusercontent.com/26475624/213013082-f40092ea-00fa-481d-9ff7-0d8c7899b311.png)

**Comment by NyarlathotepZERO** [comment]
I just tried it again and the rough ore did not drop. Perhaps it *was* mined with iron, but it flicked back to the copper pickaxe before I noticed the switch. 

edit: tried a second time and again it did not drop, I'd suggest closing this issue.
