### ISSUE TITLE
[BUG] Server AQM2 v2.0.5 crash on first load

### ISSUE THREAD

**Issue by jjamesk** [itsdinkd/AQM2#141]
**Modpack Version**
AQM2 v2.0.5

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Server wont start after a fresh installation on Linux (debian 11 java 17)

Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.12.12 (/home/aqm2/libraries/net/fabricmc/fabric-loader/0.12.12/fabric-loader-0.12.12.jar) with version 0.13.0 or later.
Unmet dependency listing:
	 - Mod 'Architectury' (architectury) 3.7.22 requires version 0.13.0 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.12!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.12 is being loaded from /home/aqm2/libraries/net/fabricmc/fabric-loader/0.12.12/fabric-loader-0.12.12.jar

**Crash log or latest.log.log**
https://pastebin.com/RRTk6tFq

**Additional context**
Any additional context?

**Comment by jjamesk** [comment]
updated fabric-loader/0.12.12/fabric-loader-0.12.12.jar to fabric-loader/0.13.2/fabric-loader-0.13.2.jar as a work around

**Comment by itsdinkd** [comment]
Not the work around, but the solution. please check change logs, when a update requires a new modloader version, it is stated on the changelog

**Comment by jjamesk** [comment]
> Not the work around, but the solution. please check change logs, when a update requires a new modloader version, it is stated on the changelog

I disagree, it should be fixed in the pack rather than telling others to do so.

**Comment by itsdinkd** [comment]
Server start downloads it automatically, every time. So you did something
wrong. Most likely by not transferring the library that server start
downloads.

**Comment by itsdinkd** [comment]
Also, most server packs do not use a automatic server installer. The server
owner is expected to grab the correct modloader version. So yes. You are
expected to read.
