### ISSUE TITLE
[BUG] Crash report for AQM2 v1.2

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#142]
**Modpack Version**
1.2

**Minecraft Version**
1.19

**Describe the crash or bug**
Crashed a couple of seconds after opening a chest

**Steps to reproduce the behavior:**
Not sure it is able to be replicated, but crash report may help to find the issue

**Expected behavior**
-

**Screenshots**
-

**Crash log or latest.log.log**
[pastebin link](https://pastebin.com/Q8MsqyXE)

**Additional context**
-

**Comment by itsdinkd** [comment]
This is a crash related to Create and its porting lib library. this is known unfortunately nothing I can do. go ahead and report to Porting Lib so more people can get them to fix it faster :) 

https://github.com/Fabricators-of-Create/Porting-Lib/issues

**Comment by NyarlathotepZERO** [comment]
> This is a crash related to Create and its porting lib library. this is known unfortunately nothing I can do. go ahead and report to Porting Lib so more people can get them to fix it faster :)
> 
> https://github.com/Fabricators-of-Create/Porting-Lib/issues

https://github.com/Fabricators-of-Create/Porting-Lib/issues/31#issuecomment-1398962894

**Comment by tlom** [comment]
Hello, I have the same problem with my current server on Version: 1.4.3hf
But my server does nor crash, it simply freezes, and I have to kill it manually.
Our fix for now is that we surround the chest or barrel with bedrock, so nobody opens it accidentally.

**Comment by itsdinkd** [comment]
> Hello, I have the same problem with my current server on Version: 1.4.3hf But my server does nor crash, it simply freezes, and I have to kill it manually. Our fix for now is that we surround the chest or barrel with bedrock, so nobody opens it accidentally.

You are on a very old version of the modpack.
