### ISSUE TITLE
[BUG] Crash in Nether + Aternos version stuck

### ISSUE THREAD

**Issue by OofyOwyOOF** [itsdinkd/AQM2#142]
**Modpack Version**
2.0.5

**Minecraft Version**
1.18.1

**Describe the crash or bug**
I was exploring in the Nether and found a nether temple, nearby and once I got in, I started crashing repeatedly. I tried everything, to removing the mod's data that was mentioned in the crashlog, to reinstalling the whole pack. It just wasn't working so I took a break. Now the version 2.0.5 is missing from my launcher and I'm stuck on 2.0.4.1, so I can't play on the Aternos server me and my friend was playing on, due to it automatically updating to the newest version so it's stuck at 2.0.5.

**Steps to reproduce the behavior:**
I can only assume it can be reproduced by entering a certain chunk in the Nether that includes a blackstone temple. Xaeno World Map keeps stating that it keeps crashing so I'm assuming it's classing with another mod?

**Expected behavior**
I tried over and over to log in, but after about 5 seconds, no matter what I did, my game instantly crashed, closing itself.

**Crash log or latest.log.log**
https://pastebin.com/4P1JQxGV

**Comment by itsdinkd** [comment]
Fixed with 2.0.6a
