### ISSUE TITLE
2x crash reports [BUG]

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#143]
**Modpack Version**
1.2
**Minecraft Version**
1.19.2

**Describe the crash or bug**
2x crash reports, one when paddling in a boat, the other when poking around in a castle village

**Steps to reproduce the behavior:**
Nothing unusual, probably cannot be replicated

**Expected behavior**
no crash was expected

**Crash log or latest.log.log**
https://pastebin.com/KWkbAxLZ
https://pastebin.com/tbnGXDVR

edit: And another couple of reports.
https://pastebin.com/2a3rCp8F

These last 2 are reports from a completely broken autosave, the game now crashes within seconds of loading.
https://pastebin.com/Atqw3Mnd
https://pastebin.com/taBTgiXD

**Comment by itsdinkd** [comment]
Same crash as your other ones. please look in your stack trace and if you see this **do not report**

`
	at net.minecraft.class_1309.handler$zcg000$port_lib$spawnDropsTAIL(class_1309.java:5701)
`

**Comment by NyarlathotepZERO** [comment]
> Same crash as your other ones. please look in your stack trace and if you see this **do not report**
> 
> `at net.minecraft.class_1309.handler$zcg000$port_lib$spawnDropsTAIL(class_1309.java:5701)`

https://github.com/Fabricators-of-Create/Porting-Lib/issues/31#issuecomment-1398962894

**Comment by NyarlathotepZERO** [comment]
> Same crash as your other ones. please look in your stack trace and if you see this **do not report**
> 
> `at net.minecraft.class_1309.handler$zcg000$port_lib$spawnDropsTAIL(class_1309.java:5701)`

Could I still be getting this line in a crashlog if I have disabled both these mods ? 
![image](https://user-images.githubusercontent.com/26475624/214139409-397e3339-91b8-401a-9660-28d3cf60b169.png)

**Comment by itsdinkd** [comment]
Remove porting lib
