### ISSUE TITLE
[BUG] Unable to complete 'Grow Crystals' quest

### ISSUE THREAD

**Issue by Wolfen198** [itsdinkd/AQM2#144]
**Modpack Version**
1.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Required recipes removed 
![image](https://user-images.githubusercontent.com/122255553/213669903-25a00a58-f1cb-4699-b3e0-4f720f9914e7.png)

![image](https://user-images.githubusercontent.com/122255553/213669942-77eca46a-df41-49ed-9d0a-972dec0b408f.png)
![image](https://user-images.githubusercontent.com/122255553/213669971-43e948fc-e153-4e4c-926d-8f61b05c1afe.png)

**Steps to reproduce the behavior:**
Attempt to craft sand with fluix crystals and be unable to do so.

**Expected behavior**
Ability to craft certus and fluix crystal seeds to complete the quest

**Crash log or latest.log.log**
N/A
**Additional context**
I assume the recipes were removed on purpose but forgotten in the quest list.

**Comment by itsdinkd** [comment]
#140 duplicate
