### ISSUE TITLE
Getting Cinnabar from redstone ore[BUG]

### ISSUE THREAD

**Issue by tdugger** [itsdinkd/AQM2#146]
**Modpack Version**
1.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When I mine redstone ore of any time, I 'm getting cinnabar from it.  Mining with iron and diamond.

**Steps to reproduce the behavior:**
should be easily reproducable. 

**Expected behavior**
should get redstone dust or similar.

**Comment by itsdinkd** [comment]
This is a feature. you need to use a grindstone to get redstone. there are quests on this that you completed once you received that cinnabar.
