### ISSUE TITLE
[BUG] Jotaro's hat bug

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#149]
**Modpack Version**
1.3

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Jotaro's hat which is offered as a reward (unique simplyswords) is unable to be found in REI, nor is the hat equipable once claimed.

**Steps to reproduce the behavior:**
claim jotaro's hat as a reward and try to equip it in any of the hat slots

**Expected behavior**
I'd expect the hat to be usable or removed from the game entirely ( if that is the intention)

**Screenshots**
![image](https://user-images.githubusercontent.com/26475624/215238551-766cdb0a-7872-4990-835e-532987e67fe6.png)

**Crash log or latest.log.log**

**Additional context**

**Comment by itsdinkd** [comment]
**Jotaro's hat which is offered as a reward (unique simplyswords)** 

What do you mean offered as a reward? 

this item is disabled

**Comment by NyarlathotepZERO** [comment]
> 

'unique simplyswords' quest reward
![image](https://user-images.githubusercontent.com/26475624/215259533-e4d2302d-ea9e-4115-9118-a95b57f04085.png)

**Comment by itsdinkd** [comment]
fixed
