### ISSUE TITLE
[BUG] Rendering certain blocks in Nether crashes

### ISSUE THREAD

**Issue by micahflack** [itsdinkd/AQM2#150]
**Modpack Version**
AQM2 1.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Server crashes whenever certain blocks from the BetterNether mod are within render distance. So far, I've confirmed that Barrel Cactus or Agave plants will cause the crash.

**Steps to reproduce the behavior:**
Create nether portal and enter it. Continue walking around the Nether until Barrel Cactus or Agave plants are within render distance. Server/instance crashes.

**Expected behavior**
Server shouldn't crash from rendering blocks.

**Screenshots**
N/A

**Crash log or latest.log.log**
https://pastebin.com/KCWAAGyf

**Additional context**
Better Nether 7.1.1 and 7.1.2

**Comment by micahflack** [comment]
In the meantime we've disabled the suspected blocks within the mod config and deleted the nether world to regenerate w/o those blocks

```
{
  "blocks": {
    ...
    "agave [default: true]": false,
    "barrel_cactus [default: true]": false,
    ...
    }
}
```

**Comment by itsdinkd** [comment]
Update your modpack
