### ISSUE TITLE
[BUG] Spelunkery Nephrite Charm crash

### ISSUE THREAD

**Issue by micahflack** [itsdinkd/AQM2#151]
**Modpack Version**
AQM2 1.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When using the NephriteCharm ability to save XP levels, the server crashes

**Steps to reproduce the behavior:**
Have a full experience bar with at least 1 level. Hold the Nepherite Charm and shift + click to save experience levels to the charm. Assuming it works, it should at least 30 levels of experience.

**Expected behavior**
Using the Nepherite Charm should save experience levels and not crash.

**Screenshots**
N/A

**Crash log or latest.log.log**
https://pastebin.com/jtmPmQ8V

**Additional context**
Spelunkery 1.19.2-0.1.4

**Comment by AstralOrdana** [comment]
no need to outright name _me_ in your bug report. I cant replicate the issue so more information is needed. First though, try to replicate this in the latest version of the mod

**Comment by itsdinkd** [comment]
that made me giggle i didnt notice they put your name in the title lol. 

I'll test it out on the latest version

edit: wow what a spicy update

**Comment by micahflack** [comment]
I just copied the relevant error line for the title, didn't know that was the author's name 🤷‍♂️

**Comment by itsdinkd** [comment]
Mod has been removed from the pack. The developer is a douche.
