### ISSUE TITLE
[BUG] Reference to incorrect result (AE2 quest)

### ISSUE THREAD

**Issue by NyarlathotepZERO** [itsdinkd/AQM2#152]
**Modpack Version**
1.3.1

**Minecraft Version**
-

**Describe the crash or bug**
Quest reads the outcome as being dust, but the result is actually crystal

**Steps to reproduce the behavior:**
-

**Expected behavior**
It should read as "it will create fluix crystal"

**Screenshots**
![image](https://user-images.githubusercontent.com/26475624/215731638-84079f8f-d14d-4c7e-b408-12cb028eabcf.png)

**Crash log or latest.log.log**
-

**Additional context**
-

**Comment by itsdinkd** [comment]
fixed
