### ISSUE TITLE
[BUG] AE2 Terminals glitchy gui

### ISSUE THREAD

**Issue by 4nner** [itsdinkd/AQM2#154]
**Modpack Version**
1.3.3

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Glitched interface with AE2 Wireless terminals

**Steps to reproduce the behavior:**
Just open an AE2 Wireless terminal

**Expected behavior**
The inventory should look normal

**Screenshots**
![image](https://user-images.githubusercontent.com/3206935/216787426-b8046063-10ee-4ff7-b832-46657f2f218a.png)

**Comment by itsdinkd** [comment]
Please report to AE2
