### ISSUE TITLE
[BUG] Block of Bauxite Paradox

### ISSUE THREAD

**Issue by Jirodyne** [itsdinkd/AQM2#156]
**Modpack Version**
What modpack version

AQM2 v1.3.3

**Minecraft Version**
What mc version

1.19.2

**Describe the crash or bug**

Block of Bauxite does show up in the REI client side, but is still craftable

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

9 Bauxite Dust to make a Block of Bauxite. The same you would make any other block of metal.

**Expected behavior**
What is the expected outcome?

Block of Bauxite to show up in the REI

**Screenshots**
Post screenshots if available

![Screenshot_4](https://user-images.githubusercontent.com/64215334/216889060-dd38c428-fd57-45b0-86b4-2d1f9db27ebe.png)

**Comment by itsdinkd** [comment]
fixed
