### ISSUE TITLE
[BUG]server starts crashing randomly

### ISSUE THREAD

**Issue by giovanny196** [itsdinkd/AQM2#158]
**Modpack Version**
1.3.3

**Minecraft Version**
1.19.2

**Describe the crash or bug**
i downloaded the server pack yesterday for me and my bf and we both also did a clean install of the mod (client side) and after a while it started crashes simply for killing a mob or looking somewhere and now it crashes the server on logging in .

**Steps to reproduce the behavior:**
i can't since it now crashes when trying to join it

**Expected behavior**
What is the expected outcome?

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
https://pastebin.com/kzr3H6rL

**Additional context**
Any additional context?
[crash-2023-02-09_07.47.20-server.txt](https://github.com/itsdinkd/AQM2/files/10694434/crash-2023-02-09_07.47.20-server.txt)

**Comment by itsdinkd** [comment]
Should be fixed in newer versions of aqm2. if not i would report to Soulslike Weaponry https://github.com/mariumbacchus/Soulslike-Weaponry
