### ISSUE TITLE
Nether Gobber ore not always dropping after mining with proper pickaxe[BUG]

### ISSUE THREAD

**Issue by Ironchestplate** [itsdinkd/AQM2#16]
**Modpack Version**
1.2.1

**Minecraft Version**
1.18

**Describe the crash or bug**
Nether Gobber Ore does not always drop upon break with level 4 pick

**Steps to reproduce the behavior:**
Mine the ore

**Expected behavior**
Should drop everytime

**Comment by itsdinkd** [comment]
Can you record a video? What enchantments? does this happen on 1.2.2?  What origin are you using? What is a proper pick axe? what pick axe are you using?

Your description is very vague
