### ISSUE TITLE
[BUG]Erratic chunk behavior on multiplayer

### ISSUE THREAD

**Issue by ArcaneDefence** [itsdinkd/AQM2#160]
**Modpack Version**
v1.3.3

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Multiple vanilla behaviors broken in ~15 chunks leading to lots of unexpected outcomes on my friend's public multiplayer server. These dysfunctional chunks block many machines from functioning inside them.

**Steps to reproduce the behavior:**
Connect to my friend's server, `15.235.118.68:2399` and go to the chunk indicated on the map's coordinates. 
Spawn is by the village, so it's just a short walk to the north west.
Break a tree so that there's just leaves, stack sand and break the lower block, or bucket water
![image](https://user-images.githubusercontent.com/51932756/218188786-f6df1b7b-8e9d-44af-9919-7012342ce97a.png)

**Expected behavior**
Vanilla properties of blocks should be preserved, multiblock structures should be able to validate their positioning, wiring should naturally connect to itself when placed

**Screenshots**
https://streamable.com/3e9ah4

**Crash log or latest.log.log**
https://pastebin.com/BGpbjx3N

**Additional context**
The only region I've claimed with a gold hoe and unclaimed with /flan deleteAll has been the region boxed in gold.
All of the chunks boxed in red are the problematic regions, with exception of the two chunks with interior white boxing as those two function normally.

Here's also a list of things I've tested to work within or across these problematic chunk borders

Identified disfunctional behaviors:
    Vanilla water
    Vanilla leaf decay
    Vanilla sand gravity
    Tech reborn wiring
    Modern industrialization steam quarry multiblock
    Create steam engine multiblock
    Create shafts

Identified Functional behaviors:
    Vanilla nether portals
    Vanilla redstone
    Vanilla double chests
    AE2 ME fluix cables
    Industrial revolution cables
    
I've also noticed `/flan menu` has waterborder as a global permission to 'toggle water crossing claim borders', but the claim border extends further than the concrete line at the chunk border where the erratic water behavior was occurring, so I don't think this has an effect.

This also shouldn't have impacts on the chunks further north which have no claim on them but also manifest the unusual behavior.

**Comment by itsdinkd** [comment]
Issue lies with Xaeros. i imagine its fixed by now from their latest updates but either way it would need to be reported to them.
