### ISSUE TITLE
[BUG] @Sandwichables redstone desalinator creates salt from @Bewitchments

### ISSUE THREAD

**Issue by MEAkkaya** [itsdinkd/AQM2#165]
**Modpack Version**
1.4.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When the redstone desalinator from sandwichable mod is used, it creates bewitchment salt which is not compatible with sandwichable mod.

**Steps to reproduce the behavior:**
Put the redstone desalinator in a salty water and see the output

**Expected behavior**
Salt from sandwichable

**Screenshots**
![image](https://user-images.githubusercontent.com/62956746/219639444-b7b59110-238f-4f55-875d-612dc5773bb5.png)

**Possible quick fix:**
 adding a crafting recipe to convert other salt to sandwichable salt

**Comment by itsdinkd** [comment]
as expected. if bewitchment salt doesnt work with sandwichable then its a bug with sandwichable as its configured to do so. you can also find sandwichable salt in world gen
