### ISSUE TITLE
[BUG]AQM Journey Twigs Quest Broken

### ISSUE THREAD

**Issue by Nostice1** [itsdinkd/AQM2#166]
**Modpack Version**
1.4.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
In the questline "AQM Journey" The quests revolving around the twigs mod are broken. I've broken several of the right type of stones, AND twigs and the questbook isn't logging that I have or finishing that quest.

**Steps to reproduce the behavior:**
Just... Destroy stone? Destroy Twigs? And look at the quest relating to them. They won't have been checked off.

**Expected behavior**
For the quest to finish and for me to get the reward/check

**Comment by itsdinkd** [comment]
fixed in 1.4.2
