### ISSUE TITLE
Bewitchment Progression - Demon Horns

### ISSUE THREAD

**Issue by EntropyParadigm** [itsdinkd/AQM2#167]
Since hellhounds are still disabled for bewitchment, would it be possible to get a recipe to craft the demon horns to progress through bewitchment?
Maybe like a 2x2 shapeless recipe using: Grim Elixir, Fiery Serum, Blade Rod, Blaze Rod

The above recipe suggestion gates the demon horn behind the nether and could even swap out one blaze rod for one of the doom Argent Essence's to increase the difficulty.
Hellhound spawn randomly throughout the nether and there is no ritual for summoning them.

Discord Thread: https://discord.com/channels/417606822615187466/1070848407071096962

**Comment by itsdinkd** [comment]
added
