### ISSUE TITLE
[BUG] [Gobber2] End Pickaxe losing durability

### ISSUE THREAD

**Issue by Danilkat** [itsdinkd/AQM2#168]
**Modpack Version**
1.4.1 FABRIC

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When mining any stone-like blocks with end pickaxe from gobber, the durability decreases. 
But when i'm mining with End Hammer, the durability does not decrease (as it supposed to be)

**Steps to reproduce the behavior:**

1. Craft End Pickaxe
2. Mine any block
3. See that annoying green bar at End Pickaxe and decreased durability with advanced tooltips ON)

**Expected behavior**
End pickaxe should NOT break or decrease in durability

**Screenshots**
![Durability difference of End Pickaxe and Hammer](https://user-images.githubusercontent.com/41061608/221350566-4526ecaf-2fcc-435f-be99-fa92a23959b5.png)

**Comment by itsdinkd** [comment]
End tools are supposed to lose durability with the way its configured. If the hammer being unbreakable is a bug within gobber that I will not be able to fix and the dev would have to. Feel free to open a issue with gobber github if you'd like
