### ISSUE TITLE
[BUG] Invalid copper nugget from rusticated

### ISSUE THREAD

**Issue by Marpfie** [itsdinkd/AQM2#169]
**Modpack Version**
1.4.1

**Describe the crash or bug**
Conflict in copper nuggets.
There is an additional copper nugget from "Rusticated", which does not work for recipes like the other one does

**Expected behavior**
There should only be one kind of copper nugget

**Screenshots**
Output servo recipe:
![grafik](https://user-images.githubusercontent.com/24807827/222272036-3c3b24bd-8550-4d98-893e-41d9515ac399.png)

Supposed copper nugget recipe
![grafik](https://user-images.githubusercontent.com/24807827/222272051-736b8326-a1dd-4ad4-adda-cd76320c9ed8.png)

Actual result is a different copper nugget
![grafik](https://user-images.githubusercontent.com/24807827/222272066-a8644085-9082-4ad2-bfa6-bde0b8de7887.png)

That nugget not working in the recipe
![grafik](https://user-images.githubusercontent.com/24807827/222272085-c501fed2-959e-40d7-8e92-a5ed2cd682c0.png)

**Comment by itsdinkd** [comment]
Fixed in 1.4.2

next time you open a issue please name it. 
![image](https://user-images.githubusercontent.com/35115304/222809099-b57cb935-ff79-4b04-bb4f-6fe6136e7dc6.png)
