### ISSUE TITLE
Arcinite does not get fire proofing at level 50 like it should[BUG]

### ISSUE THREAD

**Issue by Ironchestplate** [itsdinkd/AQM2#17]
**Modpack Version**
What modpack version
1.2.2
**Minecraft Version**
What mc version
1.18
**Describe the crash or bug**

When gaining the new powers at level 50, fire proofing doesn't work but lightning proofing does work

**Steps to reproduce the behavior:**

How can someone replicate this bug/crash?

Reach lvl 50 as an archinite and jump in fire

**Expected behavior**
What is the expected outcome?
No dmg from fire ticks

**Comment by itsdinkd** [comment]
I took off Fire proof the day I added that origin. need to modify description.
