### ISSUE TITLE
[BUG] Botania Terra Blade, etc. still not integrated with better combat in 1.4.2

### ISSUE THREAD

**Issue by Hiccup251** [itsdinkd/AQM2#170]
**Modpack Version**
1.4.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
1.4.2 changelog said these weapons were now compatible with better combat, but they're still functioning entirely like vanilla swords.

**Steps to reproduce the behavior:**
Swing a terra blade or either of the other two weapons in game.

**Expected behavior**
Sword should swing like a better combat sword would, not like a vanilla sword.

**Comment by itsdinkd** [comment]
If it still doesn't work then it's a bug with botania/ better combat and will need to be reported to them
