### ISSUE TITLE
[BUG] Nano Armor doesn’t protect

### ISSUE THREAD

**Issue by JudoJake** [itsdinkd/AQM2#171]
**Modpack Version**
What modpack version
Both 1.4.2 and 1.4.1

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
Nano armor doesn’t negate damage like it’s supposed to when charged. It’s on par with leather armor and whenever it takes damage only the boots lose charge

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Wear charged Nano Armor and take damage

**Expected behavior**
What is the expected outcome?
I believe nano armor should negate all damage as long as it has a charge

**Screenshots**
Post screenshots if available
Not available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
No

**Comment by itsdinkd** [comment]
Nothing I can do to change how a mod functions. This will need to be reported to Modern Industrialization
