### ISSUE TITLE
Loot Crate in Lighthouse cause immediate server crash

### ISSUE THREAD

**Issue by SkyeMors** [itsdinkd/AQM2#172]
Within the Lighthouses, on the first floor, there's a spot for a Loot Crate from MyLoot to spawn. When ANY player interacts with it, the server instantly springs a memory leak and freezes, crashing once it realizes it's over a minute behind. And by Interact, that includes: opening, breaking, and updating any block sharing a face.

My only guess is that the loot pool for that specific container contains an invalid or glitched or broken item, or the loot pool itself is broken. No way to find out, as the server crashes before the inventory can open.

Tried to break it in Creative, crashed the server. Tried to place Bedrock around it (all six faces to prevent interaction), server crashes. Next step: just... bury the whole lighthouse in bedrock. xD

I have been informed that it is, in fact a barrel, not a crate.

**Comment by itsdinkd** [comment]
You need to open a bug issue as it contains a template to follow that provides me the info I need to review
