### ISSUE TITLE
There's a Loot Barrel that can crash a server (MyLoot)

### ISSUE THREAD

**Issue by SkyeMors** [itsdinkd/AQM2#173]
**Modpack Version**
1.4.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Opening a certain Loot Barrel (rather, spawning a certain Loot Pool) will freeze the server.

**Steps to reproduce the behavior:**
Find a Villager Lighthouse or Sunken Boat, and open the Loot Barrel from MyLoot. It'll likely crash the server. If it does it once, it'll do it for all players.

**Expected behavior**
Opening the barrel, and acquiring loot. Instead, the barrel never opens and the server freezes.

**Screenshots**
Screenshot just shows CPU usage doubling upon interaction.
![image](https://user-images.githubusercontent.com/39830646/223540424-c9da1725-50f2-484c-b333-0ac237dda533.png)

**Crash log or latest.log.log**
Tried using PasteBin, said it contained offensive words, blablabla
https://mcpaste.io/6b763aae530fb9af

**Additional context**
Presumably the loot pool is the same for all players, and probably the same in same locations in different worlds. This bug has been encountered in the Villager Lighthouse, and a Sunken Ship so far. "Interaction" expands so far as: opening the Loot Barrel, placing or deleting blocks sharing a face with the Loot Barrel, breaking the Loot Barrel, replacing the Loot Barrel with Air or Bedrock via command.
It appears that ANYTHING that refers to the barrel's Loot Pool or ID besides it just vibing, will crash the server.
Server is hosted on PebbleHost, but that's probably not relevant.

**Comment by rurigk** [comment]
I'm having this problem on a dedicated machine

I can provide a world containing a bugged barrel

**Comment by itsdinkd** [comment]
My suggestion is edit the myloot config and remove minecraft:barrel from it.
