### ISSUE TITLE
[BUG] Open Map on Mythic Mount CRASHES

### ISSUE THREAD

**Issue by JudoJake** [itsdinkd/AQM2#174]
**Modpack Version**
What modpack version
1.4.2

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
Whenever you open your map on a Mythical Mount (so far I only know that this happens on the Żar-ptak) and zoom out some it seems to crash the game almost immediately. It says "saving world" and then crashes out to the MC Launcher.
**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Open your full size map while riding a Żar-ptak in the air

**Expected behavior**
What is the expected outcome?
Be able to open the full screen mount while riding a Żar-ptak without crashing

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log
https://pastebin.com/Daq1j5ax
https://pastebin.com/uf4K6gsH

**Additional context**
Any additional context?
Not sure if this happens with other mythic mounts/mounts in general, but it would be worth looking into

**Comment by itsdinkd** [comment]
1.4.4 AQM2 updates xaeros. it could possibly fix this. ill close for now, if it crashes on new version let me know, and would also require reporting to the Xaeros Dev
