### ISSUE TITLE
[BUG] Storm Stones not breaking when hit.

### ISSUE THREAD

**Issue by darkspyro92** [itsdinkd/AQM2#176]
**Modpack Version**
What modpack version
1.4.2

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
When striking the embedded Storm Stones from Spectrum, they aren't being broken free preventing progress.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Hit Storm Stones with everything you've got.

**Expected behavior**
What is the expected outcome?
Storm Stones should break free and be collected.

**Screenshots**
Post screenshots if available
I have a screenshot but am not home at the time of writing this 

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
According to others on other servers, I'm the only one with this issue. I'm going to try to speed another player through the mod so they can attempt to break them as well as a work around.

**Comment by itsdinkd** [comment]
Would need to be reported to spectrum developer
