### ISSUE TITLE
[BUG] Archon and Meriam's Souls Like Weapons bosses not dropping boss items 

### ISSUE THREAD

**Issue by darkspyro92** [itsdinkd/AQM2#177]
**Modpack Version**
1.4.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
I've killed Ayla from Archon three times and she's supposed to drop Angelic Essence so that you can craft the Heaven's Dial. None of the times has she dropped anything.

I've also summoned and killed the Monarch of Chaos from Meriam's Souls Like Weapons twice and killed it, but it's only dropped normal loot instead of loot from the Mod. The Monarch has three unique drops, and then Verglass which has been relegated to boss drops. Verglass I can see as being a loot table thing, but the Crown of Chaos, Cape of Chaos, and Withered Wabbajack should drop with each kill as they're boss-specific items.

So far I've had no issue with the drops from Bosses of Mass Destruction thankfully, but these two mods seem like they might have issues. I'm going to attempt to kill some of the other bosses in the mods to see if the issue persists on other bosses or if it's just these two.

**Steps to reproduce the behavior:**
Summon and kill Archon and MSLW bosses.

**Expected behavior**
Boss-specific loot should drop each time.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
I've only killed these two bosses so far and will report back after killing other bosses from the mods.

**Comment by darkspyro92** [comment]
Just killed an Arch Maykr and she didn't drop her unique item, either. So it extends past even those two mods. It must be only items that drop from the specific bosses. For some reason the BOMD bosses are dropping their stuff, though.

Edit: Arch Maykr doesn't have a unique item. My bad.

**Comment by darkspyro92** [comment]
Killed the Monarch again and the quest to kill him didn't complete.

**Comment by itsdinkd** [comment]
I'll look into it. Could be due to my loot modification

**Comment by itsdinkd** [comment]
a new version of aqm2 has loot dropping of the bosses
![image](https://user-images.githubusercontent.com/35115304/227395589-f7c9c366-5ddf-4645-a134-bdc658558415.png)

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/227395760-0463c69a-9308-40ae-9ea0-6a699502bfb6.png)
