### ISSUE TITLE
[BUG] Sniper Sword projectile sometimes crashes server.

### ISSUE THREAD

**Issue by darkspyro92** [itsdinkd/AQM2#179]
**Modpack Version**
1.14.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When striking an NPC with the projectile of the Sniper Sword, the server sometimes crashes. More often than not, it's only from passive NPCs, but it has happened with bosses as well.

**Steps to reproduce the behavior:**
Strike an NPC from a distance with the Sniper Sword.

**Expected behavior**
Damage with no crash.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
I'll have to get with my server owner for that, but they aren't on often.

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Would need to be reported to Gobber developer along with logs
