### ISSUE TITLE
[BUG] Ring of return (Gobber) not returning back to spawn

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#18]
**Modpack Version**
1.4.2
**Minecraft Version**
1.18.1
**Describe the bug**
Ring of return does no take you back to spawn when shift + right clicking

**To Reproduce**
1. get a Ring of return
2. shift + right click to go back to spawn
3. nothing happens

**Expected behavior**
Ring should take you back to spawn

**Crash log or latest.log.log**
Nothing to see here

**Comment by red2blue** [comment]
It takes you to your spawn. You must set a spawn point aka use a bed.

**Comment by Squoshy-Boop** [comment]
> It takes you to your spawn. You must set a spawn point aka use a bed.

I mean WORLD spawn, the shift + eight click function

**Comment by itsdinkd** [comment]
does this still exist in 2.0.1?

**Comment by Sebas-Re** [comment]
Yes

**Comment by Sebas-Re** [comment]
Item description changed, so my guess is that the Dev modified the item's functions
