### ISSUE TITLE
[Feature/Suggestion] Improve Double Jump + Gliding Interaction

### ISSUE THREAD

**Issue by rkwapisz** [itsdinkd/AQM2#180]
**Is your feature request/suggestion related to a problem? Please describe.**
Any sort of elytra glide ability, whether from wings or armor sets like Gobber, break the ability to double-jump using the enchant. Instead, hitting the jump button in the air prioritizes the glide ability rather than activating additional jumps up to whatever maximum is provided by the enchant.

I would instead like one of several options:
- Separate keys for jumping vs. gliding, which would allow me to use the jump keybind to double-jump and then a different key to activate gliding whenever I want. I think this is probably the most practical solution for all users.

- Allow gliding only after hitting jump once all double-jump charges have been expended (i.e., you double-jump until you can no longer do so, then the next jump makes you glide). However this would prevent a user from gliding intentionally before all jumps are expended, which may not be desirable for all players.

- Allow players to disable gliding temporarily via some sort of menu setting, or via toggles directly integrated into elytra (incl. Winged Mod) and Gobber armor sets.

I think double jump is a fantastic enchant that adds a lot of value to the overall player experience, but right now it requires me using weaker armor (since endgame Gobber armor has glide built-in) or not using elytra, which I love using simply for the aesthetic aspect. I also enjoy gliding, but wish both abilities cooperated with each other.

**Comment by itsdinkd** [comment]
This all sounds like a bug and incompatibility with the double jump mod. Nothing I can do on my end for any of this as it's all related to specific mod functions. Best bet would be to report to the developer of Double Jump mod

Thank for the detailed post though.
