### ISSUE TITLE
[BUG] Crashes when creating new world

### ISSUE THREAD

**Issue by Brok3nMango** [itsdinkd/AQM2#181]
What modpack version
AQM2 1.19.2 1.4.2

What mc version
1.19.2

fully crashed when create new world is clicked, goes "" then "Saving world"

How can someone replicate this bug/crash?
idk, might just be a me thing

What is the expected outcome?
not to crash?

Screenshots
https://user-images.githubusercontent.com/128040375/225587458-d9f15259-06bd-4eff-8110-b87470501484.png
https://user-images.githubusercontent.com/128040375/225587608-24e986f1-2726-4d83-b7a3-42f38493727e.png
https://user-images.githubusercontent.com/128040375/225587739-a80acac6-3ca6-4682-bb4c-fbf1bae5bdf2.png

Any additional context?

**Comment by itsdinkd** [comment]
in the template when you opened this issue, it asked for "Logs". you deleted it. Screenshots do not help. once you provide logs ill re-open
