### ISSUE TITLE
Windows Defender reports a trojan in the server files

### ISSUE THREAD

**Issue by Divinewerezwolf** [itsdinkd/AQM2#182]
server_aqm2-1.19.2_1.4.2.zip

Trojan:Script/Wacatac.B!ml

![image](https://user-images.githubusercontent.com/93427972/226094906-376e489a-bad5-442f-b86f-4bbbe89abf2f.png)

**Comment by itsdinkd** [comment]
False report. Curseforge wouldn't allow viruses to be uploaded. Use virustotal.com for a scan of 50+ anti virus analysis on it if you'd like.
