### ISSUE TITLE
[BUG] Hamburger requires specific ingredients rather than ore dictionary ingredients.

### ISSUE THREAD

**Issue by ToastedEggplant** [itsdinkd/AQM2#183]
**Modpack Version**
1.4.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
The hamburger from Farmer's Delight requires tomato, onion, and lettuce from specifically Farmer's delight.

**Steps to reproduce the behavior:**
Try to craft a hamburger from Farmer's Delight using onion, tomato, or lettuce from another mod.

**Expected behavior**
The hamburger should be craftable with any tomato, onion, or lettuce. The recipe should specify the ore dictionary entry for these ingredients and not the specific items from Farmer's Delight. There is likely many other food recipes experiencing this issue. 

**Additional context**
Hamburger.

**Comment by itsdinkd** [comment]
A lot of farmers delight recipes are based off items and not tags. This isn't a huge problem and would require a lot of work to unify each individual recipe. As long as its craftable, its fine. Closing as I will not fix (unless something is not craftable)
