### ISSUE TITLE
[BUG] Crafting Lightest Lamps Alchemical Dust crashes the game

### ISSUE THREAD

**Issue by tali9** [itsdinkd/AQM2#184]
**Modpack Version**
What modpack version
1.4.2

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
Crafting Alchemical Dust from the Lightest Lamps mod causes the game to crash.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Try crafting Alchemial dust in survival. I'm not sure if obtaining it via cheats grants the same result.

**Expected behavior**
What is the expected outcome?
The game closes.

**Screenshots**
Post screenshots if available
I have none.

**Crash log or latest.log.log**
use pastebin.com for your log
https://pastebin.com/zBcPkpgf

**Additional context**
Any additional context?
When rejoining after the crash, the Alchemical Dust is gone and you're not stuck in a crash-loop.

**Comment by tali9** [comment]
Note: If you don't shift-click the crafting container, when you rejoin you'll recieve the item and the item itself does not cause a crash. Most likely an issue with the crafting process itself.

**Comment by itsdinkd** [comment]
This will need to be reported to the developer of mod. Nothing I can do on my end. Feel free to link this issue on their github
