### ISSUE TITLE
[BUG] Origins issue - Carnivore - Multiple items improperly marked inedible

### ISSUE THREAD

**Issue by Sporque** [itsdinkd/AQM2#185]
Modpack Version
1.4.2

Minecraft Version
1.19.2

Describe the crash or bug
When using an Origin with the diet restricted to being a Carnivore, there are multiple food items that are clearly meat that are being flagged as inedible. This includes multiple variant versions of meat items, especially from Sandwichable, and the GoFish Mod.

Choose an origin with the Carnivore dietary restriction (I'm using Dragonkin)
Take a vanilla minecraft salmon, and use a sandwichable cutting board and knife to turn it into sliced salmon. It becomes inedible.
Many of the raw fish in the end from the GoFish Mod also show as inedible.

Expected behavior
Any item that is clearly raw meat or cooked meat should be edible by a Carnivore.

Additional Note: I know this is likely an issue with items from Mods not being included in specific groups, or those groups not being added to the list of accepted groups for Carnivores. If you want to point me in the direction of where those are stored, I am more than happy to dig through and compile what I can find that needs to be changed / updated.

**Comment by itsdinkd** [comment]
there is a discord post in relation to all foods for compiling

https://discord.com/channels/417606822615187466/1070560568261476384 

I do not have the time to go through all the foods unfortunately but if someone can give me a list with proper categories I have no problem adding. or creating a PR here in github for t.
