### ISSUE TITLE
[BUG] Stainless Steel Drill output do not show up in rei and produces Modern industrialization Titanium

### ISSUE THREAD

**Issue by ZaRb0G** [itsdinkd/AQM2#187]
**Modpack Version**
1.4.2
**Minecraft Version**
1.19.2

**Describe the crash or bug**
Stainlees steel drill output do not show up in rei and produces Modern industrialization titanium ore that you cant melt to Tech reborn titanium 

**Steps to reproduce the behavior:**
use Stainless steel drill in Electric quarry 

**Expected behavior**
should show up in rei and Titanium should be melted to Tech reborn Titanium

**Screenshots**
none

**Crash log or latest.log.log**
none

**Additional context**
none

**Comment by itsdinkd** [comment]
Thats because tech reborns titanium is not obtained through ores naturally. you will need to get tech reborn titanium the way it was made by the mod itself. you can use MI titanium for MI.
