### ISSUE TITLE
[BUG] Some Rusticated brews are not functioning properly

### ISSUE THREAD

**Issue by flakaby** [itsdinkd/AQM2#188]
**Modpack Version**
What modpack version
1.4.2

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
Rusticated's elixirs are upgraded using an extra component. Often, it's horsetail flowers. This works for the speed elixir and produces speed 2. However, it doesn't do this with regeneration or iron skin. They all take the same bonus ingredient of horsetail flowers to do this, but it only works with speed. I've tried every other ingredient in hopes that the book was incorrect, but nothing worked.

**Steps to reproduce the behavior:**
Use an Advanced Alchemical Condenser and put the proper ingredients in to make each brew. The process is detailed in the Rusticated manual. Base brews require only two ingredients, so a third will either do nothing and get consumed (use dirt in the third slot as an example) or will upgrade the brew (check the book for the recipes). You'll notice that the horsetail flowers in the third slot are consumed, but the potion is still a base potion as though it wasn't there in the first place.

**Expected behavior**
It should be producing potions of regeneration 2 or iron skin 2, but instead it's producing regen 1 or iron skin 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/128662227/227089142-caa93809-7ff3-48d3-8a38-7bcd3089d5f6.png)

**Crash log or latest.log.log**
use pastebin.com for your log
There isn't a crash happening - would a log be helpful here?

**Additional context**
Any additional context?
Nope

**Comment by itsdinkd** [comment]
Reading the datapack from the mod this is the recipe for strong regeneration

```
{
  "type": "rusticated:adv_condenser",
  "ingredient": [
    {
      "item": "rusticated:blood_orchid"
    },
    {
      "item": "minecraft:honeycomb"
    },
    {
      "item": "rusticated:horsetail"
    }
  ],
  "potion": "minecraft:strong_regeneration",
  "result": {
    "item": "rusticated:elixir"
  }
}
```



Iron skin 2

```
{
  "type": "rusticated:adv_condenser",
  "ingredient": [
    {
      "item": "rusticated:cohosh"
    },
    {
      "item": "rusticated:iron_berries"
    },
    {
      "item": "rusticated:horsetail"
    }
  ],
  "potion": "rusticated:strong_ironskin",
  "result": {
    "item": "rusticated:elixir"
  }
}
```

**Comment by flakaby** [comment]
Yes, and it's not working. That recipe is used in the screenshot, and it's not producing the correct potion.

**Comment by flakaby** [comment]
I didn't mean to close the issue D:

**Comment by flakaby** [comment]
Forgive me; this is my first time using Github.

**Comment by itsdinkd** [comment]
> Yes, and it's not working. That recipe is used in the screenshot, and it's not producing the correct potion.

I see. in the case I believe its going to need to be reported to the developer of Rusticated. i am not making any direct edits of it so its possible the mod is conflicting with KubeJS itself or something is wrong with the crafting type from rusticated

**Comment by flakaby** [comment]
Okay! Thanks for responding!
