### ISSUE TITLE
[BUG] Many Issues regarding wasted resources and progression issues

### ISSUE THREAD

**Issue by Ironchestplate** [itsdinkd/AQM2#19]
**Modpack Version**
What modpack version
1.2.2
**Minecraft Version**
What mc version
1.18
**Describe the crash or bug**
Medalion of Experience from Gobber2 does not work while in offhand
and
End Stone Furnace does not work at all, halting progression.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

Use the Medalion and open any End Stone Furnace

**Expected behavior**

What is the expected outcome?

Way more XP drops to combat the outrageous Dark Enchanter costs
and
UI not being broken, allowing ores to be smelted properly

**Comment by itsdinkd** [comment]
You would need to report this to the individual developers. I cant fix a item that does not work, that is dependent on actual code in the mod, not my modpack.

I don't see how end furnace breaks progression, use a different furnace?

**Comment by itsdinkd** [comment]
For end smelter

Any items with 2000+ burn ticks - coal/charcoal blocks, lava, blaze rods, mod fuel.
