### ISSUE TITLE
[BUG] incompatible client even tho im on 1.19.2

### ISSUE THREAD

**Issue by ICEBoltG** [itsdinkd/AQM2#190]
**Modpack Version**
What modpack version
1.4.3

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
incompatible client

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
just joining

**Expected behavior**
What is the expected outcome?
cant play

**Screenshots**
![image](https://user-images.githubusercontent.com/128986893/227785393-626985cc-b5b7-43c3-93d3-e01b107ff21a.png)
**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Use discord for support. This is not a bug but a user error.
