### ISSUE TITLE
[BUG]Expert accessor recipe produces skilled accessor instead

### ISSUE THREAD

**Issue by ZaRb0G** [itsdinkd/AQM2#191]
**Modpack Version**
1.4.3

**Minecraft Version**
19.2

**Describe the crash or bug**
Expert accessor recipe produces skilled accessor instead 

**Steps to reproduce the behavior:**
.

**Expected behavior**
should output Expert accessor 

**Screenshots**
![SharedScreenshot](https://user-images.githubusercontent.com/128565586/227794395-46adb4a5-5579-4feb-b16e-38288f7c5c73.jpg)

**Crash log or latest.log.log**
.

**Additional context**
.

**Comment by itsdinkd** [comment]
Fixed
