### ISSUE TITLE
[BUG] Crash on Modpack startup

### ISSUE THREAD

**Issue by ddroche** [itsdinkd/AQM2#195]
**Modpack Version**
What modpack version
v1.4.4
**Minecraft Version**
What mc version
v1.19.2
**Describe the crash or bug**
MC launcher crashes a couple seconds after attempting to launch modpack, prior to client initializing.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
1. Download v1.4.4 of modpack from curseforge. 
2. Press play in curseforge
3. Ensure modpack is selected in MC Launcher
4. Press play in MC Launcher
5. Observe crash

**Expected behavior**
What is the expected outcome?
Modpack launches correctly.

**Screenshots**
Post screenshots if available
NOTE: See additional context section for context regarding these screenshots.
![image](https://user-images.githubusercontent.com/3280105/229176377-e217a777-b384-4d09-acfe-58a677a304c7.png)
![image](https://user-images.githubusercontent.com/3280105/229176436-b2eca07a-5b3f-435f-b27b-461f2aa7fce3.png)

**Crash log or latest.log.log**
use pastebin.com for your log
https://pastebin.com/ag0DqADe

**Additional context**
Any additional context?
I tried launching the modpack about 6 times with the same crash result, which is when I decided to submit this issue. Upon the 7th attempt to launch (so I could grab a screenshot), the modpack launched to the client's loading screen.  Once it was 98% loaded it froze the client. After approximately 60 seconds the client unfroze and displayed a message about incompatible drippy layouts (see screenshot).  The game then finished loading and I was able to update settings (usually the first thing I do in a new modpack) and create a new world. If any additional crashes occur I'll update this issue.

**Comment by itsdinkd** [comment]
Issues are not used for support. It's for reporting bugs, this is not a bug. Use discord for this
