### ISSUE TITLE
[Feature/Suggestion] Server Perfomance

### ISSUE THREAD

**Issue by Tomboru** [itsdinkd/AQM2#197]
**Is your feature request/suggestion related to a problem? Please describe.**
So I noticed, when playing with multiple people on one server, and some players start to render
new chunks. The server is getting some lag spikes.

**Describe the suggestion you'd like**
My suggestion would be to add the mod:
[Server Performance - Smooth Chunk Save](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save) from [someaddon](https://www.curseforge.com/members/someaddon) since it reduces a lot of lags from chunk saving. 
Also it would be good if there was an mod for preloading chunks.
Something like:
[Chunky (Fabric)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator) from [pop4959](https://www.curseforge.com/members/pop4959)
[And Let Me Despawn](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn) from [frikinjay1](https://www.curseforge.com/members/frikinjay1) would be a great addition for improving performance

**If this is a request to add a mod, what is the curseforge link?**
[Server Performance - Smooth Chunk Save](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save) from [someaddon](https://www.curseforge.com/members/someaddon)
[Chunky (Fabric)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator) from [pop4959](https://www.curseforge.com/members/pop4959)
[And Let Me Despawn](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn) from [frikinjay1](https://www.curseforge.com/members/frikinjay1)

**Why do you think this would benefit the modpack?**

These 3 mods have been proven to gain performance for servers.
Especially when multiple players are online.
Smooth Chunk Save is known for gaining performance and Chunky doesn't remove anything for any player.
It just adds the abbility to preload a world.

**Comment by itsdinkd** [comment]
Server operators are more than welcome to add any server mod they desire, as well as clients.

LMD will break eldritch mobs that are supposed to persist 
Chunky is subjective
Smooth chunk will create roll backs if crashes occur more frequently than the standard 5 minute save.
