### ISSUE TITLE
[Feature/Suggestion] Starlight instead of Phosphor

### ISSUE THREAD

**Issue by Tomboru** [itsdinkd/AQM2#198]
**Is your feature request/suggestion related to a problem? Please describe.**
The lack of some perfomance in the client and server

**Describe the suggestion you'd like**
I think [Starlight](https://www.curseforge.com/minecraft/mc-mods/starlight) from [Spottedstar](https://www.curseforge.com/members/spottedstar) will improve the perfomance by mutch more then Phosphor.

**If this is a request to add a mod, what is the curseforge link?**
[Starlight](https://www.curseforge.com/minecraft/mc-mods/starlight) from [Spottedstar](https://www.curseforge.com/members/spottedstar) 

**Why do you think this would benefit the modpack?**
Better performance is always better as long as there is no noticable change for the player that is playing.

**Comment by itsdinkd** [comment]
We've used both individually before, and the performance changes are minimal and not noticeable. Starlight doesnt play well with certain mods and breaks their function of certain blocks ie; kibe big torch
