### ISSUE TITLE
not starting crash. at the first start

### ISSUE THREAD

**Issue by xxl2005** [itsdinkd/AQM2#199]
**Modpack Version**
AQM2-1.19.2-1.4.4hf

**Minecraft Version**
1.19.2

**what kind of operating system do you have?**
Manjaro Linux

**Crash log or latest.log.log**
[https://pastebin.com/8QwjsgZf](https://pastebin.com/8QwjsgZf)

not starting crash. at the first start by new installation

**Comment by itsdinkd** [comment]
Try a different launcher, you have an issue with libglfw
