### ISSUE TITLE
Inconsistencies within the modpack

### ISSUE THREAD

**Issue by WindexBleach** [itsdinkd/AQM2#2]
So I'm just going to list some of the issues I've found
-Dragonkin (Origins) can not eat the majority of meat based foods from the other mods, most notably fish.
-Argent Pickaxe/Paxel aren't able to mine several pickaxe related blocks such as anvils or lignite coal
-Argent Axe doesn't count as an axe so the *tree feller* thing where it replaces the log with one from the top of the tree doesn't work
-Argent Sword doesn't get sword modifiers it gets armor modifiers
-Slab Furnaces/Blast Furnaces/Smokers are unable to cook non-vanilla recipes
I believe that's all I've found at the moment I may submit another if I find more issues
I'm not sure if you are able to fix all these, I just figured I would bring it to your attention
Thank you for your time

(side note: for the argent paxel, most mods with paxels triple the durability since you are using 3x the materials, but I get it if that's not something that should be changed)

**Comment by itsdinkd** [comment]
Please use the issue template provided for bug reports. It's there so I can get the information I need to fix what can be fixed. 

I can tell you now though there isn't much I can do about the Argent tools. That is hard coded and would need to be reported to McDOOM
