### ISSUE TITLE
Tom's Simple Storage Mod not reading upgraded Compact Storage chest size[BUG]

### ISSUE THREAD

**Issue by Draktastic** [itsdinkd/AQM2#200]
**Modpack Version**
1.4.4hf

**Minecraft Version**
1.19.2

**Describe the crash or bug**
The inventory connector from Tom's Simple Storage Mod is only recognizing the first 54 slots of inventory space in an upgraded Compact Storage chest.

**Steps to reproduce the behavior:**
Place down a TSSM inventory connector block.
Place a CS chest and apply any number of upgrades.
Inventory connector correctly displays the number of visible slots accessible when right-clicked.
Unload the chunk or pick up the chest with Carry On then place it back down.
Inventory connector displays only 54 slots available.

**Expected behavior**
The connector is expected to read all available inventory slots at all times, rather than only when chests are newly placed as a block and not unloaded.

**Screenshots**
![2023-04-07_16 51 09](https://user-images.githubusercontent.com/130191113/230694336-2463f0c5-b743-4087-9b74-be20d8a31abd.png)
![2023-04-07_16 51 21](https://user-images.githubusercontent.com/130191113/230694361-178cf932-cb9b-4269-aa35-09bbf9b65ee5.png)
![2023-04-07_16 51 24](https://user-images.githubusercontent.com/130191113/230694366-879849f1-603a-47ed-b682-3859b41eeecd.png)

After unloading/reloading the chunk (same chest, unmoved and the item stored in the same slot):
![2023-04-07_16 50 59](https://user-images.githubusercontent.com/130191113/230694378-15c75977-51a0-4873-9761-3b9360b2de1d.png)

**Latest.log.log**
https://pastebin.com/pC5nivZE

**Additional context**
Items visible on any TSSM terminal when the issue occurs follow the same behavior--anything in slots 55 or higher don't appear on the terminal until moved into slots 1-54. Slots in upgraded Expanded Storage chests are always read properly and don't produce this behavior, whether unloaded/reloaded or picked up and placed with Carry On.

**Comment by itsdinkd** [comment]
This will need to be reported to the developer of compact storage. nothing I can do on my end, unfortunately.
