### ISSUE TITLE
[BUG] Origin Dragonkin immunity to magic won't work

### ISSUE THREAD

**Issue by FriskTemmie** [itsdinkd/AQM2#201]
**Modpack Version**
1.4.4hf

**Minecraft Version**
1.19

**Describe the crash or bug**

**Steps to reproduce the behavior:**
Be a dragonkin and press primary origin button and step on your magic breath

**Expected behavior**
Immunity to magic breath

**Additional context**
Dragonkin should be immune to magic, but they aren't. Also, their slowness apply to air and water, when they should only apply to ground/walking

**Comment by itsdinkd** [comment]
It is disabled.
