### ISSUE TITLE
[BUG]Steel drill not working+fix

### ISSUE THREAD

**Issue by ZaRb0G** [itsdinkd/AQM2#202]
**Modpack Version**
1.4.4hf

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Nickel and salt ore cause problems so that the drill doesn't work

**Steps to reproduce the behavior:**
using steel drill in electric quarry

**Expected behavior**
Nickel and salt ore needs to be removed for steel drill to work 

**Screenshots**
![SharedScreenshot](https://user-images.githubusercontent.com/128565586/230805464-461c7e6b-9f7b-4929-aacc-6cd14a6a29d0.jpg)

**Crash log or latest.log.log**
-

**Additional context**
-

**Comment by itsdinkd** [comment]
fixed in 1.5
