### ISSUE TITLE
[BUG] Suspected bug with eldritch mobs/bosses sometimes not dropping loot

### ISSUE THREAD

**Issue by RestingMonolith** [itsdinkd/AQM2#203]
**Modpack Version**
What modpack version
AQM2 v1.4.4hf
**Minecraft Version**
What mc version
1.19.2
**Describe the crash or bug**
Suspected bug with eldritch mobs sometimes not dropping loot. The main problem with this is that the buffed bosses sometimes don't drop anything at all (not even experience). I suspect that it's the eldritch mobs mod because I have observed other eldritch mobs not dropping their loot either, and this occurrence has been observed happening to multiple people and with different bosses.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
It just seems to happen when killing an eldritch mob/boss. Not sure if there's anything else.

**Expected behavior**
What is the expected outcome?
Mob dies, there's a decent chance that nothing at all will drop.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/231251933-2954ad1c-a572-4eb5-b3e2-fd1a28c3a8b0.png)
![image](https://user-images.githubusercontent.com/35115304/231251944-2790455f-220f-488f-96a4-af975df95a1a.png)
![image](https://user-images.githubusercontent.com/35115304/231251954-0c35bbec-a1ff-489e-9139-075b94fd8ee9.png)

**Comment by RestingMonolith** [comment]
This is something that happened *some* of the time, not every time. It's happened to multiple players on the AQM2 Zion server.

**Comment by itsdinkd** [comment]
without being able to reproduce, i cannot fix. lets just hope it works for you in 1.5
