### ISSUE TITLE
[crash] clicked on alium recipe and crashed to desktop [AQM2]

### ISSUE THREAD

**Issue by Xplodin** [itsdinkd/AQM2#204]
[crash-2023-04-12_01.34.46-client.txt](https://github.com/itsdinkd/AQM2/files/11207586/crash-2023-04-12_01.34.46-client.txt)

on official server.
also the bug report template leads to a 404 page just a heads up. :)

crash seems related to indium, also using shaders and vanilla pbr

it seems its not 100% of the time, so its an odd occasion thats happened twice.

**Comment by itsdinkd** [comment]
Please use the provided bug template when reporting bugs https://github.com/itsdinkd/AQM2/issues/new?assignees=itsdinkd&labels=bug&template=bug_report.md&title=%5BBUG%5D

**Comment by Xplodin** [comment]
![image](https://user-images.githubusercontent.com/13007677/231831038-b3c0de99-ec17-44dc-a358-785629b362ef.png)
I get this when using the template to report bugs
