### ISSUE TITLE
[BUG] getting sent to limbo possibly sending people outside worldborder on server

### ISSUE THREAD

**Issue by Kettledoesstuff** [itsdinkd/AQM2#205]
**Modpack Version**
What modpack version
1.5

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
playing on the Zion server. upon entering a dimensional door, i almost immediately died from suffocation. because i died in the pocket dimension i was sent to limbo, where i also immediately suffocated to death. server suffered severe tps lag during this time due to the dimensions being loaded.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
entering a pocket dimension or limbo.

**Expected behavior**
What is the expected outcome?
depends on the worldborder size. you can end up being placed outside the border.

**Screenshots**
Post screenshots if available
my deaths on Zion
[https://cdn.discordapp.com/attachments/790699597902774352/1095963740815499304/image.png](url)

Zion latest death coordinates
[https://cdn.discordapp.com/attachments/790699597902774352/1095963608325836800/image.png](url)

tested pocket dimension in singleplayer, this view is outside the border
[https://cdn.discordapp.com/attachments/1082965251647082548/1095965766475587625/image.png](url)

this is the worldborder from the overworld
[https://cdn.discordapp.com/attachments/790699597902774352/1095968051612090438/image.png](url)

coordinates inside singleplayer pocket dimension
[https://cdn.discordapp.com/attachments/790699597902774352/1095966354152099860/image.png](url)

did /kill in singleplayer pocket dimension, these are my limbo coordinates
[https://cdn.discordapp.com/attachments/790699597902774352/1095966625313853570/image.png](url)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
known issue, developer wont fix.

**Comment by itsdinkd** [comment]
Only thing you can do to prevent dying is turning off worldborder damage via /worldborder command
