### ISSUE TITLE
[BUG] Runic altar recipe for Mjölnir doesn't work

### ISSUE THREAD

**Issue by ZaRb0G** [itsdinkd/AQM2#206]
**Modpack Version**
1.5

**Minecraft Version**
1.19.2

**Describe the crash or bug**
runic altar recipe for Mjölnir doesn't work 

**Steps to reproduce the behavior:**
Try to craft Mjölnir

**Expected behavior**
should craft Mjölnir

**Screenshots**
-

**Crash log or latest.log.log**
-

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Fixed
