### ISSUE TITLE
[BUG]Lava Barista spawning unlimited times

### ISSUE THREAD

**Issue by ZaRb0G** [itsdinkd/AQM2#209]
**Modpack Version**
1.5

**Minecraft Version**
1.19.2
**Describe the crash or bug**
Lava barista walking out of the barista house and falling into lava they dont die and respawn at the barista house and repeat it, there were 1500 near zion nether spawn under the lava

**Steps to reproduce the behavior:**
^
**Expected behavior**
the shouln't respawn

**Screenshots**
-

**Crash log or latest.log.log**
-

**Additional context**
-

**Comment by itsdinkd** [comment]
Bug for the developer of the mod to fix, i cant as i did not develop the mod
