### ISSUE TITLE
[BUG] Arm Extender trinket not working with weapon combat mod

### ISSUE THREAD

**Issue by vibe-checker** [itsdinkd/AQM2#211]
**Modpack Version**
1.15

**Minecraft Version**
1.19.2

**Describe the crash or bug**
The arm extender trinket, which should add 2 attack range / reach, doesn't work with certain weapon types. I've tested it to not work on the greatsword, sword and dagger type weapons. It works fine with my bare fist.

**Steps to reproduce the behavior:**
Equip the arm extender trinket and observe the blocks at which your weapon can come into contact with the enemy. I used a skeleton and a target dummy from MmmMmmMmmMmm.

**Expected behavior**
The arm extender should increase my reach 2 blocks further when using the tested weapons.

**Screenshots**
![image](https://user-images.githubusercontent.com/97097474/232199424-a9cf0797-6b99-4f1a-8853-b03854ccbe58.png)
Arm extender equipped (+2 attack range) with lich bane (2.5 attack range) unable to hit an enemy from 3 blocks away.

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
I tried adding a fix via better combat config, if it still doesnt work in the last 4 Modpack versions then it would need a direct fix via dev. closing
