### ISSUE TITLE
[BUG] Broken Wireless crafting terminal GUI

### ISSUE THREAD

**Issue by XenonDB** [itsdinkd/AQM2#212]
**Modpack Version**
1.4.4hf

**Minecraft Version**
1.19.2 fabric 

**Describe the crash or bug**
The wireless crafting terminal GUI broken, as shown below
![2023-04-16_05 50 31](https://user-images.githubusercontent.com/58476103/232254895-35a2c8cf-8264-44ee-a99a-509f2f496be6.png)

**Additional context**
The wireless crafting terminal has been modified by AE2WTLib originly since it add extra function for terminal and improve display.
However, the GUI tweaker by this pack seems following old version of AE2WTLib, as shown below:
![image](https://user-images.githubusercontent.com/58476103/232255081-e0664843-f82c-447c-8264-bb620501a0fa.png)
The up side are tweaked GUI assets while the down side are the origins.

replacing the extras.png with the origin one can temporarily fix this issue.

Also, this may be the cause of this issue: https://github.com/itsdinkd/AQM2/issues/154

**Comment by itsdinkd** [comment]
fixed in 1.5.4
