### ISSUE TITLE
[BUG] Russian language has broken search

### ISSUE THREAD

**Issue by lnd212** [itsdinkd/AQM2#213]
**Modpack Version**
Found this bug on AQM2 1.5 and AQM2 1.5.1. Haven't checked previous versions.

**Minecraft Version**
fabric-loader-0.14.18-1.19.2

**Describe the crash or bug**
Using russian language makes item search not working. Found bug in REI search and in default minecraft search.  Maybe AE2 search is also affected.

**Steps to reproduce the behavior:**
Set russian language in game settings and try to search items in REI

**Expected behavior**
Working search

**Screenshot**
As an example, I am trying to search for torch(Факел). Getting empty result in minecraft search and showing all items in REI. Latest modpack version.
![изображение](https://user-images.githubusercontent.com/17836854/232840028-57922d4a-36e3-4b9f-9e28-e540a6de4acf.png)

**REI log**
https://pastebin.com/Wd3CwhWe

**Comment by itsdinkd** [comment]
I am not the developer of either mod. You will need to ask the developers of ae2 and rei for Russian translations

**Comment by lnd212** [comment]
It is not a translation problem. Clean fabric with REI doesn't have this weird search bug. Found that it is caused by Create Crafts & Additions mod. And there is already one month old issue in their github. Hope they will fix that one time
https://github.com/mrh0/createaddition/issues/527
