### ISSUE TITLE
[BUG] server files are broken

### ISSUE THREAD

**Issue by Xplodin** [itsdinkd/AQM2#214]
**Modpack Version**
What modpack version
1.5.1
**Minecraft Version**
What mc version
1.19.2
**Describe the crash or bug**
there is no server_overrides and server cannot start properly and let clients connect
![image](https://user-images.githubusercontent.com/13007677/233193793-7d2af799-94bb-422d-a3fb-a55b6fbc3cb3.png)

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
use server files from curse, run the batch file once.
**Expected behavior**
What is the expected outcome?
server to start properly 
**Screenshots**
Post screenshots if available
![image](https://user-images.githubusercontent.com/13007677/233193793-7d2af799-94bb-422d-a3fb-a55b6fbc3cb3.png)
**Crash log or latest.log.log**
use pastebin.com for your log
[serverstarter.log](https://github.com/itsdinkd/AQM2/files/11277396/serverstarter.log)
**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
you are missing the server_overrides folder that comes with the download

**Comment by Xplodin** [comment]
> you are missing the server_overrides folder that comes with the download


I download the files straight from curse and there is 0 files inside the server_overrides folder

**Comment by itsdinkd** [comment]
> > you are missing the server_overrides folder that comes with the download
> 
> I download the files straight from curse and there is 0 files inside the server_overrides folder

I know. It still looks for the folder hence the error when it was gone
