### ISSUE TITLE
[BUG]Calibrator recipe broken 

### ISSUE THREAD

**Issue by ZaRb0G** [itsdinkd/AQM2#215]
**Modpack Version**
1.5.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Calibrator recipe is broken because Crafting calculator was removed 

**Steps to reproduce the behavior:**
-

**Expected behavior**
-

**Screenshots**
![SharedScreenshot](https://user-images.githubusercontent.com/128565586/233245209-ee0608aa-a9c6-46f8-aba3-8a63182429bf.jpg)

**Crash log or latest.log.log**
-

**Additional context**
-

**Comment by itsdinkd** [comment]
Thanks!

**Comment by itsdinkd** [comment]
fixed in 1.5.3
