### ISSUE TITLE
Crash after going into Inv. Profiles Next mod options[BUG] 

### ISSUE THREAD

**Issue by cosmikbun** [itsdinkd/AQM2#216]
**Modpack Version**
1.5.1, fabric 0.14.18

**Minecraft Version**
1.19.2

**Describe the crash or bug**
I went into the mod menu to change the settings for the Inventory Profiles Next mod. I found it and clicked the config button, the gray one with the slider-looking bits on it. The game crashed immediately after clicking the button, but it should be able to be clicked if client options are allowed to be toggled.

**Steps to reproduce the behavior:**
Click the Mod button from the pause menu. Search for Inventory Profiles Next. Click the mod config button in the top right.

**Expected behavior**
See "Describe the crash or bug"

**Screenshots**
N/A

**Crash log or latest.log.log**
https://pastebin.com/MZneE1UB

**Additional context**
N/A

**Comment by itsdinkd** [comment]
I would recommend posting this to the IPN github as I can't this it
