### ISSUE TITLE
[BUG] Powah! Mod crashes

### ISSUE THREAD

**Issue by TjureOdinsson** [itsdinkd/AQM2#217]
**Modpack Version**
AQM2 newest available at curseforge

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When i try to place any reactor of "POWAH!" mod, the game crashes

**Crash log or latest.log.log**
[use pastebin.com for your log](file:///C:/Users/domen/curseforge/minecraft/Instances/Another%20Quality%20Modpack%202%20-%20AQM2/logs/2023-04-21-2.log)file:///C:/Users/domen/curseforge/minecraft/Instances/Another%20Quality%20Modpack%202%20-%20AQM2/logs/[2023-04-21-2.log](file:///C:/Users/domen/curseforge/minecraft/Instances/Another%20Quality%20Modpack%202%20-%20AQM2/logs/2023-04-21-2.log)

**Comment by itsdinkd** [comment]
Log?
