### ISSUE TITLE
[BUG] Toms Storage/Compact Storage

### ISSUE THREAD

**Issue by TjureOdinsson** [itsdinkd/AQM2#218]
**Modpack Version**
AQM2-1.19.2-1.5.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
When i wanna build a storage system with "Toms Storage Mod" and i use the chests from "Compact storage" Mod, the Slots getting reseted when i leave the world and load back in. (when i set it up i have 16k slots, i leave the world and join back in i have like 4k slots)
Then i have to destroy the chests and place them again

Normal vanilla chests and chests from Expanded storage mod work fine tho!

**Comment by itsdinkd** [comment]
This used to happen with expanded storage when toms did not have a compatibility change. Seems the same is happening here.

It **should** be client side visual only. You should have the actual amount but you will see less or sometimes more.

Nothing I can do to fix this though, this would need the developer of both mods to change on their end. I suggest reporting to them
