### ISSUE TITLE
[BUG] startserver.sh has invalid carriage returns at end of lines

### ISSUE THREAD

**Issue by lv00-player** [itsdinkd/AQM2#219]
**Modpack Version**
1.5.1

**Describe the crash or bug**
I'm on archlinux and I couldn't run the startserver shell script because there were carriage return characters at the end of each line. I think this is normal for files on windows but bash would give me errors when trying to run the script.
I was able to remove it with a quick ```tr -d '\r' < startserver.sh > output.sh```.

**Steps to reproduce the behavior:**
Run 'startserver.sh' on linux

**Crash log or latest.log.log**
```zsh: ./startserver.sh: bad interpreter: /bin/bash^M: no such file or directory```

**Comment by itsdinkd** [comment]
Saw this too late. I'll fix for 1.5.3

**Comment by itsdinkd** [comment]
I know nothing about unix and commands but can you write that I can put in the actual startserver.sh script so it does this on its own when someone runs it?

**Comment by FederAndInk** [comment]
you can make git do it for you :)
https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings#10419350

**Comment by itsdinkd** [comment]
fixed in 1.5.5!
