### ISSUE TITLE
[BUG] Recipe clash from Fluid Tanks, hence no Traveler's Backpack

### ISSUE THREAD

**Issue by szaborobert21** [itsdinkd/AQM2#22]
**Modpack Version**
1.2.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
The new Traveler's Backpack cannot be crafted because the recipes for the upgradable Fluid Tanks are broken. 

**Steps to reproduce the behavior:**
Try and craft a Copper, Tin or Stone Tank. Impossible.

**Expected behavior**
4 Wood Tank = 1 Copper Tank, 4 Copper Tank = 1 Tin Tank and so on...

**Screenshots**
![Screenshot 2022-05-27 213000](https://user-images.githubusercontent.com/106407051/170785299-fb7b9521-0c84-4136-9b7e-30e9c6ca4beb.png)

**Crash log or latest.log.log**
https://pastebin.com/5gbELMGg

**Additional context**
To create the Backpack Tank you need 3 Iron Tanks which are made with 4 Tin, Copper or Stone tanks. The recipes clash here as either of these tanks require Wood Tanks, and hence cannot be crafted. I tried crafting in both the normal Crafting Table and Crafting Station, but to no avail. Also, the game crashes if you click on the recipe that uses Create's auto crafting for any of the Tin, Copper or Stone tanks.

**Comment by Tylaris** [comment]
The recipe isn't displaying correctly, but the recipe does work.  

You need tanks you are upgrading from in the corners and the material you are upgrading to on the sides.

wood to copper:
![image](https://user-images.githubusercontent.com/23402951/171083641-0b5e0582-5f9d-40e1-9646-58d0da70cafe.png)
copper to iron:
![image](https://user-images.githubusercontent.com/23402951/171083846-3b7dc00c-a588-471e-8d18-f0beff540030.png)

**Comment by itsdinkd** [comment]
Recipe fixed in 1.2.4. Different from default recipe above ^. will show in rei
