### ISSUE TITLE
[BUG] Outdated MineCells v1.4.1 -> v1.4.3. Comparator not updating (Requires block update)

### ISSUE THREAD

**Issue by EpicGazel** [itsdinkd/AQM2#221]
**Modpack Version**
1.5.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Comparators need a block update to function. They otherwise will not update in response to inventories.

**Steps to reproduce the behavior:**
Place 2 hoppers facing into each other. Insert an item. Attach a comparator to one of the hoppers. Watch the comparator not update, repeatedly place a block next to the comparator and observe it updating.

**Expected behavior**
The comparator should work without block updates.

**Additional Context**
The problem does not appear to lie solely in indium as the removal of indium did not fix the issue.

**Comment by EpicGazel** [comment]
Solution:
Update minecells from 1.4.1 to 1.4.3. Broken comparator/redstone is a known and fixed [issue](https://github.com/mim1q/MineCells/pull/37).

**Comment by itsdinkd** [comment]
Updated in 1.5.2
