### ISSUE TITLE
[BUG] Dragonslayer Swordspear issue

### ISSUE THREAD

**Issue by bobman9** [itsdinkd/AQM2#224]
**Modpack Version**

1.5.1

**Minecraft Version**

**Describe the crash or bug**

Dragonslayer Swordspear is not giving loot or xp on kill when you use the throwing attack (primary hand, right click)

**Steps to reproduce the behavior:**

Kill enemies with throwing attack

**Expected behavior**

To get loot and XP on kill

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**

Killing enemies with the normal melee attack is working fine, just not the throwing of it for the killing blow

**Comment by itsdinkd** [comment]
Seems like the developer did not implement a way to obtain xp when throwing. Nothing I can do on my end unfortunately. Would have to be reported to Marian souls weapon developer.
