### ISSUE TITLE
Orchard grain  + AE2 crash [BUG]

### ISSUE THREAD

**Issue by Jackelol** [itsdinkd/AQM2#225]
**Modpack Version**
1.5.1

**Minecraft Version**
1.9.2

**Describe the crash or bug**
Inputing orchard grain or crafting orchard bread in an ME system crashes the server

**Steps to reproduce the behavior:**
Try using orchard grain

**Expected behavior**
Getting orchard bread or having orchard wheat in the ME system

**Crash log or latest.log.log**
Not the server owner so unfortunately don't have the logs

**Additional context**
Did not test with other versions of the ancient seed products but i suspect they would do the same

**Comment by itsdinkd** [comment]
Without a log I can't really do much. Also from looking at the description of what you wrote, this would more than likely need to be reported to the ae2 developers.

**Comment by itsdinkd** [comment]
closing to staleness
