### ISSUE TITLE
[Feature/Suggestion] Mod-suggestion OpenBlocks Elevator (Fabric)

### ISSUE THREAD

**Issue by farrucho** [itsdinkd/AQM2#226]
**Is your feature request/suggestion related to a problem? Please describe.**
This block used to be in old modpacks and it was really cool.

**Describe the suggestion you'd like**
I would like to add this mod to the modpack.

[**curseforge link**](https://legacy.curseforge.com/minecraft/mc-mods/openblocks-elevator-fabric)

I think this mod would be a good addition because in the old days of 1.12.2 everyone loved this elevator.

**Additional context**
Simple port of the OpenBlocks Elevator mod to Fabric
This mod adds the famous 1.12.2 Elevator block, fully functional so you can teleport up and down in your world.
You can even edit the range of the blocks in the config.

**Comment by itsdinkd** [comment]
Kibe elevator does the same exact thing as open blocks elevator
