### ISSUE TITLE
[BUG] AE2 Graphical Bug with kubejs

### ISSUE THREAD

**Issue by AzaelMew** [itsdinkd/AQM2#227]
**Modpack Version**
1.5.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Graphical Bug with AE2 crafting terminal

**Steps to reproduce the behavior:**
-

**Expected behavior**
-

**Screenshots**
https://imgur.com/VoHHEyI

**Crash log or latest.log.log**
-

**Additional context**
Files that are effected: AQM2\kubejs\assets\ae2\textures\wtlib\guis

**Comment by itsdinkd** [comment]
fixed in next ver
