### ISSUE TITLE
[BUG] [1.19.2 Ver. 1.5.2] Extremely slow chunk loading

### ISSUE THREAD

**Issue by JackSpidy** [itsdinkd/AQM2#229]
**Modpack Version**
1.5.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Chunks load extremely slow, in both singleplayer and server environments, causing rubberbanding when entering unloaded chunks and some chunks to be "loaded" but completely invisible, even upon F3+A. Memory and CPU usage are both fine.

**Steps to reproduce the behavior:**
Load into AQM2 and either log into server (hosted locally on different machine) or a singleplayer world, and attempt to fly with either elytra+fireworks or creative in one direction, eventually chunks will begin loading extemely slow, much slower than the player, and will take over a minute to catch up or singleplayer world/server will time out.

**Expected behavior**
Chunks not loading as slowly? I'm not familiar with Fabric or 1.19 modded in general yet, so idk if this is expected behavior or not.

**Screenshots**
![2023-05-04_20 16 02](https://user-images.githubusercontent.com/129154262/236355744-a00c06b6-057f-407f-9759-f0276d409665.png)

**Crash log or latest.log.log**
Log exceeded 512kb limit for pastebin, so I've just attached it here, sorry.
[latest.log](https://github.com/itsdinkd/AQM2/files/11402481/latest.log)

**Additional context**
Chunky, Chunksending, Farsight, Smoothchunks, and MusicTriggers + it's library are added both client and serverside, but without these the issue/outcome is still the same.

**Comment by itsdinkd** [comment]
`either elytra+fireworks or creative in one direction, eventually chunks will begin loading extemely slow, much slower than the player, and will take over a minute to catch up or singleplayer world/server will time out.`

This is normal. you are moving faster than your server / machine can load/generate chunks. 


My suggestion would be to download "Spark" and run a profiler just in case, while you are 'loading' chunks and posting it back here just to see if there is any other cause then normal functionality.

**Comment by JackSpidy** [comment]
> `either elytra+fireworks or creative in one direction, eventually chunks will begin loading extemely slow, much slower than the player, and will take over a minute to catch up or singleplayer world/server will time out.`
> 
> This is normal. you are moving faster than your server / machine can load/generate chunks.
> 
> My suggestion would be to download "Spark" and run a profiler just in case, while you are 'loading' chunks and posting it back here just to see if there is any other cause then normal functionality.

I've ran Spark, and everything there seems fine aside from the chunk loading obviously being high usage. and also just tested out other 1.19/1.18 modpacks for forge and fabric and gotten pretty much the exact same results, so I guess this is expected behavior, I'm used to older packs but I guess with the new world generation + mods on top of that is a lot to handle, pre-rendering a 3000x3000 square with Chunky on my server has stopped this from being a problem though, thanks for your time.
