### ISSUE TITLE
[BUG] RedCellBattery in Inmis backpack cause eventual CTD

### ISSUE THREAD

**Issue by subtumaka** [itsdinkd/AQM2#23]
**Modpack Version**
2.12
**Minecraft Version**
1.17.1
**Describe the bug**
Having a red cell battery from TechReborn in an Imnis Gilded Backpack causes a CTD after around 10 minutes of loading into the world. Unsure if SP issue, this has caused several issues on a Multiplayer server however.
This produces a normal crashlog, however does not produce anything in the Not-Enough-Crashlogs folder.

**To Reproduce**
1. Obtain gilded backpack
2. Move red cell battery into backpack's storage
3. Wait around 10 or so minutes
4. Try to click the backpack in the inventory to pick it up with the mouse, or open it inhand.
5. Game will CTD

**Expected behavior**
Red Cell Battery should be able to be put into backpacks indefinitely without an impending CTD. 

**Crash log or latest.log.log**
https://pastebin.com/XUB6kKp1

**Additional context**
I am unsure about if this occurs in singleplayer as this just occurred during multiplayer. At the time, I had exactly two red cell batteries in the backpack. And a jackhammer.

**Comment by itsdinkd** [comment]
https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/70
