### ISSUE TITLE
Croptopia Greenhouse Crash

### ISSUE THREAD

**Issue by BeanAlrighty** [itsdinkd/AQM2#23]
**Modpack Version**
V1.2.3 [1.18.2]

**Minecraft Version**
1.18.2

**Describe the crash or bug**
When a fully grown aconite crop from bewitchment grows to maturity beneath a croptopia greenhouse, it will crash the game/server.

**Steps to reproduce the behavior:**
Place a croptopia greenhouse, hoe the ground, place an aconite seed, grow it to completion and crash.

**Expected behavior**
You will crash

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**

https://pastebin.com/4bjqiWW4 

**Additional context**
I think this happens with all bewtichment seeds, I'm unsure if it happens with any other seed

**Comment by itsdinkd** [comment]
This is known and there already is a warning given in the information tab of the recipe in REI

![image](https://user-images.githubusercontent.com/35115304/170849049-ddeca829-5f96-4d37-a632-333305f6107e.png)
