### ISSUE TITLE
[BUG]Cursed gem recipe dont work anymore 

### ISSUE THREAD

**Issue by ZaRb0G** [itsdinkd/AQM2#231]
**Modpack Version**
1.5.2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
cursed gem recipe dont work anymore 

**Steps to reproduce the behavior:**
try to craft the cursed gem in the assembler 

**Expected behavior**
should produce the cursed gem

**Screenshots**
-

**Crash log or latest.log.log**
-

**Additional context**
-

**Comment by itsdinkd** [comment]
fixed in 1.5.5
