### ISSUE TITLE
Dragon Gobber Armor Not Unbreakable

### ISSUE THREAD

**Issue by 4North4** [itsdinkd/AQM2#232]
**Modpack Version**
What modpack version 1.5.4

**Minecraft Version**
What mc version1.19.2

**Describe the crash or bug**
Dragon Gobber armor is not unbreakable after being crafted.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Craft Dragon armor
**Expected behavior**
What is the expected outcome?
Should be unbreakable per you and the achievement 
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
Just adding this here as a reminder for you.

**Comment by itsdinkd** [comment]
Closing because it is unbreakable after crafting
