### ISSUE TITLE
[BUG] dragon kin dragon breath self damage

### ISSUE THREAD

**Issue by ShyviaAngel** [itsdinkd/AQM2#233]
**Modpack Version**
What modpack version
1.5.4
**Minecraft Version**
What mc version
1.19.2
**Describe the crash or bug**
just a bug with dragonkin origin fireball  the user doesnt have the immunity to it as said in the origin description

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
just enter the magic damage zone of the fireball or shoot it at your own feet
**Expected behavior**
What is the expected outcome?
immunity to magic damage
**Screenshots**
Post screenshots if available
![image](https://github.com/itsdinkd/AQM2/assets/133601808/93eaa375-0975-4aa3-93c9-344c940bf477)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
It's disabled
