### ISSUE TITLE
AE2 inscriber press recipe doesn't exist in REI [BUG]

### ISSUE THREAD

**Issue by Draktastic** [itsdinkd/AQM2#234]
**Modpack Version**
1.5.6.1

**Minecraft Version**
1.19.2

**Describe the bug**
REI states that AE2 inscriber presses are crafted in the Botania mana pool, and to check REI for the recipe. The recipe does not exist for the mana pool.

**Steps to reproduce the behavior:**
Look up the recipe in REI. Left clicking on any press opens up tabs that describe how to craft that press by using that press, in addition to the tab stating it's craftable through Botania.

**Expected behavior**
REI should display the recipes for the AE2 inscriber presses when displaying uses for mana infusion.
Tossing an item into a mana pool (assuming with an alchemy catalyst underneath) is expected to produce the following items:
Certus quartz crystal into a calculation press
Diamond nugget into an engineering press
Gold nugget into a logic press
Silicon into a silicon press

**Screenshots**
![2023-05-20_23 31 45](https://github.com/itsdinkd/AQM2/assets/130191113/ef454727-5874-455f-bf8a-442b1dec5710)
![2023-05-20_23 38 48](https://github.com/itsdinkd/AQM2/assets/130191113/ddc02758-1736-447e-9f3e-350df1b05c5c)
![2023-05-20_23 38 49](https://github.com/itsdinkd/AQM2/assets/130191113/cf1b15df-ddce-495d-a093-6ec446820735)
![2023-05-20_23 38 51](https://github.com/itsdinkd/AQM2/assets/130191113/dd632e07-c44d-4cec-a40d-817245d03fc2)
![2023-05-20_23 47 36](https://github.com/itsdinkd/AQM2/assets/130191113/c1b13c4d-04c5-4a23-9a85-baf4ac9d6b82)

**Comment by itsdinkd** [comment]
![Uploading image.png…]()
