### ISSUE TITLE
[BUG] Can't run AQM2 on Apple M1 CPU (MacOS, aarch64)

### ISSUE THREAD

**Issue by metalim** [itsdinkd/AQM2#236]
**Modpack Version**
1.5.6.1

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Can't run on Apple M1 CPU (MacOS, aarch64)

**Steps to reproduce the behavior:**
Start AQM2 in MacOS running on M1 or M2 CPU

**Expected behavior**
Game started

**Screenshots**
no

**Crash log or latest.log.log**
crash log: https://mclo.gs/tCO0UZD
latest.log: https://mclo.gs/GGG4AAJ

**Additional context**
Tried vanilla JDK 17, and GraalVM EE JDK — same result: crash on com.sun.jna.Native initialization

**Comment by itsdinkd** [comment]
Github is used for bug reports. You can use our discord for support http://aqm2.cc

**Comment by metalim** [comment]
Ok. isn't that a bug though? Discord says don't post bug reports and issues there

**Comment by metalim** [comment]
UPDATE: It sure is a bug, as one of mods is using JNA without providing code for aarch64 CPU architecture
