### ISSUE TITLE
[BUG] no boss drops from Mariums Soulslike Weaponry

### ISSUE THREAD

**Issue by Valinnn** [itsdinkd/AQM2#237]
**Modpack Version**
1.5.7hf

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Killed the Returning Knight boss with my friend, i was using Kirkhammer he was using Sniper Sword. we kill it, look around, no drops from him. we were playing on official Zion server

**Steps to reproduce the behavior:**
idk i guess go kill him with those weapons and see if you get drops?

**Expected behavior**
his hammer, lord soul, whatever else he drops, yk the usual

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
unable to reproduce

**Comment by itsdinkd** [comment]
unable to reproduce
