### ISSUE TITLE
[BUG] Dragonkin origin magic damage

### ISSUE THREAD

**Issue by Valinnn** [itsdinkd/AQM2#238]
**Modpack Version**
1.5.7hf

**Minecraft Version**
1.19.2

**Describe the crash or bug**

**Steps to reproduce the behavior:**
become a dragonkin origin, use primary ability, stand in the purple magic zone, you will take damage

**Expected behavior**
not take damage from ALL magic , even my own (as the origin says)

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Magic immunity is disabled

**Comment by itsdinkd** [comment]
#233 also duplicate
