### ISSUE TITLE
[BUG] Unable to Use Moth Origin Ability

### ISSUE THREAD

**Issue by drwolf17** [itsdinkd/AQM2#24]
**Modpack Version**
AQM2-1.2.3
**Minecraft Version**
1.18.2

**Describe the crash or bug**
The cooldown for the Flutter Ability for the Moth origin is stuck and wont progress, making me unable to use it. 

**Steps to reproduce the behavior:**
The bug started after the bouji server's world reset. This bug does not happen on any of my singleplayer worlds. Best guess for why it happened was when my player data from the backup server of the old bouji world got moved over to the new one since thats when it started happening. 

**Expected behavior**
The flutter ability is supposed to, Every 25 seconds, you are able to launch yourself 10-20 blocks upwards when you press the primary ability key.

**Screenshots**
![Bugged Cooldown](https://user-images.githubusercontent.com/29005854/170846769-635a0f8d-e8dd-425b-a6e7-e1194210c927.jpg)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
IGN in superminer548 if it is a problem with my player data.

**Comment by itsdinkd** [comment]
Still occuring?

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
