### ISSUE TITLE
[BUG] createaddition:alternator and createaddition:electric_motor can not be crafted

### ISSUE THREAD

**Issue by Simba98** [itsdinkd/AQM2#243]
**Modpack Version**
What modpack version
Verified on AQM2 >= 1.5.2

**Minecraft Version**
What mc version
1.19.2 
**Describe the crash or bug**
createaddition:alternator and createaddition:electric_motor can not be crafted in survival mode.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Just look up JEI

The reason is a mod (Unifix sth? I do not know the name, so I just call it unifix) disabled the reduplicate items, e.g. multiple iron rods.

However, the mechanism crafting in create addition mod, specified the c:rods/iron, and only the iron rod in the create addition mod will have the tag, the other use the tag of c:iron_rods.
![image](https://github.com/itsdinkd/AQM2/assets/7941967/b02d1a16-3a57-4a7c-a3a2-94d02cfc4b83)
![image](https://github.com/itsdinkd/AQM2/assets/7941967/301be84f-e231-48e0-8fb7-60710e9cbc02)
![image](https://github.com/itsdinkd/AQM2/assets/7941967/ccb64386-6aa6-4eb7-b0db-7c815b907e3d)

So the createaddition:alternator and createaddition:electric_motor can not be crafted.

By changing the createaddition-fabric+1.19.2-20230211a.jar\data\createaddition\recipes\mechanical_crafting\electric_motor.json
I fixed and tested this issue, I will open an issue in the GitHub of the create addition.
But I think AQM2 can fix it before create addition did it.

**Comment by TheCreepyGinger** [comment]
Can you share the json file? Did you fix the alternator too by any chance?

**Comment by Simba98** [comment]
> Can you share the json file? Did you fix the alternator too by any chance?

[createaddition-fabric+1.19.2-20230211a.zip](https://github.com/itsdinkd/AQM2/files/11945920/createaddition-fabric%2B1.19.2-20230211a.zip)
Yes, both are fixed. And you may use this repacked jar mod file to replace it. Unzip the zip file you will have the jar.
https://github.com/mrh0/createaddition MIT License, so the changed jar file should also be licensed in MIT. And thanks mrh0 for delelopment.

**Comment by itsdinkd** [comment]
fixed for when we use create additions again
