### ISSUE TITLE
[BUG] Prime Eye drop missing 

### ISSUE THREAD

**Issue by 4North4** [itsdinkd/AQM2#244]
**Modpack Version**
1.5.9

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Prime Eye item is not dropped from The Eye boss.

**Steps to reproduce the behavior:**
Have summoned the eye 10+ Times and have not gotten any prime Eyes from it, required for angel ring. 

**Expected behavior**
Prime eye item should drop from the eye boss

**Additional context**
The prime  Eye is an item required in angel ring and on bouji drops perfectly fine from the Eye Boss. The void also does not spawn after the eye is killed on zion. Tested on bouji 7/5/23 and had no issues.

**Comment by itsdinkd** [comment]
cannot fix but removed from angel ring recipe
