### ISSUE TITLE
V1.6.1 server lib39-machination error

### ISSUE THREAD

**Issue by p928s1984** [itsdinkd/AQM2#245]
**Modpack Version**
1.6.1 server

**Minecraft Version**
1.19.2

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lib39-machination'!

**Steps to reproduce the behavior:**
Running java 17, trying to start the server with the startserver.sh 
get the error above "lib39-machination", server will not start

**Expected behavior**
Server starts without error? 

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
https://pastebin.com/9yu7wTeb

**Additional context**
first time setting up this pack, not sure what is going on. 
I just attempted to downgrade and I am able to run 1.6.0 without issue.

**Comment by itsdinkd** [comment]
I released a hotfix already. You can update the modpack or delete lib39.
