### ISSUE TITLE
[BUG] AQM2 Crashes on macOS Sonoma

### ISSUE THREAD

**Issue by PsychoH13** [itsdinkd/AQM2#250]
**Modpack Version**
Another Quality Modpack 2

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Minecraft crashes before it even shows the loading screen, the launcher reappears after a while reporting error 255.

**Crash log or latest.log.log**
https://pastebin.com/7sijBixr

**Comment by itsdinkd** [comment]
User error. (fat file, but missing compatible architecture (have 'i386,x86_64', **need 'arm64'))** 


change your virtual machines architecture to arm64

**Comment by PsychoH13** [comment]
Huh I'm not using a virtual machine here.
