### ISSUE TITLE
[BUG] Cant have superflat for some reason

### ISSUE THREAD

**Issue by BrianTheguyIguess** [itsdinkd/AQM2#251]
**Modpack Version**
What modpack version
1.6.3
**Minecraft Version**
What mc version
Fabric 1.19.2
**Describe the crash or bug**
Whenever I try to have superflat I do everything and when it loads in it just does the default for some reason no matter what I do

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Just do Superflat and as you can see it doesnt work and makes it a normal world (Isnt supeflat)
**Expected behavior**
What is the expected outcome?
to have superflat
**Screenshots**
Post screenshots if available
I feel like I dont need to show this since I didnt and im too lazy to do it
**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
That's because terralith doesn't support it.
