### ISSUE TITLE
The Croparia recipe is using grape seeds only

### ISSUE THREAD

**Issue by Bluedot55** [itsdinkd/AQM2#255]
**Modpack Version**
1.6.3

**Minecraft Version**
1.19.2

**Describe the crash or bug**
The croparia recipe is set to use any forge seed. This category only includes grape seeds, which seems incorrect. 

**Steps to reproduce the behavior:**
Check the recipe for the base croparia item

**Expected behavior**
It uses normal seeds

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
North already confirmed this is a bug

**Comment by itsdinkd** [comment]
![image](https://github.com/itsdinkd/AQM2/assets/35115304/00f73dd9-1edd-4726-9cc8-d6fbd7a6dc6e)
oh nice. thats because the developer put a forge tag in a fabric environment
