### ISSUE TITLE
[BUG] Registry remapping failed: Received ID map for minecraft:item contains IDs unknown to the receiver!

### ISSUE THREAD

**Issue by D4rktec** [itsdinkd/AQM2#258]
**Modpack Version**
1.6.3

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Registry remapping failed: Received ID map for minecraft:item contains IDs unknown to the receiver! - mcdw:sword_the_starless_night

**Steps to reproduce the behavior:**
Join a Server with the Modpack

**Expected behavior**
Joining the Server

**Screenshots**
![image](https://github.com/itsdinkd/AQM2/assets/131616644/5b2e4223-22b6-4657-8259-fb39a2b169f6)

**Crash log or latest.log.log**
https://pastebin.com/86L2zcxa

**Additional context**
Both Client and Server Running the Same Version.
Server ist Installed with following Settings
MC-Version: 1.19.2
Fabric Loader Version: 0.14.21
Fabric Installer Version 0.11.2
RAM: 16GB

Already tried with 1.19.3 and/or Fabric Loader 0.15.3 (Server does even not start)

Server Setup:
1. The Server ist startet with the basic settings (MC Version and Fabric Loader).
3. the server will be stoppt and the mods will be loaded in the mods folder (from the curseforge client version)
4. the "world" folder will be deleted
5. stating the server again
6. after the server is fully startet try to join

so the client and the server have for sure the exact same mods and version

**Comment by D4rktec** [comment]
Edit:
if i remove the mod there are more Error appering:
![image](https://github.com/itsdinkd/AQM2/assets/131616644/c109c51a-c3d6-4b05-94af-a8a0060184a2)

**Comment by itsdinkd** [comment]
This means you are missing those mods in your modpack on your client _**or**_ server and/or your configs are mismatched. 

It's most likely your configs being mismatched as the registry is mentioning things that can be disabled via configs.

I suggest reinstalling. also please use the discord for things like this. this is not a bug.
