### ISSUE TITLE
[BUG] ServerStarter can't load the server-setup-config.yaml

### ISSUE THREAD

**Issue by JulianVennen** [itsdinkd/AQM2#259]
**Modpack Version**
1.7

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Running the start.sh of the server files causes an error

**Steps to reproduce the behavior:**
Download the server files and run the start.sh or start.bat

**Crash log or latest.log.log**
https://gist.github.com/JulianVennen/7602d6680181501ad11e5a0c5c758982

**Comment by itsdinkd** [comment]
Thanks for reporting, i fixed this issue but forgot to upload it into the server pack zip file. 

I just uploaded the fix to curseforge, however, if you want to skip downloading/waiting for it to be approved, go into the server-config yaml file

Look for
```
  additionalFiles:
    - mods/expandedstorage-8.3.4+1.19.2-fabric.jar
```

and replace it with just this
```
  additionalFiles:
```
