### ISSUE TITLE
[Feature/Suggestion] Flowery Structures mod

### ISSUE THREAD

**Issue by kittech0** [itsdinkd/AQM2#26]
**Is your feature request/suggestion related to a problem? Please describe.**
It's not related to a problem.

**Describe the suggestion you'd like**
Add minecraft mod

**If this is a request to add a mod, what is the curseforge link?**
https://www.curseforge.com/minecraft/mc-mods/flowery-structures

**Why do you think this would benefit the modpack?**
It adds many small, ambient & vanilla++ structures, they are not big so they will not really effect the gemplay  itself but they will add many ambient stuff making adventure more varied. It's based on idea of old Ruins mod.

**Additional context**
![obraz](https://user-images.githubusercontent.com/73485099/170888363-1afb7037-342c-4388-82b6-31a1a302a0f1.png)
![obraz](https://user-images.githubusercontent.com/73485099/170888368-7e7bf5b1-a1fd-4427-8671-d347a2273423.png)

**Comment by itsdinkd** [comment]
Cool mod and thank you for the suggestion,  will have to pass though. We are using additional structures in the pack which adds small structures as well.
