### ISSUE TITLE
[BUG] Refined Storage UI Disappearing

### ISSUE THREAD

**Issue by Mohammad-Ishtiaq** [itsdinkd/AQM2#260]
**Modpack Version**
What modpack version
1.6.1

**Minecraft Version**
What mc version
1.18.2

**Describe the crash or bug**
When entering "Sawdust" from the Thermal Series mod into the Refined Storage grid it makes everything disappear in the UI.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

1. Refined Storage basic setup : Controller, Disk Drive, Grid, Power
2. Enter random items into the system.
3. Then enter some sawdust and exit the UI
4. Open Ui again and the items will not load.

**Expected behavior**
What is the expected outcome?
Items should be visible.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
This should be fixed in v1.7 of aqm3 as refined storage had a major update
