### ISSUE TITLE
[BUG] Receiving XP on every mob spawner break with silk touch

### ISSUE THREAD

**Issue by thebruceree** [itsdinkd/AQM2#261]
**Modpack Version**
What modpack version
1.7

**Minecraft Version**
What mc version
1.19.2

**Describe the crash or bug**
Every time I break a spawner with silk touch, I receive XP. Infinite XP basically.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
1. Find spawner and mine with silk touch.
2. Place spawner down and mine again with silk touch
3. Profit

**Expected behavior**
What is the expected outcome?
Breaking spawners without silk touch should probably give XP, but when you get the spawner by using silk touch, you probably shouldn't be given xp?

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Fixed in v1.8
