### ISSUE TITLE
[BUG] LargeFluidTank tanks have 1000x less than they should (non-integer bucket counts)

### ISSUE THREAD

**Issue by Abaddon16** [itsdinkd/AQM2#262]
**Modpack Version**
**1.7**

**Minecraft Version**
**1.19.2**

**Describe the crash or bug**
Tanks from the `LargeFluidTank` mod have the wrong capacity. For example, the `Wood Tank` will hold 4mb. This is shown in the image below. I tested various ways to ensure this wasn't user error and that it wasn't just a "the UI _says_ 4mb, but really means 4 buckets" situation. 
1. I used a bucket to try and insert, no dice
2. I used a Create pump to put water into the tank (this worked) and tried to retrieve it with a bucket. The water disappeared, but the bucket remained empty

I looked at the config and saw that the capacities are listed as what is shown in game (e.g. - 4mb for Wood Tanks), and this holds true for all of the tanks. My guess is that while the mod's `Tier` class intends to multiply this by 1000 on object generation (per the GitHub repo), that there may be something different with how it's processing the config file versus internal values, resulting in the config file potentially needing to be changed.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Place down a `Wood Tank` from `LargeFluidTanks`. Attempt to put water from a bucket into it.

**Expected behavior**
That the tanks have the expected values (e.g. - Wood tank holds 4 buckets). 

**Screenshots**
![image](https://github.com/itsdinkd/AQM2/assets/6559658/2a0e3d7c-c6bc-41d2-b386-e7a1e41c878f)

**Crash log or latest.log.log**
N/A, no crash

**Additional context**
N/A

**Comment by itsdinkd** [comment]
This is working as it should. You are comparing the tier 1 tank, wood. 

the mod page specifically states tier 1 is 4mb. 
![image](https://github.com/itsdinkd/AQM2/assets/35115304/8678d777-5b85-4b9f-b90e-4d53bec6185e)

**Comment by Coolburritoboi** [comment]
Sorry, but I believe you misunderstood, the tier 1 is 4B (buckets) not 4mb (millibuckets). This can be easily fixed in the config by multiplying each tank's capacity by 1000.
Installing largefluidtanks on a different instance also shows this since both the capacity and config lists the wood tank as 4000mb (which is 4 buckets).
