### ISSUE TITLE
[BUG] v1.8 contains 1.20 mods?

### ISSUE THREAD

**Issue by JulianVennen** [itsdinkd/AQM2#263]
**Modpack Version**
v.18

**Minecraft Version**
1.19.2

**Describe the crash or bug**
It appears that the modpack contains a few 1.20 mods, even though it is running 1.19.2.

**Steps to reproduce the behavior:**
Download the server files and run them (should also happen on the client)

**Expected behavior**
The server should start 

**Crash log or latest.log.log**
https://mclo.gs/H2cFP2B#L24

**Comment by itsdinkd** [comment]
Ah, the issue is not that it contains 1.20 mods, its that Fabric Loader is still on the older version for Server Start. You need version 0.15.10. Go to server_files/settings config, and change both call outs to "0.14.25" to "0.15.10"

I will release a update for the server pack

**Comment by itsdinkd** [comment]
Released fix in curseforge
