### ISSUE TITLE
[BUG] Incompatible mods on AQM2-1.19.2-1.8.3.zip

### ISSUE THREAD

**Issue by TheHappywheels1** [itsdinkd/AQM2#266]
**Modpack Version**
AQM2-1.19.2-1.8.3.zip

**Minecraft Version**
1.19.2

**Describe the crash or bug**
Incompatible mods on new instance/install. Unable to load

**Steps to reproduce the behavior:**
Install the modpack on Cureseforge and attempt to load

**Expected behavior**
Modpack should load as normal

**Crash log or latest.log.log**
https://pastebin.com/BcAqcxmc

**Additional context**
Any additional context?

**Comment by SirDarkBliss** [comment]
Hi! I am a moderator for the discord for this modpack, currently the fastest workaround for this would be; open curseforge, click on the modpack in your my modpacks folder, click on the triple dots near the play button, click on profile options, under advanced settings you can then choose your modloader versions, please select fabric 0.15.11 for the meantime, I have tested it and it will boot no issues, until this is updated please use this method. Sorry for the inconvenience!

**Comment by TheHappywheels1** [comment]
Thanks for the quick reply, that did the trick. Shall look out for the next update to the modpack

**Comment by itsdinkd** [comment]
Fixed with 1.8,4

Thanks for reporting
