### ISSUE TITLE
[BUG] Portal Charm not working as intended in necklace slot

### ISSUE THREAD

**Issue by FishyDreamer** [itsdinkd/AQM2#27]
**Modpack Version**
v1.2.4hf

**Minecraft Version**
1.18.2

**Describe the crash or bug**
The portal charm doesn't work as intended with the nether portal when equipped in the necklace slot but works when held in hand. Doesn't also work with the caving portal regardless if in hand or slot.

**Steps to reproduce the behavior:**
Walk into nether portal or caving portal with portal charm in necklace slot.

**Expected behavior**
Instant shift to new dimension upon touching portal. Intended behavior occurs when necklace is held in hand.

**Additional context**
N/A

**Comment by itsdinkd** [comment]
What is a portal charm?

**Comment by FishyDreamer** [comment]
This is the portal charm. ![image](https://user-images.githubusercontent.com/29006642/171520494-609d492e-d68c-4912-91e4-f678a0aafd64.png)

**Comment by itsdinkd** [comment]
Nothing I can do about this. You'll have to raise this to the developer of the mod.
