### ISSUE TITLE
[BUG] botania bauble pendant crash

### ISSUE THREAD

**Issue by Evan545** [itsdinkd/AQM2#29]
**Minecraft Version**
1.18.2

**Describe the crash or bug**
the instant i equipped the snow pendant my game crashed

**Crash log or latest.log.log**
[<script src="https://pastebin.com/embed_js/8scGEWiN?theme=dark"></script>](https://pastebin.com/8scGEWiN)

(I hope this works)

**This modpack is pretty fun so having this happen is a real bummer**

**Comment by itsdinkd** [comment]
this will need to be reported to botania
