### ISSUE TITLE
[Tag Support]  Add tags to unify certain blocks

### ISSUE THREAD

**Issue by nukeofwf** [itsdinkd/AQM2#3]
SUPPORT TICKET | OVERVIEW (@Nukeofwf)

Category: Ingame Client Support

AQM2 or AQM3?
AQM2

Can you launch the game successfully?
Yes

If yes, please choose one, are you unable to join a server, or join your single player world? otherwise say other
other

Pick what this ticket is regarding, Mod Support | Quest Support | Feature Support | Crash Log | Cannot Join Official Server | Other
mod support

Have you filled out a bug report?
no

Was your bug report denied?
no

Did your game crash?
no

Is this related to a specific mod or something the server is causing like a ticking entity?
no

What is your modpack version (not minecraft version, but modpack version)
1.1.1

Did this happen on Single Player, AQM Official Server, or unofficial server?
unofficial

If Official Server, which server?
n/a

(REQUIRED) there was a crash or error involved, Please provide link from https://paste.corebot.dev/ -- Copy and paste your entire crash log from /crash-reports or /logs/latest.log at this website and paste the link to it here.`
n/a

Please explain in detail your issue
It seems that in version 1.1.1, the ore dictionary support is very limited, and a couple of issues have arisen.
1) when attempting to make a pedestal for spectrum, I could not make polished calcite in any vanilla furnace, as 'consistency plus' had taken that recipe and that block is not ore-dictionary synonymous with spectrum's polished calcite
2) in version 1.1a I could use any mod's bronze in the compression machine from Modern industrialization, but as of version 1.1.1, the bronze ingot from industrial revolution seems to not be a analogue to modern industrialization version of it.

**Comment by nukeofwf** [comment]
Was told by Sebas it looks like a config issue with kubejs and polymorph

**Comment by itsdinkd** [comment]
There is no OreDictionary in fabric. That is a forge thing. I'm going to assume you mean tags. Also, next time please use the **provided issue template for bug reports** that appears when you Create a New issue.

**Comment by nukeofwf** [comment]
Apologies, I was just linked here through discord, so I copy/pasted the ticket that was generated.

**Comment by itsdinkd** [comment]
For Bronze Ingots, There is only one bronze ingot, and that should be Tech Reborn. You should be able to use however a bronze ingot from any other mod if on the off chance you actually have it. You might not see it in a recipe, just know you can use it in the recipe. Please confirm if you are able to craft using a bronze ingot from indrev in a MI machine or wherever you are trying to use it. (Dont use REI to determine if you can or cannot, you have to actually place it in a recipe)

**Comment by itsdinkd** [comment]
__Also I already have a script to remove Polished Calcite from consistency plus. Can you send me your log in logs/kubejs/server.txt please?__

Edit: nevermind, the namespace was wrong. fixing.

**Comment by nukeofwf** [comment]
![image](https://user-images.githubusercontent.com/624153/168174599-6479ddda-a39b-45d9-b83e-784201ac55f5.png)
The Steel compressor stays in this state and never processes the ingot into plate, also when put into the forge hammer
![image](https://user-images.githubusercontent.com/624153/168174737-f53a44c8-031a-4ec3-8aac-6357972a9f12.png)
No crafting options appear. If I place in iron ingots, standard crafting options appear.
The bronze ingots I have are from Indrev, which were created in 1.1a from the 3copper 1 tin 2x2 recipe in handheld crafting after crack hammering.
However, the dust I just created is from tech, and smelts into tech ingots, and compresses into tech plates.  
The IndRev bronze ingots appear to be orphans.

**Comment by nukeofwf** [comment]
I JUST SAW that you can put the ingot in a shapeless craft to change what mod it is. That resolves the issue. So it is no longer an orphan ingot. and looks that way for all indrev ingots I have seen so far. Thanks for your time.
