### ISSUE TITLE
[BUG] looking up uses of AE2 crystal seed causes crash

### ISSUE THREAD

**Issue by busterbrown1999** [itsdinkd/AQM2#30]
**Modpack Version**
AQM2 1.5.1
**Minecraft Version**
1.18.1 

**Describe the bug**
looking up uses of AE2 crystal seed causes crash
**To Reproduce**
1. Search an AE2 Crystal see 
2. Rick click or press U
3. Crash

**Expected behavior**
Shows Uses

**Crash log or latest.log.log**
https://pastebin.com/79xniBe8

**Comment by itsdinkd** [comment]
Duplicate of https://github.com/itsdinkd/AQM2/issues/22
