### ISSUE TITLE
[BUG] Another Quality Modpack 2 - 1.18.2 Cant open Things

### ISSUE THREAD

**Issue by Sionax2001** [itsdinkd/AQM2#31]
Cant open (Crafting Table, Chests, Doors Furnace etc...) if i dont hold an item in my hand.

It says "Nobody owns this block" tried in Gammode but dont work. 

Not working in Multiplayer Server.

**Comment by itsdinkd** [comment]
Go into config/flan 

"inspectionItem": "minecraft:air", 

 change to 

"inspectionItem": "kubejs:aqm2",

**Comment by Sionax2001** [comment]
I changed it but its not saving it, when i startup the Server its just reseting to minecraft:air.

**Comment by itsdinkd** [comment]
> I changed it but its not saving it, when i startup the Server its just reseting to minecraft:air.

try minecraft:stick
