### ISSUE TITLE
[BUG] Cleric Class gives random enchantments

### ISSUE THREAD

**Issue by jonathanjamestar** [itsdinkd/AQM2#32]
**Modpack Version**
v1.5.1 & v1.4.3
**Minecraft Version**
1.18.1
**Describe the bug**
For the Cleric class, enchanting a piece of armor sometimes does not improve the enchantment as the description says but gives a random enchantment.

**To Reproduce**
1. Select any race and the Cleric class
2. Enchant any piece of armor/weapon

**Expected behavior**
The armor should have the enchant as shown on the enchantment table with improvement or the same enchant as shown.

**Screenshots**
https://imgur.com/a/5LkwbS6

**Crash log or latest.log.log**
https://pastebin.com/zP2ibbFh

**Additional context**
In a modded minecraft with only Origins and Origins:Classes, the feature works as intended.

**Comment by itsdinkd** [comment]
does this still occur
