### ISSUE TITLE
[BUG] FallingTree mod does not recognize Gobber Paxels as axes.

### ISSUE THREAD

**Issue by FishyDreamer** [itsdinkd/AQM2#32]
**Modpack Version**
v1.2.4hf

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Gobber Paxel does not allow mining of a tree from its bottom log. Gobber axe however does not have this issue.

**Steps to reproduce the behavior:**
Mine any log with more than one log above it. The log mined is removed.

**Expected behavior**
The logs above it should be removed first and dropped as an item.

**Additional context**
N/A

**Comment by itsdinkd** [comment]
Please report this to the Gobber developer

**Comment by FishyDreamer** [comment]
This issue no longer exists on the most recent version of the modpack.
