### ISSUE TITLE
[BUG] Palladium Ore

### ISSUE THREAD

**Issue by Lex808** [itsdinkd/AQM2#33]
Palladium Ore was changed in configs to a negative Y Cord
Althought this Ore only spawns in the nether,
so i believe this is why it is unfindable
if we can get that changed to a correct nether cord above negative
i believe a simple edit of config and restart would fix it
Thanks.

Mod - Mythical Metals

**Modpack Version**
1.5.2
**Minecraft Version**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by itsdinkd** [comment]
Fixed with recent versions
