### ISSUE TITLE
Registry remapping failed

### ISSUE THREAD

**Issue by axissnova** [itsdinkd/AQM2#34]
Connection lost message "Registry remapping failed: Received ID map for minecraft:block contains IDs unknown to the receiver! - kubejs:magical_soil" when attempting to connect to server hosted on apex hosting. Both server and client are on version 1.2.4 for AQM 2 1.18.2

**Comment by itsdinkd** [comment]
Please open a new ticket and use the bug template provided when selecting bug issue
