### ISSUE TITLE
Game crashes on Minotaur hit

### ISSUE THREAD

**Issue by Bunshock476** [itsdinkd/AQM2#35]
**Modpack Version**
1.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Game crashes on Twilight Forest Minotaur hit

**Steps to reproduce the behavior:**
Entering the maze and getting attacked by Minotaur

**Expected behavior**
Just taking damage

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
Crash log: https://pastebin.com/dCgQK0hb

**Additional context**
It happened everytime I got hit. At the time was wearing full enchanted Doom armor, with a couple of gobber items in the inventory, not sure if it was related.
Not able to test it further for now as I got another crash when entering the Minoshroom room. Apparently it crashed while trying to render it and now I'm not able to enter the world as it instantly crashes after joining it, but will open another issue for it specifically later.

**Comment by itsdinkd** [comment]
Please report this to Twilight Forest

**Comment by itsdinkd** [comment]
Minotaur disabled in 1.3.1 and reported to twilight team
