### ISSUE TITLE
[BUG] Debris Miners Drop Gear with disabled enchantments

### ISSUE THREAD

**Issue by TheSheev** [itsdinkd/AQM2#35]
**Modpack Version**
1.5.2a
**Minecraft Version**
1.18.1
**Describe the bug**
Debris Miners (Piglin Brute) drop items that sometimes have enchantments on them, but when viewed, the enchantments are "disabled or missing."

**To Reproduce**
1. Go to Nether and/or obtain spawner.
2. Find Debris Miner
3. Kill until gear drops. Looting helps.
4. Hold "Shift to see enchants"
5. See that Enchant is disabled/missing

**Expected behavior**
Items have enchantments.

**Screenshots**
Not available on current computer. Some on home computer. Will update later.

**Crash log or latest.log.log**
N/A

**Additional context**
N/A

**Comment by itsdinkd** [comment]
If the enchantment is showing disabled then that means intended behavior its most likely a MCDW enchantment (Without screenshots I cannot say for sure)

**Comment by TheSheev** [comment]
Below is screenshot showing exact issue. In one of the earlier versions I believe they had regular enchantments on them? It's on the multiplayer server, so I can't go back and find which one it was.
![2021-12-31_18 07 11](https://user-images.githubusercontent.com/89590514/149184490-195022a9-529d-45f8-92d7-ae6963fe3b8a.png)
