### ISSUE TITLE
[BUG] boss Minotaur in twilight forest.

### ISSUE THREAD

**Issue by DaddySangradorBugFinder** [itsdinkd/AQM2#36]
**Modpack Version**
What modpack version
1.3
**Minecraft Version**
What mc version
1.18.2
**Describe the crash or bug**
Once you enter the room, game goes bye bye.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Enter the Minotaur room after completing the dungeons prior 
**Expected behavior**
What is the expected outcome?
Crash once u enter
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log
I’m on mobile but text me and I’ll give it to you.
**Additional context**
Any additional context?
No uwu

**Comment by itsdinkd** [comment]
Need to see logs.

**Comment by itsdinkd** [comment]
Minotaur disabled in 1.3.1 and reported to twilight team

**Comment by itsdinkd** [comment]
Duplicate of #35
