### ISSUE TITLE
Can't equip hats in 1.5.1

### ISSUE THREAD

**Issue by MedicinalOSRS** [itsdinkd/AQM2#37]
Can't equip hats in 1.5.1.
Hats are only able to be worn in the shield slot

**Comment by itsdinkd** [comment]
Need more information
What hats specifically?  We have disabled a few hats. 
Screenshots as well please.

**Comment by MedicinalOSRS** [comment]
All of the hats from Give Me Hats mod,
Tested with Sailor, Woolrus, dwarvern, bowler, cowboy, crown, fez, jotaros, slime, witches, viking + santa hat. None can be equipted in any of the slots apart from the shield slot
![javaw_JwhHjtgZDv](https://user-images.githubusercontent.com/88799496/148737266-f7174352-687b-4688-8b05-8dd3e3484a00.png)
.

**Comment by itsdinkd** [comment]
Update your pack
