### ISSUE TITLE
[BUG]enchament tooltips crashing minecraft wen shift hovering over curse of thorns

### ISSUE THREAD

**Issue by KlaraChaos** [itsdinkd/AQM2#38]
**Modpack Version**
1.5.2a
**Minecraft Version**
1.18.1
**Describe the bug**
enchant tooltips commpley crashes Minecraft if ya shift hover over curse of thorns
**To Reproduce**
1. Get  a book or tool that has the curse of thorns enchant
2. shift hover over book or tool
3. Minecraft crashes

**Expected behavior**
Minecraft not crashing and just showing the info about the enchant

**Screenshots**
N/A

**Crash log or latest.log.log**
https://pastebin.com/JhLtFydd

**Additional context**
happed wen i was fishing and a book had the curse on and i shift click so i can fast put it into a chest

**Comment by itsdinkd** [comment]
Fixed by removing Enchanted Tooltips from 2.0.1
