### ISSUE TITLE
[BUG] New cosmetic armor crash

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#38]
**Modpack Version**
1.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Ya know which one is it, it was fixed in the past iirc but now it's back.
Equiping armor on the cosmetic slot while wearing actual armor will make your client (and anyone's if they see you) crash

**Crash log or latest.log.log**
https://gist.github.com/itsdinkd/6a7cb4aef5e8462c7eb47401cca23155

**Additional context**
Crash report is not mine btw, just making sure the report is being made

**Comment by itsdinkd** [comment]
mod was removed
