### ISSUE TITLE
[BUG] Nether Temple Causes Crash of Client-Side Server

### ISSUE THREAD

**Issue by FishyDreamer** [itsdinkd/AQM2#39]
**Modpack Version**
v1.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Single player world crashes when in a nether temple. Suspect that dispenser or some other redstone going off is causing this.

**Steps to reproduce the behavior:**
Possibly by activating redstone in nether temple. Repeated this behavior on three different crashes.

**Expected behavior**
Server not to crash upon activating redstone.

**Crash log or latest.log.log**
[crash-2022-06-06_14.48.31-server.txt](https://pastebin.com/pFQsaFBP)

**Additional context**
N/A

**Comment by itsdinkd** [comment]
There should be another crash report, or if you can send me latest.log when this happened. the crash report you attached is not showing the issue

**Comment by itsdinkd** [comment]
closed due to no response
