### ISSUE TITLE
[BUG] Unification issue with some foods

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#4]
**Modpack Version**
v1.1.1

**Minecraft Version**
1.18,2

**Describe the crash or bug**

- Tomatoes from Sandwichable shows recipes, but the ones from croptopia and Farmer's delight shows no recipes with them

- Cabbage and rice from Farmer's Delight shows recipes, but the one from croptopia doesn't.

- Garlic from Bewitchment shows all the recipes it should have, but the one from croptopia has no recipes
 
- Soybeans and Soybean seeds from Croptopia and The Veggie way shows different recipes, and the seeds from one cannot convert to the other.

**Expected behavior**
Those ingredients should be unified, seeds included 

**Additional context**
I can't cook now! xD

**Comment by itsdinkd** [comment]
This is a feature from 1.1a. Now only 1 food type exists, instead of 5 variants. The one that has recipes is selected tyoe. Put the item in question in the crafting table by itself and you should be able to convert it.

 Seeds were never unified

**Comment by Sebas-Re** [comment]
Maybe I didn't explain myself correctly there. That was my first thought, and I've already tried to convert them to the variant that has recipes, but it didn't work sadly. This is what I mean:

croptopia:tomato
![image](https://user-images.githubusercontent.com/32151264/167525283-14d1ea52-a28d-42f2-aca3-f1dfbf7a958d.png)

Farmer's delight tomato
![image](https://user-images.githubusercontent.com/32151264/167525491-96dc9f2f-9ea1-47d0-a353-3264dcc94cab.png)

Croptopia:rice (does not give valleycraft's variant, so this item is useless atm)
![image](https://user-images.githubusercontent.com/32151264/167525348-99566f9b-9aad-4573-a839-919b6123811d.png)

Croptopia:cabbage
![image](https://user-images.githubusercontent.com/32151264/167525414-cf54b1c0-64d7-4cff-b695-20c7a5783bc9.png)

croptopia:garlic
![image](https://user-images.githubusercontent.com/32151264/167525549-e45a7334-2197-410f-8b1e-b066ea8d298e.png)

**Comment by itsdinkd** [comment]
Alright I'll get it fixed

**Comment by TrippyV** [comment]
Just started playing the modpack today and still having this issue on version 1.2.2
