### ISSUE TITLE
[BUG] Prefab's previews arent working

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#40]
**Modpack Version**
1.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Prefab's previews arent working, you cannot see anything when in preview mode

**Steps to reproduce the behavior:**
use a prefab

**Expected behavior**
should show prefab preview 

**Screenshots**
![borrar1](https://user-images.githubusercontent.com/32151264/172284728-a5302f87-7b53-4555-a715-e4d32371b8ec.png)
![borrar2](https://user-images.githubusercontent.com/32151264/172284736-29e2dc9e-b58b-4ec1-a9bc-ca500615789f.png)

**Crash log or latest.log.log**
forgot to extract latest log. Will do when I can

**Comment by itsdinkd** [comment]
will need client log

**Comment by Laff70** [comment]
This happens for me too, nothing shows up.

**EDIT: It apparently works if I turn shaders on. How odd.**
