### ISSUE TITLE
[BUG] Server Crash with 2+ Players - Unknown Reasons

### ISSUE THREAD

**Issue by ZenithAstralis** [itsdinkd/AQM2#40]
**Modpack Version**
1.5.2a

**Minecraft Version**
1.18.1

**Describe the bug**
Multiple players at once cause server crash.

**To Reproduce**
1. Be logged on.
2. Someone else logs on.
3. Wait between Zero and Sixty seconds.
4. Server crashes.

**Expected behavior**
Server should ideally not crash in these circumstances.

**Screenshots**
None available, sorry.

**Crash log or latest.log.log**
https://pastebin.com/KbPSEy8a

**Additional context**
Does not appear to matter which players or where in the world they are when they log on. I'm sorry I can't make much of my read through the crash log; it appears to involve something called "Completable Futures" and may or may not involve entities being waterlogged or not? Sorry, and thank you.

Submitting because no one else on the server will; I can liaise with them but have not experienced it first hand.

**Comment by itsdinkd** [comment]
This crash error is basically saying there is a tick that takes longer than
the max tick rate (60000 by default) so watchdog comes in to crash the
server so it doesn't stall. You can you editing your server properties and
increasing max tick rate.

And then you should also add spark into your server and run its profiler so
you can see what is causing the long tick

**Comment by itsdinkd** [comment]
Other than that, I can't really assist here. This isn't a bug, nor a crash.
It's minecraft doing its thing. Let's see what spark says though and we can
go from there.
