### ISSUE TITLE
[BUG] I bring you some cute bugs uwu

### ISSUE THREAD

**Issue by DaddySangradorBugFinder** [itsdinkd/AQM2#42]
**Modpack Version**
What modpack version
1.3
**Minecraft Version**
What mc version
1.18.2
**Describe the crash or bug**
-Motherdemon will keep spawning after killing it if you wait for a minute or so.
-Gladiator will not naturally spawn
-Wrench from MI let’s you grief and steal buttons, and every single machine from AE2 on a claim.
-Ring of stealth makes every doom monster and boss ignore you, so they won’t hit you any time.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Bosses on their natural structures, with ring of stealth 
Wrench on claims
Ring of stealth in the nether
**Expected behavior**
What is the expected outcome?

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
Ps: couldn’t kill the gauntlet not even cheesing it, just one shots u no matter what

**Comment by itsdinkd** [comment]
1) mother demon has multiple lives. Not a bug
2) gladiator spawns at its structure. Not a bug 

Please refrain from opening 1 issue containing multiple bugs, this is not the correct way to opening issues. Now  I cannot close a issue for the things you wrote that aren't bugs, nor do I have the structure required. 

Please open new issues for the other two bugs you wrote about.
