### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThePoeticGoat** [itsdinkd/AQM2#43]
**1.5.2**

**1.18.1**

**cannot launch the mod**
i go to launch the mod and Minecraft and midway trough the loading on the launcher it says, "error: could not create the java virtual machine. error: a fatal exception has occurred. program will exit." then closes

**To Reproduce**
1. Go on 'curseforge'
2. Click on 'install' to install the mod "another quality modpack 2"
3, wait for it to install
3. Press 'play'
4. Launcher will then open and press play again in the Minecraft launcher.
5. See error (up in the description of the problem)

**Expected behavior**
it is supposed to launch and download normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/97387337/148680013-fb5f45ce-3c58-41e1-888b-bcc8953850b2.png)

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by itsdinkd** [comment]
Okay this is not a bug with the modpack.
