### ISSUE TITLE
[BUG] Server sometimes crashes when player with origin Golem takes damage from mob

### ISSUE THREAD

**Issue by MatthiasMistelbauer** [itsdinkd/AQM2#44]
**Modpack Version**
1.5.2
**Minecraft Version**
1.18.1
**Describe the bug**
My Minecraft Server sometimes crashes when a player with the origin Golem gets damage from a mob. This occured when the player took damage from a phantom and one time from a motherblob.  This crash das not always occur when the player gets damage from these mobs.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash log or latest.log.log**
I found the following in my server logs:
[09.01 13:26:47] [Server] [ForkJoinPool.commonPool-worker-2/INFO]: Loaded 5219 translation keys
[09.01 13:26:47] [Server] [ForkJoinPool.commonPool-worker-2/ERROR]: There was a problem reading sub-power "lank:no_regen_o___0" in power file "lank:no_regen": Error reading data field at effects.[1]: Identifier "minecraft:intant_health" was not registered in registry "minecraft:mob_effect".
[09.01 13:26:47] [Server] [ForkJoinPool.commonPool-worker-2/ERROR]: There was a problem reading sub-power "lank:small_attribute_modifiers" in power file "lank:small": Error reading data field at modifiers.[2].attribute: Identifier "reachentityattributes:attack_range" was not registered in registry "minecraft:attribute".
[09.01 13:26:47] [Server] [ForkJoinPool.commonPool-worker-2/ERROR]: There was a problem reading power file ratsmischief:ratified (skipping): Power type "requiem:soul_type" is not defined.

I do not know if this is related to the problem.

Crash Report (crash-2022-01-09_13.17.32-server):
https://pastebin.com/WAyRLWz3

Logs after restart:

Look what happens after the "player passiv_aggressiv" joins the game.
https://pastebin.com/D75xyLRN

After that the Server crashed and I restarted the server the same thing happend. I fixed this problem by teleporting the player after he joined immediately

**Additional context**
My server is currently running fine and I will give more input to this problem if we encounter this bug again.

**Comment by itsdinkd** [comment]
Please provide a **full** crash log or latest log and upload it on pastebin.com and provide the link here

**Comment by MatthiasMistelbauer** [comment]
Crash Report (crash-2022-01-09_13.17.32-server):
https://pastebin.com/WAyRLWz3

Logs after restart:

Look what happens after the "player passiv_aggressiv" joins the game.
https://pastebin.com/D75xyLRN

After that the Server crashed and I restarted the server the same thing happend. I fixed this problem by teleporting the player after he joined immediately

**Comment by itsdinkd** [comment]
Is he a golem born by chance? if so, those are disabled and powers removed. the crash reason looks like its due to powers not being found

**Comment by MatthiasMistelbauer** [comment]
How can a origin be born by chance?

When he first joined the game, he select Golem as his origin.

**Comment by MatthiasMistelbauer** [comment]
Server crashed again. Probably the same problem as last time. This time the player did not recieve damage.
Crashlog:
https://pastebin.com/qhrb8mYk

Logs:
https://pastebin.com/fQk0MB8f

**Comment by itsdinkd** [comment]
The origin is called **"GOLEM BORN"** 

I am asking you if its the **GOLEM BORN** origin, not if a golem is born by chance... There are two different golem origins.

**Comment by MatthiasMistelbauer** [comment]
He selected this origin when he joined the server for the first time.
![image](https://user-images.githubusercontent.com/91223104/150173803-49dad712-74f4-460d-aa81-fccaa893bd07.png)

**Comment by itsdinkd** [comment]
does this still occur with versions 2.x?

**Comment by MatthiasMistelbauer** [comment]
Hi, sorry for the late response.

We quit playing on the server two months ago. Therefore I can't give any more feedback regarding this issue.

**Comment by itsdinkd** [comment]
No worries
