### ISSUE TITLE
[BUG] Can't create world

### ISSUE THREAD

**Issue by Unofficial545** [itsdinkd/AQM2#44]
**Modpack Version**
1,3

**Minecraft Version**
1.8.9

**Describe the crash or bug**
Can't create singleplayer world neither default nor superflat

**Steps to reproduce the behavior:**
Create singleplayer world

**Expected behavior**
What is the expected outcome?

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
https://pastebin.com/1zhBhipp

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Update modpack to 1.3.2 and also i need latest.log, invalid crash report.
