### ISSUE TITLE
[BUG] Not able to start a new world

### ISSUE THREAD

**Issue by Nebelraucher** [itsdinkd/AQM2#45]
**Modpack Version**
What modpack version

**Minecraft Version**
1.18.2

**Everytime i click create world its says cant create world because of The twilight forest**

**Start a new World**

** Game Crash**
What is the expected outcome?

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
https://bytebin.lucko.me/fgQeALjRxm

**Comment by itsdinkd** [comment]
I'm sorry. I really regret adding that broken mod.
