### ISSUE TITLE
[BUG] Curl won't follow redirects

### ISSUE THREAD

**Issue by brct-james** [itsdinkd/AQM2#46]
**Modpack Version**
AQM2 v1.5.2a Server

**Minecraft Version**
1.18.1

**Describe the bug**
startserver.sh may not handle redirects correctly when downloading serverstarter-2.1.1.jar

**To Reproduce**
1. Setup server using the latest image of [itzg/docker-minecraft-server](https://github.com/itzg/docker-minecraft-server)
2. Attempt to start server
3. Wait for it to download the jar file and fail to start
4. Open jar file
5. See that it is html

**Expected behavior**
Curl follows redirects to download jar file

**Additional context**
Recommend explicitly specifying -L option in curl cmd

**Comment by itsdinkd** [comment]
I have no control of this as I am not the developer. You could report this to https://github.com/BloodyMods/ServerStarter

**Comment by brct-james** [comment]
Issue is fixed on main in https://github.com/BloodyMods/ServerStarter. The version in the pack is out of date.

If curl is bugged, it doesn't matter whether I start it locally or in the dedicated container... That workaround is fine for windows but not if you use linux locally as well.
