### ISSUE TITLE
Weird crash while playing AQM2

### ISSUE THREAD

**Issue by kamilikot2** [itsdinkd/AQM2#46]
**Modpack Version**
AQM2-1.3.2

**Minecraft Version**
1.18.2

Soo I started playing on latest version of this modpack and out of nowhere my game crashed

After collecting some wood and basic materials, I crafted stone pickaxe to mine some coal, next I created some torches and placed one on coal ore, then my screen went black, game froze for a minute or so and just closed. I don't really understand these logs, but probably it has to do with shaders?

Here's crash report
https://pastebin.com/PGuBmpgL

**Comment by itsdinkd** [comment]
Hmm your crash report is saying it's due to building gadgets. 

What tools were you using

**Comment by itsdinkd** [comment]
closed due to no response
