### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Zaveryan** [itsdinkd/AQM2#47]
It would be really cool for it to work on 1.19

**Comment by AzureDoom** [comment]
Because it's as easy as turning an 18 to an 19, amrite XD 
![image](https://media3.giphy.com/media/XBCJIv6xAyDfrajXoe/giphy.gif)

**Comment by itsdinkd** [comment]
> It would be really cool for it to work on 1.19

It would be really cool if it life was that simple :)
