### ISSUE TITLE
[BUG] Tech Reborn Lapatron Crystal in Inmis Backpack causes CTD

### ISSUE THREAD

**Issue by RojinUK** [itsdinkd/AQM2#48]
**Modpack Version**
1.5.2a
**Minecraft Version**
1.18.1
**Describe the bug**
If placing a lapatron crystal in an inmis backpack, when you hover over the backpack in your inventory this will result in a crash. This appears to be due to Shulker Tooltips, as disabling this stops the issue happening.

**To Reproduce**
1. Add Lapatron Crystal to backpack
2. Hover cursor over backpack so that tooltip showing contents should appear
3. Game crashes to desktop

**Expected behavior**
Tooltip showing contents should be shown.

**Screenshots**
n\a

**Crash log or latest.log.log**
[Crash report](https://pastebin.com/DUnyCX8F)

**Additional context**
n\a

**Comment by itsdinkd** [comment]
https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/70 

Posted about this 3 months ago, no luck on any fix since.
