### ISSUE TITLE
Arcanite abilities used on Rubro mob causes crash

### ISSUE THREAD

**Issue by drezzyuv** [itsdinkd/AQM2#48]
**Modpack Version**
AQM2 1.3.2

**Minecraft Version**
1.18.2

**Describe the crash or bug**
The projectiles of the arcanite origin abilities cause a crash/disconnect when used on Rubros, tested several times after it first happened and occured 100% of the time

**Steps to reproduce the behavior:**
By using either the fireball or wither skull ability of the arcanite on a Rubro

**Expected behavior**
For that to not happen

**Screenshots**

**Crash log or latest.log.log**

**Additional context**
It really is nothing major and doesn't really hinder the gameplay but I thought it wouldn't do any harm to still report it

**Comment by itsdinkd** [comment]
Oof. Which mod is Rubros from again? Earthbound right?

**Comment by itsdinkd** [comment]
Also can you please provide me the crash log
