### ISSUE TITLE
[BUG] Unable to unpack the steel furnace

### ISSUE THREAD

**Issue by ARTEMI5** [itsdinkd/AQM2#49]
**Modpack Version**
1.3.2

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Basically as the title says.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Try to put a steel furnace from the MI mod into an unpacker

**Expected behavior**
What is the expected outcome?
You should get back a bronze furnace and steel upgrade in line with other unpacker recipes

**Screenshots**
https://imgur.com/K6x9WUr

**Crash log or latest.log.log**
IDK why this is relevant but I will give you it anyway. I had to use onedrive cuz pastebin wants me to pay for pro just to paste this simple log. https://1drv.ms/t/s!Atg2Ok-xm8yW0ilFmWGh_4oLgxbG

**Additional context**
Any additional context?
Nope

**Comment by ARTEMI5** [comment]
id like to add that issue is also present for the steel wiremill

**Comment by DaddySangradorBugFinder** [comment]
Please remember to check your craftings, you don’t upgrade the steel furnace or the wire mill with a steel upgrade, they are crafted into steel, just like the boiler.
