### ISSUE TITLE
[BUG] Soulbound issue with graves

### ISSUE THREAD

**Issue by RojinUK** [itsdinkd/AQM2#49]
**Modpack Version**
1.5.2a
**Minecraft Version**
1.18.1
**Describe the bug**
As Soulbound has a chance to not keep the item in the players inventory, this can result in the item not actually being placed in the grave but dropped where the player died. If this is in the Nether then the items can be easily lost, or if you cannot return to the area fast enough the items may despawn.

**To Reproduce**
1. Enchant item, such as sword (this is the item that I have lost 3 times now)
2. When killed the item may not be kept in player inventory (this is a random chance?)
3. Returning to grave you will see the item on the floor instead of in the grave (if it hasn't been lost in lava or despawned)

**Expected behavior**
Item should be in the grave

**Screenshots**
n\a

**Crash log or latest.log.log**
n\a

**Comment by itsdinkd** [comment]
fixed on next update
