### ISSUE TITLE
[BUG] Chopping trees is still the same despite changelog saying otherwise

### ISSUE THREAD

**Issue by IvoryOwl92** [itsdinkd/AQM2#50]
Modpack Version: 1.6

Minecraft Version: 1.18.1

Bug: In version 1.6, the changelog states Felling Trees has been reverted so the player has to hold Shift to drop trees from top to bottom. This is not the case, since it still behaves the same as before.

**Comment by itsdinkd** [comment]
Will be fixed in next release

**Comment by itsdinkd** [comment]
in the meantime you can edit the falling tree config and set reverseSneaking to true
