### ISSUE TITLE
[BUG] Arcanite Origin - More hearts that intended

### ISSUE THREAD

**Issue by IvoryOwl92** [itsdinkd/AQM2#51]
Modpack Version:1.6

Minecraft Version: 1.18.1

Bug: Arcanite Origin is supposed to start off with fewer hearts, instead, it has more than intended.
![Captura de ecrã 2022-01-10 211512](https://user-images.githubusercontent.com/11478317/148841812-4d8de3cc-f9b4-4ff9-85cb-8cc446684da0.png)

**Comment by itsdinkd** [comment]
Reported to developer
