### ISSUE TITLE
[BUG] NO ZINC ORE

### ISSUE THREAD

**Issue by luddebigking** [itsdinkd/AQM2#53]
**Modpack Version**
What modpack version 1.3.2 

**Minecraft Version**
What mc version 1.18.2

**Describe the crash or bug**
There are no zinc ore in world gen

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

**Expected behavior**
What is the expected outcome?

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by xErrorAmelie** [comment]
Hey, you can search the discord for such information. You get zinc with tech reborn, not with mining.

**Comment by Deathcounter** [comment]
One further question. Zinc and Andesite are the two main things required for Andesite Alloys that are needed for most "Create" crafting recipes. Could it be that Andesite no longer generates in the world since 1.3.2? It did in 1.3 certainly tho.
