### ISSUE TITLE
[BUG]Coal ore in Macerator not Available

### ISSUE THREAD

**Issue by Arnesk** [itsdinkd/AQM2#53]
**Modpack Version**
1.6

**Minecraft Version**
1.18.1

**Describe the bug**
Cannot enter Coal ore into Macerator for the crushed dust. Coal crushed dust is still there with no known recipe to produce it.

**To Reproduce**
1. Go to Macerator
2. Fill with Coal Ore
3. Nothing happens.

**Expected behavior**
Coal ore should be turned into what i remember being 3 crushed coal dust.

**Screenshots**
![image](https://user-images.githubusercontent.com/97490479/148870254-e4ac547b-0570-40df-9c4e-cd7335217352.png)
![image](https://user-images.githubusercontent.com/97490479/148870319-99a32db9-077e-4e62-aaec-5e4a00f32635.png)

**Comment by itsdinkd** [comment]
Turn on advanced tooltips, and hover over the plus sign on the recipe you're referring to. please let me know the ID

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/149583308-aeb9a0f6-5991-4ff5-87c6-dfcd2e4037dd.png)

these are all the Macerator recipes that is stored inside the MI mod itself

**Comment by itsdinkd** [comment]
Has been determined that this is a issue with MI itself, which is a non-existent recipe.
