### ISSUE TITLE
[BUG] Server Crashes after using Bone Meal on Host Grass Block

### ISSUE THREAD

**Issue by zBimMaqi** [itsdinkd/AQM2#56]
**Modpack Version**
What modpack version
1.3.3
**Minecraft Version**
What mc version
1.18.2
**Describe the crash or bug**
I was on Bouji Server (it probably works on zion server too) and i wanted to bone meal the Host Grass Block to get Host Grass because it can drop Wither Roses, after using Bone Meal on the Host Grass Block the server immediately crashed.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Using Bone Meal on Host Grass Block
**Expected behavior**
What is the expected outcome?
Maybe trying to solve this bug, if not possible maybe deleting the Mod (Magic Fungi)
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
https://github.com/Luligabi1/MagicFungi/issues/63
