### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dominixoneq** [itsdinkd/AQM2#57]
**Modpack Version**
1.3.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Can't start server says 
"./start.sh: line 67: 3731938 Killed                  $JAVA $OTHERARGS $ARGS -jar fabric-server-launch.jar nogui"

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

**Expected behavior**
What is the expected outcome?
Server should start

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by FederAndInk** [comment]
You don't have any logs?

also, java17 is needed, see your java version with `java -version`

how much RAM do you have (available)? `free -h`

**Comment by Dominixoneq** [comment]
I managed to start the server but it crashed with the message above
And i have 8 gb total and 4.4 available
https://pastebin.com/k8RUVvYX <--- server log

**Comment by FederAndInk** [comment]
do you have any swap? are you using ubuntu? which version? the server might get killed if it uses too much ram compared to whats available

**Comment by Dominixoneq** [comment]
Im starting it right now and it doesnt seem to crash 
it was that it eat too much ram
changed it from 6g to 4 seems to work

**Comment by FederAndInk** [comment]
you can try to launch your server in a TTY without running a graphical interface. Also try using a lightweight distro for servers.

**Comment by itsdinkd** [comment]
Will re-open when this is properly named
