### ISSUE TITLE
[BUG] Gobber Staff of Transformation in Create Basin causes ticking block entity error/hardlocks out of world

### ISSUE THREAD

**Issue by bhuinda** [itsdinkd/AQM2#58]
**Modpack Version**
1.3.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Throwing a Staff of Transformation into a Create Basin will immediately cause a singleplayer (not tested in multiplayer) world to crash to the home screen, sending a Crashy report. I attempted to do this because there is a (custom?) recipe to automate Netherrack by combining a Staff of Transformation and Cobblestone by mixing them.

**Steps to reproduce the behavior:**
Place a Create Basin, set up a Mixer on top of it and run a Creative Motor into it for power, then throw the Gobber Staff of Transformation into the Basin.

**Expected behavior**
Crash to home screen, unable to rejoin world due to ticking block entity error caused by the Mixer.

**Screenshots**
https://gyazo.com/8df1c4a1c702d7ab743570aee8cc0407

**Crash log or latest.log.log**
https://pastebin.com/tivzdQ4z
https://crashy.net/VTLdPZ0AdCH8CLfSVfyI

**Comment by itsdinkd** [comment]
You will need to report this to the Create developers as there is nothing I can do to fix this

**Comment by itsdinkd** [comment]
Closed due to dev not being able to fix on their hand other than leaving a warning
