### ISSUE TITLE
[BUG] Ring of teleport doesn't show up in REI

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#58]
**Modpack Version**
v1.6
**Minecraft Version**
1.18.1
**Describe the bug**
Ring of teleport (from gobber) does not show up in REI

**Expected behavior**
The item should show up in REI

**Screenshots**
![image](https://user-images.githubusercontent.com/32151264/149061826-45001a9a-248c-4b55-ac70-83e3647e35de.png)
![image](https://user-images.githubusercontent.com/32151264/149061867-69b08424-2b3d-4980-8a8d-d8b1c9f97226.png)

**Comment by itsdinkd** [comment]
Fixed in next version
