### ISSUE TITLE
[BUG] Bouji Anti Cheat breaks flying mounts

### ISSUE THREAD

**Issue by PresidentCez** [itsdinkd/AQM2#59]
**Modpack Version**
1.3.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
I was using a mythic mount which was a bird and had the ability to fly. However, if you use said ability, it kicks you out of the server (being the bouji server) which completely destroys the purpose of the mount. It even got my mount killed since I wasn't able to move away from a skeleton in time when I rejoined. 

**Steps to reproduce the behavior:**
All you need to do is tame a flying mount and ride it. After a few second in the air, it will kick you from the server.

**Expected behavior**
After a few second in the air, it will kick you from the server.

**Additional context**
I don't know if this works for any other flying mob, but I think the mob was called a zar patak.

**Comment by Dres-Tiefling** [comment]
Can confirm. This happens to me and That_different too.

**Comment by itsdinkd** [comment]
Fixed
