### ISSUE TITLE
[BUG] Wandering trader crash server when spawning.

### ISSUE THREAD

**Issue by Limmek** [itsdinkd/AQM2#59]
**Modpack Version**
v1.6 (Server pack)

**Minecraft Version**
1.18.1

**Describe the bug**
Wandering trader crashes the server when spawning and the server just keep restarting when a player tries to connect.
Need to manually remove the entity with /kill command from the console before players are able to connect again otherwise the server just keep crashing.

**To Reproduce**
1. Upgrade mod pack from 1.5.2a to 1.6.
2. Start the server and play as normal.
3. Server crashes when a wandering trader spawns.
4. Players are unable to connect to the server, it crashes and keep restarting.
5. Use kill command on the server to remove the entity.
6. Players can now connect and start to play again.
7. Wait until a new trader spawn and you need to redo step **3-6**.

**Expected behavior**
The game should not crash when a wandering trader spawn nor when players tries to connect to the server after the trader has spawned.

**Crash log or latest.log.log**
https://pastebin.com/A9cLQFz1

**Comment by badgerlovk** [comment]
This crash occurs due to a conflict with MC Dungeons Armours and RPGStats.
Updating to RPGStats V4.3.4 will fix this issue
See related bug report https://github.com/P03W/RPGStats/issues/92
