### ISSUE TITLE
[BUG] Book of shadows / bewitchment No entries

### ISSUE THREAD

**Issue by nukeofwf** [itsdinkd/AQM2#6]
**Modpack Version**
1.1.1

**Minecraft Version**
1.18.2 

**Describe the crash or bug**
Bewitchment book of shadows has no entries

**Steps to reproduce the behavior:**
Craft bewitchment book of shadows with book and mandrake, Open book, no entries found.

**Expected behavior**
Mod information and entries should appear in book

**Screenshots**
![image](https://user-images.githubusercontent.com/624153/168194847-e04968d2-f1a7-4aef-be1f-c7ac8b86d828.png)
Error building entry bewitchment:brewing/elemental_oils
Error while loading entry bewitchment:brewing/elemental_oils page 6
Error setting up template processor

**Crash log or latest.log.log**
[latest.log](https://github.com/itsdinkd/AQM2/files/8683497/latest.log)

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
delete the file in kubejs/data/bewitchment

**Comment by nukeofwf** [comment]
File and folder does not exist client side, is this something to look at server side?

**Comment by itsdinkd** [comment]
My bad. I meant kubejs/server_scripts/bewitchment


You would need to remove it from the server if on a server. Otherwise remove it on client if playing SP

**Comment by nukeofwf** [comment]
Issue has been resolved in latest server version
Thanks.
