### ISSUE TITLE
[BUG] Nickel ingot

### ISSUE THREAD

**Issue by DaddySangradorBugFinder** [itsdinkd/AQM2#60]
**Modpack Version**
What modpack version

**Minecraft Version**
What mc version
Latest
**Describe the crash or bug**

Nickel I got from MI is uncraftable by any means or table and it is required for the ultimate ingot.
**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Try
**Expected behavior**
What is the expected outcome?
Uncraftable 
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
fixed in next version
