### ISSUE TITLE
[Feature Request] Minecraft Transit Railway mod

### ISSUE THREAD

**Issue by jbpixel52** [itsdinkd/AQM2#60]
Adds a complex train metro system over a simple vanilla rail system. 
It has routes, paths, schedules, the whole package.

Mod page: https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway

Tutorials by creator: https://youtube.com/playlist?list=PLp0jZgheSlXv_vjilwnbrOtdbmgvz1VkC

![2017-05-04_18.png](https://user-images.githubusercontent.com/50649423/149191344-ee9703e0-6c6e-4888-9cdb-3ae06c8d6fc8.png)

**Comment by itsdinkd** [comment]
Thank you for your suggestion
