### ISSUE TITLE
GAIA2 Not Dropping Dice Of Fate[BUG]

### ISSUE THREAD

**Issue by Yung-Buk** [itsdinkd/AQM2#61]
**Modpack Version**
AQM2-1.6
**Minecraft Version**
1.18.1
**Describe the bug**
Gaia Guardian 2 boss does not drop Dice of Fate when killed, and as far as i know it hasn't been disabled. I've Killed it twice now and i got the same result.

**Screenshots**

![image](https://user-images.githubusercontent.com/97660956/149285229-1d9a8268-e9ef-4c13-b0aa-613f3a826a70.png)

**Additional context**

**Comment by itsdinkd** [comment]
Relics are disabled
