### ISSUE TITLE
[BUG] Salt has no use from MI

### ISSUE THREAD

**Issue by DaddySangradorBugFinder** [itsdinkd/AQM2#61]
**Modpack Version**
What modpack version
Latest
**Minecraft Version**
What mc version
Latest
**Describe the crash or bug**
Macerates will give salt from MI, which you can’t turn into salt from Bewitchment by any means 

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Try it
**Expected behavior**
What is the expected outcome?
No use 
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?
UwU

**Comment by itsdinkd** [comment]
#41
