### ISSUE TITLE
[BUG] Infested Origin

### ISSUE THREAD

**Issue by Sylvie605** [itsdinkd/AQM2#63]
AQM2 1.6

AQM2 1.18

Infested origin dies of its own ability

To reproduce the bug you just have to use your ability as Infested and then go into stone and you will start to take damage

The Infested origin is supposed to survive and regen its decay bar in stone without taking damage

**Comment by itsdinkd** [comment]
Infested is disabled by default.

**Comment by Sebas-Re** [comment]
It's still there on the selection menu
![image](https://user-images.githubusercontent.com/32151264/151639896-6ea1b608-17d1-48a7-aef2-8f6474ef1a15.png)

**Comment by Sebas-Re** [comment]
Phantom Origin is also enabled, idk if it's intended, considering you get damaged when you go through blocks
![image](https://user-images.githubusercontent.com/32151264/151639953-4f2de787-245a-4689-a233-267eceafa468.png)
![image](https://user-images.githubusercontent.com/32151264/151640007-15f97fdd-81c3-49d2-bd17-e48ffb209bcd.png)
