### ISSUE TITLE
[BUG]Client crashes due to [Techreborn :data_storage_core]

### ISSUE THREAD

**Issue by binglingyao** [itsdinkd/AQM2#64]
**Modpack Version**
1.6hofix
**Minecraft Version**
1.18.1
**Describe the bug**
When [Techreborn :data_storage_core] exists in a container, opening the container causes a client crash.
If it is in the Shulker box and the shulker box is in inventory, the client will crash when the inventory is opened.

**To Reproduce**
1. Put a [Techreborn :data_storage_core] into the container.
2. Close the container, open the container again.
4. Client crash.

**Expected behavior**
Repair it

**Screenshots**
No screenshots

**Crash log or latest.log.log**
No error log is generated

**Additional context**

**Comment by itsdinkd** [comment]
There is an issue with tech reborn items and shulker boxes. avoid using shulker boxes with TR. use dank storage instead or backpacks.
