### ISSUE TITLE
[BUG] Smelting Recipe conflict between Spectrum and Consistency+

### ISSUE THREAD

**Issue by DaFuqs** [itsdinkd/AQM2#65]
**Modpack Version**
1.6

**Minecraft Version**
1.18.1

**Describe the bug**
The smelting recipes of Concistency+ Basalt/Calcite and Spectrum Basalt/Calcite collide, both being smelting products of raw Basalt/Calcite

**To Reproduce**
1. Put Calcite in a Furnace
2. It Smelts to Consistency+ Calcite

**Expected behavior**
Different recipes for both

**Comment by itsdinkd** [comment]
Which calcite? there are tons, same with basalt. Need specifics please.

**Comment by DaFuqs** [comment]
Those smelting recipes from spectrum are unavailable, because overwritten:
minecraft:calcite => spectrum:polished_calcite (calcite_to_polished_calcite.json)
minecraft:smooth_basalt => spectrum:polished_basalt (smooth_basalt_to_polished_basalt.json)

**Comment by itsdinkd** [comment]
Thanks! will be fixed next update

**Comment by itsdinkd** [comment]
Fixed in 1.7
