### ISSUE TITLE
[BUG] Cannot fell a tree with perks and items that state you can

### ISSUE THREAD

**Issue by BrickedKeyboard** [itsdinkd/AQM2#67]
**Modpack Version**
AQM2 v1.6-hotfix
**Minecraft Version**
Minecraft 1.18
**Describe the bug**
Some mod allows you to harvest a tree by breaking the bottom block.  This means the industrial chainsaw, which can 'harvest a whole tree at once', and the forester profession, which can fell a whole tree at once, don't get their perks.  

**To Reproduce**
Spawn yourself an industrial chainsaw or launch a new game and give yourself the forester profession.  Try cutting down a tree.  

**Expected behavior**
The entire tree should come down after you break the bottom block.

**Screenshots**

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by itsdinkd** [comment]
This is a bug with the Origins Classes. I suggest reporting it to them as this is something minor.
