### ISSUE TITLE
[BUG] Natures' staff from spectrum not working 

### ISSUE THREAD

**Issue by marybrook** [itsdinkd/AQM2#67]
**Modpack Version**
AQM2 1.3.3

**Minecraft Version**
1.18

**Describe the crash or bug**
Natures' stuff from spectrum doesn't work at all. People in spectrum discord say other mods can cause this issue but no details.

**Steps to reproduce the behavior:**
Use natures' staff
![image](https://user-images.githubusercontent.com/101207311/177014804-97c8416c-1a4a-4460-b6bd-47d9f02fae00.png)

**Comment by itsdinkd** [comment]
I have no power of other mods causing issues with spectrum's nature staff. spectrum will need to fix.
