### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CozyKeybord** [itsdinkd/AQM2#68]
**Modpack Version**
1.3.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Unable to break most stone 

**Steps to reproduce the behavior:**
I Just am unable to beak stone after creating a world 

**Expected behavior**
You should not be able to break most stone with any pickaxes or tools

**Comment by itsdinkd** [comment]
Change your origin and next time you open a issue please name it.
