### ISSUE TITLE
[BUG] Tree fruits from Croparia do not give a reasonable or useful output

### ISSUE THREAD

**Issue by BrickedKeyboard** [itsdinkd/AQM2#68]
**Modpack Version**
AQM2 
**Minecraft Version**
Minecraft 1.18
**Describe the bug**
The Croparia tree fruits, such as Oak Fruit, Spruce Fruit, Birch Fruit, Jungle Fruit, Acacia Fruit give saplings rather than wood.  This is completely useless - if you need saplings just plant the tree instead of wasting diamonds, lapis, and emeralds to make the seeds.

**To Reproduce**
Open up BEI or spawn yourself an "oak seed".  Plant it as a crop and grow it with bonemeal.  Notice when your harvest it you get a seed and a fruit.  Notice that the fruit gives saplings.  Now check all the other croparia plants.  There is an iron crop that gives iron ingots, gold crop gives gold ingots, and so on.

**Expected behavior**
The oak fruit should give oak logs or oak planks in a crafting table.  Same with the other woods.

**Screenshots**

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by itsdinkd** [comment]
You are comparing Croparia, a different mod, to croptopia.

**Comment by BrickedKeyboard** [comment]
> You are comparing Croparia, a different mod, to croptopia.

Type "@Croparia fruit" in BEI.  This is what this report is about.
