### ISSUE TITLE
[BUG] meat-lover able to eat apple

### ISSUE THREAD

**Issue by fallinforya** [itsdinkd/AQM2#7]
**Modpack Version**
1.1.1

**Minecraft Version**
1.18.1?

**Describe the crash or bug**
bug: place apples in faceslot -> eat them even when meat-lover

**Steps to reproduce the behavior:**
place apples in face-slot

**Expected behavior**
not able to eat apple as meat-lover

**Screenshots**
/

**Crash log or latest.log.log**
/

**Additional context**
/

**Comment by itsdinkd** [comment]
faceslot? can you provide screenshots please

**Comment by fallinforya** [comment]
![asdf](https://user-images.githubusercontent.com/22235101/168221781-9c98ecf0-0481-40fb-96a7-f74bd1445019.png)

yeah basically when you shift-rightclick apples in inventory it puts it in that slot and auto-eats when needed

**Comment by fallinforya** [comment]
shift-leftclick, sorry im too tired to think

**Comment by itsdinkd** [comment]
Lol wtf. That's a weird one. I'll see if I can blacklist apples for that slot I guess

**Comment by itsdinkd** [comment]
Does this still occur?

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
