### ISSUE TITLE
Archive does not contain a recognized modpack type[BUG]

### ISSUE THREAD

**Issue by inikishev** [itsdinkd/AQM2#71]
**Modpack Version**
What modpack version AQM2 v1.3.3

**Minecraft Version**
What mc version1.18.2

**Describe the crash or bug**
doesnt install with the message Archive does not contain a recognized modpack type[BUG]

**Steps to reproduce the behavior:**
download zip.
install zip.

**Expected behavior**
it installs 

**Screenshots**
![image](https://user-images.githubusercontent.com/76593873/178139074-733582a0-5782-4ab1-a706-db7e62bc8135.png)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by itsdinkd** [comment]
Use curseforge launcher or polyMC
