### ISSUE TITLE
[Crash] Does not launch - Unknown Reason

### ISSUE THREAD

**Issue by votex09** [itsdinkd/AQM2#72]
**Modpack Version**
AQM2 v1.4.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Pack doesn't launch through GDLauncher (latest stable) / PolyMC (1.3.2-404b9599) on Linux (Endeavour OS)
Unknown if this is isolated to Linux or just dumb on my part - but I haven't had any issues playing anything else.

Seems to point to org.spongepowered.asm.mixin.transformer.* - this is obscure due to other mods using this classpath commonly.

**Steps to reproduce the behavior:**
Create instance of pack through launchers.

**Expected behavior**
Title screen should appear after loading

**Screenshots**
![image](https://user-images.githubusercontent.com/10671494/179336179-6287de97-b576-4d6a-92ee-3cb445fc07b3.png)
![image](https://user-images.githubusercontent.com/10671494/179336226-94c12f57-dbef-4a77-9fe6-52c252563db4.png)

**Crash log or latest.log.log**
[Link](https://mclo.gs/7wdWQyF)

**Additional context**
Unmodified instance of modpack in both attempts.
Further investigation notes that AQM2 v1.3.3 also has the exact same crash, only tested on GDLauncher.

**Comment by FederAndInk** [comment]
first you need to use java 17, then there is an issue with glfw on Linux, you need to install glfw>=3.3.7 (it should be available on the official repos of Endeavouros), then you need to specify "use system glfw" in PolyMC

**Comment by votex09** [comment]
Using glfw 3.3.7 solved this.

![image](https://user-images.githubusercontent.com/10671494/179358946-ee4f61d8-f98b-4435-b657-ed318453f11b.png)

For GDLauncher, looks like i'll have to manually move the libraries from /usr/lib/ to the instance in natives.
On attempting this, looks like it succeeds as well:

![image](https://user-images.githubusercontent.com/10671494/179359207-757743c8-4dad-465e-9236-d9ae4e8fa46c.png)

Closing this as solved - not a bug with the pack.
