### ISSUE TITLE
[BUG] Entering Mining Dimension Portal as Werewolf Causes Game / Server Crash 

### ISSUE THREAD

**Issue by vaurealis** [itsdinkd/AQM2#73]
Version 1.4.1
Minecraft 1.18.2

Steps to reproduce:
- Build 3 x 2 standard size mining dimension portal
- As Activated Werewolf origin, crouch and walk into portal
- Upon dimension transfer, game / server crash occurs

[able to append crash logs later once im back at my pc]

Only was able to test on that dimension / portal configuration, possible that nether portal is similarly broken, and / or that using a taller portal (4+) would temporarily solve issue

**Comment by itsdinkd** [comment]
3x2 is not the standard size for a portal, the solution as you mentioned is to use the correct amount of blocks for a portal
