### ISSUE TITLE
[BUG] Eldritch Mobs effect(probably) causes crash when mob with it is hit or killed by melee turtle(not sure which).

### ISSUE THREAD

**Issue by Laff70** [itsdinkd/AQM2#75]
**Modpack Version**
AQM2 1.4.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
See below, sorry it's a mess. Couldn't figure out a good way to separate the crash and reproducing data.

**Steps to reproduce the behavior:**
Not entirely sure, but I was doing testing in my creative test world. I made a spawn chamber and cheated in 2 vanilla spawners and right clicked them with blaze and wither skeleton spawn eggs. I funneled them to a kill chamber with a CC: Tweaked melee turtle set to constantly swing and kill. The game has crashed twice since I've set this up. I've used melee turtles before to kill nether mobs spawned by cursed earth with no problems, but I'm not sure if that was in this version. I've noticed when the turtle damages mobs, the mobs interpret it as me damaging them to some extent(I.E. Zombie Piglins aggro on me and the turtle if my turtle attacks one which spawned on cursed earth). Also, I think whenever the turtle attacks a mob, "[Render thread/WARN]: Received unknown attacker" shows up in the log. Since the crash doesn't always happen, I'd say most blazes and wither skeletons won't cause the crash. As such, this crash is either due to a rare mob(like a mob which is buffed by a _certain_ eldritch mobs effect) or a rare event when a mob dies(potentially the turtle trying to level up due to the RPG leveling system mod). I must say though, after placing Soothing Lamps down to prevent eldritch mobs from spawning, it doesn't seem to be crashing. I'm reasonably sure that there's a certain eldritch mob effect which conflicts with melee turtles. It might also conflict with players as well as I had an issue with a blackstone golem crashing the game in version 1.3.3.

**Expected behavior**
No crashes.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
use pastebin.com for your log
My log is too big for pastebin. Would it be ok if I just pasted the area around the crash?
Edit: https://gist.github.com/Laff70/986aa026da25291eed39c81670ed49c8

**Additional context**
I had the farm run with the soothing lanterns while I typed out this bug report and the loot chest filled up way more than it did before both crashes. It also didn't crash as I typed this. So it's probably caused by eldritch mobs.

**Comment by itsdinkd** [comment]
Need a log to help. gist.github.com upload it there

**Comment by Laff70** [comment]
> Need a log to help. gist.github.com upload it there

Done. Link added to post.

**Comment by itsdinkd** [comment]
is there a crash report? i am not seeing any fatal crashes in that log

**Comment by Laff70** [comment]
> is there a crash report? i am not seeing any fatal crashes in that log

I wasn't aware those were a thing. I have some, but they're mismatched somehow. I might need to recrash to acquire the required data.
