### ISSUE TITLE
[Bug] Surprising Gift enchantment works, but exits world 

### ISSUE THREAD

**Issue by oneWishes** [itsdinkd/AQM2#75]
Whenever I drink an Instant Health potion while equipped with my Surprising Gift helmet, it immediately disconnects me from the server I am playing on with a message stating "Internal Server Error". Upon logging back in, the Instant Health potion is not consumed and a random beneficial potion is added to my inventory instead, which means that Surprising Gift *is* working, it's just also disconnecting me. 

The level of Surprising Gift on my helmet is III.
The level of the Instant Health potion I'm drinking is 1, made from killing a mob with a sword enchanted with "Refreshment."
I'm playing on v2.0a, on the official Zion server.

**Comment by itsdinkd** [comment]
This is a known issue, for any future reports, please do not delete the template is created on each issue as its important information needed for us.
