### ISSUE TITLE
[BUG] Crash when pressing space in the anvil

### ISSUE THREAD

**Issue by Asgarus** [itsdinkd/AQM2#76]
I was pressing space in an empty anvil and it caused my whole game to crash

Crash report:
[crash-2022-07-20_14.46.38-client.txt](https://github.com/itsdinkd/AQM2/files/9149915/crash-2022-07-20_14.46.38-client.txt)
.

It happened on the bouji server. I'm trying to replicate it in SP for now.

**Comment by Asgarus** [comment]
Wasn't able to replicate it neither in SP nor on the server. 
I'm pretty sure that before it crashed, the textfield was active even though the slots were both empty.
(normally it's grayed out and you can't type at all)

**Comment by itsdinkd** [comment]
Next time you open a issue please use the provided templates.

**Comment by itsdinkd** [comment]
Your issue is due to cotton, whatever that is.
