### ISSUE TITLE
Can not spawn new world in 2.0a

### ISSUE THREAD

**Issue by grimcreapere** [itsdinkd/AQM2#76]
[crash-2022-01-20_00.05.50-client.txt](https://github.com/itsdinkd/AQM2/files/7903211/crash-2022-01-20_00.05.50-client.txt)

Downloaded newest version og AQM2 and tried making a new world. Game crashed within seconds of starting to generate new world.

Someone on discord suggested attempting to create worlds multiple times, over the course of day gave it a few attempts, even altering the Terralith seed on the off chance it was something at the initial seed. no luck.

**Comment by grimcreapere** [comment]
I tried a repair and a fresh install as well with the same results.

**Comment by GwydionJon** [comment]
I got the same problem

**Comment by IvoryOwl92** [comment]
Modpack version: 2.0.a

I have the same issue as well. I've attempted to start a new world several times now and it always crashes. Here are my logs.

Taken from Crash-Reports folder:
[crash-2022-01-20_03.16.03-client.txt](https://github.com/itsdinkd/AQM2/files/7905203/crash-2022-01-20_03.16.03-client.txt)

This one was taken from the Logs folder:
[2022-01-20-3.log](https://github.com/itsdinkd/AQM2/files/7905209/2022-01-20-3.log)

**Comment by itsdinkd** [comment]
Delete LazyDFU

**Comment by IvoryOwl92** [comment]
Removing LazyDFU doesn't seem to fix the issue like we thought.
Could this be re-opened please?

**Comment by itsdinkd** [comment]
Try deleting just enough keys. Though it will reset your keybinds, back them up before deleting the mod

**Comment by WindWa1kR** [comment]
From what I've figured out, it has to do with the BetterEnd and BetterNether mods.  If I disable them, it works fine.  I tried to update them to the newest version, including the BCLib, but that didn't fix it.

**Comment by sharvesh-intrest** [comment]
[crash-2022-01-22_12.46.48-client.txt](https://github.com/itsdinkd/AQM2/files/7917822/crash-2022-01-22_12.46.48-client.txt)
have onether report of the same bug

**Comment by itsdinkd** [comment]
The issue is with better mods and terrablender. Update terrablender as they fixed it in their latest version, or delete the mod and magic Fungi entirely.
