### ISSUE TITLE
PC Crashes when creating new World  [BUG]

### ISSUE THREAD

**Issue by ArkUwU** [itsdinkd/AQM2#77]
**Modpack Version**
v2.0a
**Minecraft Version**
1.18.1 | Fabric - 0.12.12

**Describe the crash or bug**
I was just creating a new World when it's done loading the World it crashes my PC

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
I don't know how.
**Expected behavior**
What is the expected outcome?
The whole PC Crashes and restarts
**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
I don't have one

**Additional context**
Any additional context?

**Comment by IvoryOwl92** [comment]
Hey, you're having the same issue as us at: https://github.com/itsdinkd/AQM2/issues/76

Also, you can find your logs where you installed the game. Instance > Crash-Reports > Copy paste your latest log and drag it here. Crash reports are sort of needed when reporting these issues, without them, the developer can't do much.

**Comment by itsdinkd** [comment]
Duplicate
