### ISSUE TITLE
[Feature Request] Add Umbrellas for Enderians and Phantoms

### ISSUE THREAD

**Issue by ThanosDeGraf** [itsdinkd/AQM2#78]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Adding a Mod.

**Why do we need this feature?**
Playing an Enderian or Phantom for new players can be difficult, since the rain/sun can put on hold any business they had on the surface. This is a simple solution for a player in the early stages of the game before they get access to Water Protection for Enderian/Nothing for the Phantom.

**Link to the modpage if mod?**
(https://www.curseforge.com/minecraft/mc-mods/origins-umbrellas)

**Comment by itsdinkd** [comment]
Thanks for the suggestion
