### ISSUE TITLE
[BUG] Game crash when creating new world

### ISSUE THREAD

**Issue by MACM4C** [itsdinkd/AQM2#79]
Hello !

**Modpack Version**
V2.0a

**Minecraft Version**
1.18.1 Fabric - 012.12

**Describe the crash or bug**
my game crashes when creating a new world.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?

None
**Expected behavior**
What is the expected outcome?
close the game and return to windows 

**Screenshots**
Post screenshots if available
none

**Crash log or latest.log.log**
https://pastebin.com/e2WgdAdz

**Additional context**
Before posting I looked at solution #76 brought to grimcreapere. I removed LazyDFU, but it didn't work.

**Comment by itsdinkd** [comment]
we don't need multiple issues opened for this.. follow the other one.
