### ISSUE TITLE
BetterEnd end citites not spawning

### ISSUE THREAD

**Issue by kazoth** [itsdinkd/AQM2#79]
End cities should look like the picture but they spawn in as the vanilla version. Is there any way to fix this? I've tried uninstalling some mods that could be the issue but nothing works. I have also tried using the data pack that changes the way they spawn while using vanilla blocks but it is a bit buggy and I would prefer the modded version.

![dad92-16347922118704-1920](https://user-images.githubusercontent.com/104038552/180100957-1c5f14eb-5289-440a-9240-a4a77f5349ae.png)

**Comment by itsdinkd** [comment]
Please create a new issue and use the template provided for bug reports. It exists to retrieve the information needed to fix things.
