### ISSUE TITLE
[BUG] Gobber Questline and AE2

### ISSUE THREAD

**Issue by Nightscore** [itsdinkd/AQM2#8]
**Modpack Version**
2.1.3
**Minecraft Version**
1.18.1

**Describe the crash or bug**
You can't finish the Gobber Quest if you're crafting at a AE2 Crafting Terminal. It doesn't trigger the Quest as Finished. 
I can just say its a Problem for Nether- and Endgobber because i finished the Overworld Gobber quests before i had the ME-System.
But with Tom's Storage mod it worked fine.

**Steps to reproduce the behavior:**
Craft a Gobber Glob at a AE2 Crafting terminal and check if the quest is finished and after try it with a Vanila Crafting Table

**Expected behavior**
The Quest should be finished in all Crafting terminals/Tables

**Comment by itsdinkd** [comment]
This is nothing I can control. Its what ftb quests recognizes as crafting. I can write use a vanilla crafting table in the 1.18.2 pack, thanks for reporting.
