### ISSUE TITLE
Nether gobber rods quest requires nether gobber pickaxe as dependancy[BUG]

### ISSUE THREAD

**Issue by ZacPJ** [itsdinkd/AQM2#80]
**Modpack Version**
What modpack version
1.4.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
The quest for nether gobber rods is dependant on the quest for nether gobber pickaxe, also the nether gobber pickaxe is dependant on end gobber ore.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Its an error in the quest book itself.
**Expected behavior**
What is the expected outcome?
The nether gobber rods quest should not depend on the pickaxe, it seems to be backwards.
**Screenshots**
Post screenshots if available
https://cdn.discordapp.com/attachments/1000405985384476753/1000410750596161536/unknown.png
https://cdn.discordapp.com/attachments/1000405985384476753/1000410807261216829/unknown.png

**Crash log or latest.log.log**
use pastebin.com for your log
n/a
**Additional context**
Any additional context?
I am unsure if there are any other quests with errors like this.

**Comment by itsdinkd** [comment]
Please name issues 
![image](https://user-images.githubusercontent.com/35115304/180614450-de303275-774b-4032-94f6-10c45214b1ff.png)

**Comment by itsdinkd** [comment]
fixed
