### ISSUE TITLE
[BUG] Enderman xp farm despawning minecart

### ISSUE THREAD

**Issue by Antoninecek** [itsdinkd/AQM2#81]
**Modpack Version**
1.5.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Minecart with Nametagged Endermite was between carpets. Enderman can't reach him. After mobs spawning the minecart with Endermite disappears.
![image](https://user-images.githubusercontent.com/15322661/150601714-4654449a-a29c-44f9-93a7-86e237921ef2.png)

**Expected behavior**
Minecart should be there.

**Comment by itsdinkd** [comment]
Update your modpack.
