### ISSUE TITLE
[BUG] Red Bits Guide book recipe missing

### ISSUE THREAD

**Issue by Deathcounter** [itsdinkd/AQM2#82]
**Modpack Version**
1.3.3

**Minecraft Version**
1.18.2 

**Describe the crash or bug**
There is no recipe for that book

**Steps to reproduce the behavior:**
Press the Recipe button for REI on the book -> wrong recipes for other guide books show up

**Expected behavior**
A recipe for Red Bits Guide book

**Additional context**
Could I propose a Crafting recipe? I would like it to be a Book + Redstone torch. Thanks in advance

**Comment by itsdinkd** [comment]
yes this is known. its because they haven't released a update to fix their bug with new patchouli
