### ISSUE TITLE
[BUG] Enderman doesn't drop xp

### ISSUE THREAD

**Issue by Antoninecek** [itsdinkd/AQM2#82]
**Modpack Version**
1.5.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Minecraft Endermen don't drop experience points, only MobZ Endermen do.

**Expected behavior**
Minecraft Enderman should drop 5 xp points.

**Comment by itsdinkd** [comment]
Update modpack to latest, 2.0a and let us know if this bug still exists, if it does I will re-open ticket. cannot offer back support on older versions when there's over 30-60 mod updates on most modpack updates.
