### ISSUE TITLE
[BUG] Tech Reborn Grinder Coal Dust recipe problem

### ISSUE THREAD

**Issue by MarVIN-UwU** [itsdinkd/AQM2#83]
Modpack Version
2.0a

Minecraft Version
1.18.1

TechReborn Grinder makes 2xCoal from grinding 1 coal. It shoud give you 1 coal dust.

To Reproduce
Put one coal into Tech Reborn Grinder

Expected behavior
1 Coal Dust as output of grinding Coal

Screenshots
![image](https://user-images.githubusercontent.com/98196327/150618885-4c417ad7-178d-42cd-8610-d5d5c2f50c4d.png)
![image](https://user-images.githubusercontent.com/98196327/150619778-4431db78-9853-44e1-b406-e692ebcdd446.png)

**Comment by itsdinkd** [comment]
Fixed in 2.0.1
