### ISSUE TITLE
[BUG] Can't log into server after updating to 1.5

### ISSUE THREAD

**Issue by madbrad21** [itsdinkd/AQM2#83]
**Modpack Version**
AQM2 1.5
**Minecraft Version**
1.18.2

**Describe the crash or bug**
After updating to 1.5 I can no longer log in
Had assistance from host provider and they believe it has to do with the origins mod but was unsure what specifically was causing the issue.
Deleting my player data allowed connection
I was playing as an arcanite with blacksmithing (level 74)

**Steps to reproduce the behavior:**
Maybe create an arcanite blacksmith with no curse on 1.4 then update to 1.5
Unsure how to recreate this but I can also provide the player.dat file if needed

**Expected behavior**
Allow the account to log in

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
Client latest: https://pastebin.com/sgjX9n0i
Server Latest: https://pastebin.com/cp8p25Qk

**Additional context**
I was wearing doom armor but I have removed it with an nbt editor
Link to player.dat
https://drive.google.com/file/d/1Ukqc4TzBbuhjdoLXTj3C0HNA6C0OpBRF/view?usp=sharing

**Comment by itsdinkd** [comment]
Doom armor was removed
Did you modify anything in the modpack or add anything? 

Also you'll have to report this to Origins github

**Comment by madbrad21** [comment]
I did not add anything or modify anything however I believe the host provider uses the client files to make the server. Everyone else on the server are able to join so far without issue

As for reporting it to the origins github was there a version change at all that I should make note of for them?

**Comment by madbrad21** [comment]
So looking at the Origin for Arcanite it looks like the immunity to fire and lightning was removed, I'm thinking that may be what was causing the issue as the older version I had immunity and in the new one that is not part of the origin
