### ISSUE TITLE
[BUG] AE2 cable anchor craft modified by the kubejs unification script

### ISSUE THREAD

**Issue by Kuchiha** [itsdinkd/AQM2#84]
Hello,

I don't know if it's intended, but the craft for the anchor cable from AE2 is modified by the unification script inside kubejs.

`server_scripts:unification.js:183: ~ ae2:network/parts/cable_anchor[minecraft:crafting_shapeless]: IN 'create:brass_ingot' -> 'techreborn:brass_ingot'`

The initial recipe accepts ingots inside the tag 'ae2:metal_ingots', but the tag is replace by the brass ingot.

After asking on the discord, I've been asked to open a bug report here.

**Modpack Version**
AQM 2 v1.5

**Minecraft Version**
1.18.2

**Comment by itsdinkd** [comment]
Not a bug, unless you cannot craft it with the brass ingot?

**Comment by Kuchiha** [comment]
Then there is still a bug, the craft with the deployer from create accept all ingots ...

![image](https://user-images.githubusercontent.com/13506611/181846134-18e7b338-52d9-4669-b13d-9d98c413aeac.png)
