### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NOOVAK05** [itsdinkd/AQM2#85]
**Modpack Version**
AQM2-1.4.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Whenever the screen block from the mod lift was placed down, the game will become very blurry. Tried to remove some of those performance mods such as sodium, indium, and iris to see if it is the cause but still no luck. Mod that i removed are Sodium, Sodium-Extra, Entityculling, Krypton, Indium, bsvb, Reeses_Sodium_Options. 

**Steps to reproduce the behavior:**
Place down a screen block from the mod lift 

**Expected behavior**
the screen turns blurry

**Screenshots**
![2022-07-30_16 32 28](https://user-images.githubusercontent.com/73258046/181900937-b3062ec8-f6fb-443c-a2cb-43259410112a.png)

![2022-07-30_16 32 38](https://user-images.githubusercontent.com/73258046/181900848-67868bbf-82c0-48ca-9b39-64923409c173.png)

![2022-07-30_16 32 47](https://user-images.githubusercontent.com/73258046/181901098-ecc31095-11e0-4280-9a46-d01390c975ad.png)

**Crash log or latest.log.log**
use pastebin.com for your log

**Additional context**
Any additional context?

**Comment by FederAndInk** [comment]
was this map created on 1.4.1?
You could try

1. updating to the latest version of the modpack
2. posting this issue on the mod issue page

**Comment by NOOVAK05** [comment]
Updated the modpack and created a new world in the new version and the issue still exists. Did a little testing and try removing some mods to see what caused the bug. It ended up being the tempad mod that caused the bug. Not sure if there is any config that could be changed to fix this bug, but removing the mod fixed it.

**Comment by itsdinkd** [comment]
You added a mod? 

![image](https://user-images.githubusercontent.com/35115304/181994474-bc4f94dd-a0b7-414f-b140-e92d0a8b8eeb.png)

**Comment by itsdinkd** [comment]
Nope you didnt add it nevermind. However, you are using the screen wrong. take that off, that is made for the actual Lifts.
