### ISSUE TITLE
[BUG] Mining Dimensions completely broken

### ISSUE THREAD

**Issue by Archiplex** [itsdinkd/AQM2#85]
**Modpack Version**
AQM2, Fabric, 2.0a

**Minecraft Version**
1.18

**Describe the crash or bug**
Attempting to enter a mining dimension (any of them) causes an eternal loading screen.
Attempting to use /execute in (dimension) does not actually show the dimension. The dimension might just not be loading entirely.

**Steps to reproduce the behavior:**
Literally just use a portal, or try to use /execute in (dimension) run tp (name) (coords)

Deleted the other bug report stuff as not very needed.

**Comment by itsdinkd** [comment]
Issue with terrablender (another one yay) will be fixed on 2.1
