### ISSUE TITLE
[BUG] Croptopia butter recipe using up cooking pot and food press

### ISSUE THREAD

**Issue by Asgarus** [itsdinkd/AQM2#86]
**Modpack Version**
1.5

**Minecraft Version**
1.18.2

**Describe the crash or bug**
When crafting butter from the Croptopia mod, the cooking pot and all purpose food press are being used up. 
Definitely doesn't make sense.
It happens in the crafting terminal of Tom's Simple Storage Mod as well as the regular 2x2 in the player's inventory.
It's also not mentioned in any change log, so I'm assuming it's unintended behavior.

**Steps to reproduce the behavior:**
Craft butter (I'm using cooked soy milk buckets)

**Expected behavior**
The cooking pot and the food press not being used up.

**Screenshots**
Before crafting 
![grafik](https://user-images.githubusercontent.com/46724269/181906252-d66070d6-9b03-4e05-8787-c804fb3bfc21.png)
After crafting 
![grafik](https://user-images.githubusercontent.com/46724269/181906267-0d7bc0f1-cafe-438f-b952-b76d2d194d3c.png)

**Crash log or latest.log.log**
no crash

**Additional context**
It didn't happen before, but I'm not sure which update caused it. Must be either 1.5 or 1.4, because I crafted butter before in larger quantities.

**Comment by Asgarus** [comment]
Same thing in the crafting station, so I guess it doesn't have to do with where you craft it.

**Comment by itsdinkd** [comment]
Please report to croptopia if this problem still exists in AQM2 v1.6
