### ISSUE TITLE
[BUG] Instant Health Potion causes disconnect

### ISSUE THREAD

**Issue by Archiplex** [itsdinkd/AQM2#86]
Modpack Version
AQM2, Fabric, 2.0a

Minecraft Version
1.18

**Describe the crash or bug**
Drinking *some* instant health potions in a multiplayer servers disconnects the drinker immediately with a "Internal Server Error". The potion remains in inventory and does not disappear. Doesn't create weird logs on the server nor client.

**Steps to reproduce the behavior:**
Drink an instant health potion from a loot chest.

**Expected behavior**
To be healed!

**Additional context**
SOME instant health potions worked; from my experience it seems it's mainly "Instant Health" but not "Instant Health II", and all the potions used were obtained from loot chests (easily found in the blimps/flying dungeons)

**Comment by itsdinkd** [comment]
https://github.com/P03W/RPGStats/issues/94#issuecomment-1020572144

**Comment by itsdinkd** [comment]
Fixed in 2.0.2
