### ISSUE TITLE
[BUG] BE Anvil Crafting not functioning at all

### ISSUE THREAD

**Issue by Archiplex** [itsdinkd/AQM2#87]
Modpack Version
AQM2, Fabric, 2.0a

Minecraft Version
1.18

**Describe the crash or bug**
Anvil crafting is required by Better End for a good portion of its recipes; i.e crafting Ender Dust requires anvil crafting with no other method of creating it (could be neat for a grinder/macerator recipe, but i digress).

**Steps to reproduce the behavior:**
It normally works by placing an object to be crushed on the left slot on an anvil, hammer in the middle, and it creates on the right.

**Expected behavior**
Being able to craft BE items i.e ender dust.

**Screenshots**
https://i.imgur.com/Xg996TW.png
https://i.imgur.com/B9IYYXo.png

**Additional context**
Pretty big, considering how much stuff is locked behind anvil crafting.

**Comment by itsdinkd** [comment]
I recommend reporting this to BE.
