### ISSUE TITLE
[BUG] Crafting recipe for Star Platinum Scythe / Machete only needs sticks

### ISSUE THREAD

**Issue by Asgarus** [itsdinkd/AQM2#88]
**Modpack Version**
1.5.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
The star platinum scythe and machete from the mod Harvest Scythes only needs sticks to craft. (2 for the scythe, 1 for the machete)

**Steps to reproduce the behavior:**
Use any 3x3 crafting grid.
![grafik](https://user-images.githubusercontent.com/46724269/184443000-ce927791-eb83-4706-8fc4-4efc6b97e813.png)
![grafik](https://user-images.githubusercontent.com/46724269/184443012-3827f7e9-3985-42bc-9fbb-c491d698fa93.png)

**Expected behavior**
Zero scythes or machetes.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/46724269/184443224-7ae58fe9-e654-4a7b-8a9d-d79540667e5a.png)

**Crash log or latest.log.log**
No crash. Just a faulty recipe.

**Additional context**
I assume the mod used to have its own star platinum ingots and when they got removed, the recipes weren't adjusted to the Mythic Metals star platinum ingots.

**Comment by Bombard7** [comment]
actually, when you try to look at recipe and move your cursor at place, where star platinum should be, your game crash

**Comment by itsdinkd** [comment]
Can you provide that crash log please?

**Comment by Asgarus** [comment]
I checked and don't get a crash. Nothing happens.

**Comment by itsdinkd** [comment]
Should be fixed in 1.6
