### ISSUE TITLE
[Feature/Suggestion] Improved endgame damage dealing

### ISSUE THREAD

**Issue by klassekatze** [itsdinkd/AQM2#89]
**Is your feature request/suggestion related to a problem? Please describe.**
There are numerous ways to become all but unkillable by the endgame. Death Barter, totems, poppets, status effects, potions and amulets, trinkets, and numerous strong armors that-- enchanted to the nines-- can render you so strong that even without quantum armor, it requires active negligence for a boss to kill you, and it can be _literally impossible_ for another player to do so.

This is not a problem in itself. It's a good thing, even -- it means you can 'beat' that element of the game, the initial lethality, and focus on other challenges.

The problem is that the ability to deal damage cannot be similarly scaled. This means that PVP is nearly if not impossible for players at this level.

And more egregiously, it means that bosses become tedious.

The various modded bosses have numerous characteristics designed to make them difficult to kill even before the multiplicative effects of Eldritch Mobs. Dodging, teleportation, projectile immunity, massive knockback attacks, multi-stage with mob adds and summons, timers, re-ups to full health, etc. EM can add even more re-ups, yeeting... but none of these things will kill someone with endgame defensive gear. All they do is make it harder to actually hit the enemy.

The drops from these bosses are required to complete the pack progression, and in sometimes significant quantities. With the current damage dealing capabilities, a person near the end game will have no recourse from spending literal hours bonking bosses-- often the same bosses over and over-- with the current best weapons, chipping away at in many cases thousands of HP behind tons of armor rating. It's not a challenge, it's not fun, it's just a chore.

**Describe the suggestion you'd like**
I'd like for various damage-amplifying enchantments or weapons to be re-enabled, and possibly for other weapon mods to be considered.

The low-hanging fruit here is Enigma Resonator, Void Shot, Void Strike, from MC Dungeon Weapons, already in the pack.

To my understanding, Enigma Resonator in particular was disabled for being "too powerful" -- but I feel that that was a knee-jerk reaction. Its ability to amplify damage directly correlates to your XP level, and it is inherently costly for someone to maintain a high XP level in combat unless they are already either so skilled or so well armored that they can't be killed. And if they cannot be killed, I do not feel that it is beneficial to the player experience for them to struggle to deal damage to the things that can't kill them.

The damage amplification for ER is also logarithmic, not linear-- more levels become less and less effective with it. When playing with ER on earlier versions of the pack, it still took time and effort to kill most bosses regardless of the number of XP levels accrued, with the only exception being the Obsidilith. This is because, as mentioned earlier, most bosses dodge, teleport, and/or have invulnerable stages and damage caps-- the Obsidilith is just unique in that it is predictable and vulnerable in its general stage. Even then, the slightest delay or mistake would see you needing to run around breaking the invincibility-granting obsidian runes all the same.

Void Strike/Shot are just some relatively fixed damage multipliers. Not much to say about that.

Worth noting is that in the current version of AQM2, these three enchants are disabled for the Dark Enchanter, even if enabled in MCDA. They must be initially acquired either through a lucky mob drop, a lucky villager trade, or a similarly lucky (_very_ lucky, like a hundred tries) roll on the vanilla enchanting table. This means you have to either be lucky or rich to even get them-- meaning they are unlikely to affect early gameplay.

Possibly re-enable Rod of the Unstable Reservoir.

Re-enable QuickUse on gobber sniper-sword, while possibly making the recipe more expensive. This allows players to have access to the weaker variant as a separate item, but at greater cost be able to use the high-speed arrows as well.

It's worth noting here that the gobber sniper staff and sniper sword _cannot accept bow enchantments_, and as such will never be able to be as strong arrow-to-arrow. Without QuickUse, they lose out to bows in nearly every use case.

The base damage value of the most expensive weapons in the pack could also be directly increased with kubejs, or greater damage assigned to otherwise completely redundant weapons which could then be given new, more expensive recipes. For example, the currently anemic 9-damage "Soul Alloy Sword" from Conjuring, or the 10-12 damage blades of "Aegis" from Mythic Metals, both currently crushed by gobber swords.

**If this is a request to add a mod, what is the curseforge link?**
https://www.curseforge.com/minecraft/mc-mods/attribute-plus-fix
This appears to facilitate cleanly modifying weapon damage in kubejs, and also has a code snippet for how it would be done.

**Comment by itsdinkd** [comment]
i have enabled quantum sword for the time being
