### ISSUE TITLE
[BUG] Croparia Greenhouse Crashes server

### ISSUE THREAD

**Issue by Nightscore** [itsdinkd/AQM2#9]
**Modpack Version**
2.1.3

**Minecraft Version**
1.18.1

**Describe the crash or bug**
If you place a Croparia Greenhouse on another mod Crop than Croparia the server shuts down caused by the Max tick time. 
Even if you set the max tick time to unlimited the server doesn't boot after 30mins. In my case I accidentally placed the Greenhouse on a Bewichment crop, some seconds after this i got disconnected.

**Steps to reproduce the behavior:**
Place a Croparia Greenhouse on a Bewichment crop

**Expected behavior**
The server shuts down and you cannot bring it back to life without a Worldedit tool.

**Crash log or latest.log.log**
[Client Log](https://pastebin.com/kY7yLqE4)
[Log](https://pastebin.com/d8U3921d)

**Comment by itsdinkd** [comment]
Unfortunately 1.18.1 is no longer supported. I recommend bringing this up to the developer to see if they will fix for their 1.18.1 version.
