### ISSUE TITLE
[BUG] Partialy rendered Spectrum colored trees

### ISSUE THREAD

**Issue by Antoninecek** [itsdinkd/AQM2#91]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Spectrum color trees are not rendering properly after bonemealed. First render is just few logs (but leaves are there, I cant jump under the tree). While rightclicking on them the tree is partialy rendering with every rightclick. Relog will render the tree correctly.

Mod dev:
![image](https://user-images.githubusercontent.com/15322661/150937291-885a1e25-34bc-4d80-874a-af19fe935ce0.png)

I tried Spectrum solo with Dynamic FPS, Sodium, Sodium Extra, Reese's Sodium Options, but couldn't find the issue.

**Screenshots**
Partialy rendered.
![image](https://user-images.githubusercontent.com/15322661/150937021-cdc0e141-3e32-4fb6-bb7c-27fa3b9a2083.png)

**Comment by itsdinkd** [comment]
this is not a bug. this is fast leaves.

**Comment by Antoninecek** [comment]
I don't think you understand me. I have to rightclick to rendered blocks to render adjacent blocks. There you have screenshots. Also I couldn't find any leaves mod.

![2022-01-27_09 43 47](https://user-images.githubusercontent.com/15322661/151323436-190f7e97-20be-4815-97dd-219906c1bfb6.png)
![2022-01-27_09 43 56](https://user-images.githubusercontent.com/15322661/151323448-ae5dae44-7a99-456c-a596-b3f661a1a9a1.png)
![2022-01-27_09 44 15](https://user-images.githubusercontent.com/15322661/151323459-cd4e20a4-518e-4372-9120-f28060dad1ee.png)
![2022-01-27_09 44 18](https://user-images.githubusercontent.com/15322661/151323468-8f9e0700-15c1-4731-b6f8-28d5ea2baf29.png)
![2022-01-27_09 44 29](https://user-images.githubusercontent.com/15322661/151323476-dce08a24-7814-4c68-975d-03f7dc4cdfa4.png)
![2022-01-27_09 44 32](https://user-images.githubusercontent.com/15322661/151323483-efce7bfc-ca78-44a4-9dce-16236b8b841f.png)
![2022-01-27_09 44 40](https://user-images.githubusercontent.com/15322661/151323486-078be8e0-eba1-4699-9c14-47b06a9988d8.png)
![2022-01-27_09 44 41](https://user-images.githubusercontent.com/15322661/151323495-ec7ea293-2666-4911-89d0-548ec359221d.png)
![2022-01-27_09 44 53](https://user-images.githubusercontent.com/15322661/151323504-42e9f434-8e77-478a-a763-44b0f764a543.png)
![2022-01-27_09 44 56](https://user-images.githubusercontent.com/15322661/151323509-33c57d4b-32af-4440-a34d-06922e4478ee.png)
![2022-01-27_09 44 59](https://user-images.githubusercontent.com/15322661/151323513-6b8fd387-ad2f-4498-8489-0ffe3f05b526.png)

**Comment by itsdinkd** [comment]
You can try removing indium to see if it fixes it, though this might break dependencies / items that need indium to render.
