### ISSUE TITLE
[BUG] Items in AE2 Inscriber Autocrafter Setup are converted into Botania Mana

### ISSUE THREAD

**Issue by FishyDreamer** [itsdinkd/AQM2#92]
**Modpack Version**
v1.5.1

**Minecraft Version**
v1.18.1

**Describe the crash or bug**
I'm not sure what is causing this issue. I'm on the bouji server and currently when I ask my ME system to craft processors regardless of what processor I request they are all turned into an item called Mana that says it's from Minecraft (I assume this is botania mana just mislabeled). They only turn into mana after the complete product is made and then transferred over to the pattern provider.

This was working fine beforehand but suddenly this behavior keeps occuring. The system is not in anyway connected to botania.

**Steps to reproduce the behavior:**
Ask the system to autocraft the items.

**Expected behavior**
The requested processor is produced and not turned into mana.

**Screenshots**
![image](https://user-images.githubusercontent.com/29006642/185726354-49696a8b-c244-4e14-ad80-98771a9b3de0.png)
![image](https://user-images.githubusercontent.com/29006642/185726375-f835e46e-2455-42f5-bbb2-a00fbfb6a8c0.png)
![image](https://user-images.githubusercontent.com/29006642/185726382-69d02ab5-1ddf-481d-afed-c3bede1ace6d.png)

**Crash log or latest.log.log**
Log to large to upload and is not called latest.log. Will attempt to produce a log if need be.

**Additional context**
N/A

**Comment by itsdinkd** [comment]
I would recommend reporting this to AE2 and the developer who made the Applied Botanics mod

**Comment by FederAndInk** [comment]
> are all turned into an item called Mana that says it's from Minecraft

can you provide a screenshot of this?

it could also be applied botania

**Comment by itsdinkd** [comment]
should be fixed on upcoming update
