### ISSUE TITLE
[BUG] Spectrum moving items from REI to pedestal causes disconnect.

### ISSUE THREAD

**Issue by Antoninecek** [itsdinkd/AQM2#92]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
When I try to craft Bottle of Fading, mc client will disconnect from server. It's the moment when I add items to Pigment Pedestal and pull the lever. Client disconnect (timeout). No error in logs (server and client).

With client mods Spectrum, Sodium (extra, reese's), Dynamic FPS it works well.

**Comment by Antoninecek** [comment]
It seems it's not about that bottle. Just try to add items from Rei to Spectrum Pedestal.

**Comment by itsdinkd** [comment]
From your log it looks like this issue is due to **polymer**

**Comment by itsdinkd** [comment]
I recommend posting this on the Spectrum github / Polymer github as there isn't much I can do here
