### ISSUE TITLE
[BUG] main recipe for bronce dust is missing

### ISSUE THREAD

**Issue by passivagressiv** [itsdinkd/AQM2#93]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
the main recipe for bronze dust is missing (tech reborn/modern industrialization)

**Steps to reproduce the behavior:**
1. search for recipes for bronze dust
2. it is only possible to craft bronze dust from tiny bronze dust
3. tiny bronze dust is made of tiny tin dust and tiny copper dust

**Expected behavior**
there should be the possibilty to craft bronze dust out of tin dust and copper dust,
i think the recipe is missing from the the mixer (modern industrialization)

there are still both recipes for other metals (see last screenshot)

**Screenshots**
Post screenshots if available
![bronze](https://user-images.githubusercontent.com/97842896/151238091-f5b98c96-0945-475d-a84f-fc9241573a2a.PNG)
![bronze_tiny1](https://user-images.githubusercontent.com/97842896/151238111-babe74b8-7103-4dc2-a41b-2ffb22021e9a.PNG)
![bronze_tiny2](https://user-images.githubusercontent.com/97842896/151238121-12012b26-d842-4ee5-befa-9ac922883d86.PNG)
![cupronickel](https://user-images.githubusercontent.com/97842896/151238127-e3a2ea9e-2fcf-4ffc-8226-26f695fbea65.PNG)

**Comment by itsdinkd** [comment]
To get bronze dust you need to put a bronze ingot in a furnace...  as far as recipes go, nothing has changed other than tech reborn version being prioritized. MI version of items still work, they just won't show on normal recipe viewing.

**Comment by passivagressiv** [comment]
but in the current state it is not possible to obtain bronze without an alloy smelter from tech reborn, 
before the change we could automate bronze with MI blocks only but now the recipe 1 tin dust + 3 copper dust = 4 bronze dust in the mixer is missing and you need to use tech reborn machines which have differnet speeds and energy tick rates.

i understand the fusion of the two mods but this single recipe helps to avoid a complicated workarround
