### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BeanAlrighty** [itsdinkd/AQM2#94]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
Shears don't work.
When trying to shear grass, seagrass, vines or glow lichen. It gets destroyed as if I wasn't using shears. However, leaves for some reason work fine.

**Steps to reproduce the behavior:**
Use some shears on grass, seagrass, glow lichen or vines.

**Expected behavior**
You shouldn't get the block after breaking it.

**Screenshots**
Post screenshots if available

**Crash log or latest.log.log**
This was on the server, so I don't have access to the logs.

**Additional context**
 This possibly could have been in older versions? I can't really confirm that, but I remember trying to get some glow lichen in the modpack's version 1.7 and it getting destroyed too.

**Comment by itsdinkd** [comment]
Try on latest version and report back if it still doesn't work. I'll reopen if it does not. 

Also, please add a title.
