### ISSUE TITLE
[BUG] Iron golem origin taking very long to eat / heal

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#95]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
idk if it's intended, but Iron golem origin's eat/repair cooldown bar takes a whole 1m20s to fill up, which I think it's a lot considering it's the only way this origin can regen health appart from potions.

**Expected behavior**
I think it should take less time to be able to regenerate, around 45s might be ok

**Comment by Nyomsuwu** [comment]
As far as I know this was default at 30 seconds, at least around version 1.6-hotfix.

**Comment by Sebas-Re** [comment]
AE2 invisible blocks bug was also fixed in one of those versions, and even so it has reappeared in latest ver, so maybe that's related? Idk
