### ISSUE TITLE
[Suggestion] Mod Suggestion - Toast Manager

### ISSUE THREAD

**Issue by Banzetta** [itsdinkd/AQM2#96]
**Is your feature request/suggestion related to a problem? Please describe.**
More of an annoyance than a problem, the toast popups in the corner of the screen are distracting and somewhat intrusive.

**Describe the suggestion you'd like**
A way to block toasts or make them less intrusive.

**If this is a request to add a mod, what is the curseforge link?**
https://www.curseforge.com/minecraft/mc-mods/toast-manager

**Why do you think this would benefit the modpack?**
I think the pack could benefit from my new mod, Toast Manager, which allows you to selectively block toasts so you don't have to see recipe/tutorial/system popups in the corner.  For the toasts that you do still want to see, by default the mod also makes them partially translucent so they aren't as intrusive.  It's just a nice QoL update.

**Additional context**
Not much additional context, other than Toast Manager includes all the features from the Forge mod Toast Control and then some.  Thank you for your consideration.

**Comment by itsdinkd** [comment]
This is a client side mod, youre more than welcome to add it to the modpack without it conflicting with anything else
