### ISSUE TITLE
Manual bronze ingot ratio inverted

### ISSUE THREAD

**Issue by Kevlartx** [itsdinkd/AQM2#96]
In 2.0.1, 3 tin ingots and one copper can be crafted to make bronze ingots.  It’s the right ratio, but flipped vs. usual ratio, like in the alloy smelter, where it is 3 copper per 1 tin.

**Comment by Kevlartx** [comment]
This is my first ever GitHub report, apologies if I did something wrong!  Hirobrainz

**Comment by itsdinkd** [comment]
Fixed in 2.0.2

Please use the template attached to the bug report issues. When you click issues and create new issue, there should be a item called Bug Reports. Click the button next to this and it will create that template.
