### ISSUE TITLE
[BUG]  Shearable blocks can't be obtained with shears

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#97]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**
any type of grass (grass,fern,etc), seagrass and glow lichen can't be obtained using shears, as it's supposed to.

**Steps to reproduce the behavior:**
1. Find some glow lichen / seagrass.
2. Break it using shears
3. Nothing will drop

**Expected behavior**
You should be able to obtain said blocks by using shears.

**Additional context**
Someone brought this to me as they couldn't get the necessary resources to get magic a certain base fungi item (I think it was vivifica essence).

**Comment by vydax** [comment]
+1 on this one cant do it either.,,

**Comment by itsdinkd** [comment]
fixed with latest update
