### ISSUE TITLE
[BUG] ore gen tab disabled/not working

### ISSUE THREAD

**Issue by Kevlartx** [itsdinkd/AQM2#98]
**Modpack Version**
AQM2 2.0.1 on Zion server
**Minecraft Version**
1.1.18

**Describe the crash or bug**
On Zion today, I could not see the ore gen tab that shows where to find an ore.  I was looking at vanilla and deepslate iron.  Another player, Asum5 or something, verified.

**Steps to reproduce the behavior:**
Load 2.0.1, get on Zion, use rei to look up iron ore, mouseover, press r, look at recipe tabs.  None of the dimension tabs are there.

**Expected behavior**
Ore gen graphs

**Screenshots**
Sorry on my iPad atm.

**Crash log or latest.log.log**
N/a

**Additional context**
Any additional context?

**Comment by Jordan231111** [comment]
Same issue the ore gen on REI does not show when joining/playing an AQM2 server

**Comment by itsdinkd** [comment]
This is because roughly enough resources has to be on the server for you to view ore location. It's optional for server owners if they want to allow players to see ore location or not. Not a bug
