### ISSUE TITLE
[BUG] Crash when shooting rubros with a nether bow

### ISSUE THREAD

**Issue by Asgarus** [itsdinkd/AQM2#98]
**Modpack Version**
1.5.1

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Every other time I shoot a rubro with my bow, my game crashes (not fully, I just get dropped from the server) with the error message in the first screenshot.
My bow and its enchantments are in the second screenshot.
A rubro is in the third.

**Steps to reproduce the behavior:**
Probably by using the same bow with the same enchantments (or the enchantment that probably causes the error)

**Expected behavior**
Me not crashing.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/46724269/187963324-f79fa620-eee9-49f9-a054-29f7bbe023b9.png)
![grafik](https://user-images.githubusercontent.com/46724269/187963382-03937081-fd74-4ae6-8178-d1dce423bdbe.png)
![grafik](https://user-images.githubusercontent.com/46724269/187963489-e9552e61-4712-4192-b9ec-c78bf785d5ab.png)

**Crash log or latest.log.log**
The error doesn't seem to show in my latest.log.

**Additional context**
Happened in the mining dimension, but I doubt it's limited to it.
It might have to do with them dropping redstones sometimes when you attack them.

**Comment by xErrorAmelie** [comment]
https://github.com/Klyser8/Earthbounds-old/issues/20#issuecomment-1207287961 Already reported to the dev, months ago. Could be a mod conflict ¯\_(ツ)_/¯

**Comment by itsdinkd** [comment]
possibly the Tempo enchantment

**Comment by Asgarus** [comment]
Just tested a bow with the same enchantments except for Tempo Theft. Same outcome.

**Comment by xErrorAmelie** [comment]
It should happen with everything you shoot at him, even wither skulls^^

>

**Comment by Asgarus** [comment]
It doesn't happen without the Venomous enchantment. Not sure how to shoot wither skulls..^^

I added the Tempo Theft and it still doesn't cause an error. Seems Venomous caused it. Maybe status effects in general are the cause (since Tempo Theft doesn't seem to give me a speed status effect, it probably doesn't give the target a slow status effect, either, that's why it doesn't cause the error I assume).

**Comment by itsdinkd** [comment]
Closing as 1.18.2 is sunset
