### ISSUE TITLE
[Feature Request] [Mod] Chirpy's Wildlife

### ISSUE THREAD

**Issue by IvoryOwl92** [itsdinkd/AQM2#99]
_**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**_
Adding a mod.

_**Why do we need this feature?**_
More than 50 high-quality, cute animals! Smaller species like insects and birds may be picked, and will ride on the player's head if placed there. Includes rare variants, like albinos. Comes with a config file to adjust spawn rates and location.

_**Link to the modpage if mod?**_
(https://www.curseforge.com/minecraft/mc-mods/chirpys-wildlife)

**Additional context**
![image](https://user-images.githubusercontent.com/11478317/151485607-f4c659f2-ca2f-4cbd-90aa-30314be2dc79.png)

![image](https://user-images.githubusercontent.com/11478317/151485889-a372b958-b6dc-466d-87ee-c88f60d65a43.png)

![image](https://user-images.githubusercontent.com/11478317/151485898-2a7d0f2a-b134-424e-9600-c581541a9652.png)

![image](https://user-images.githubusercontent.com/11478317/151485910-bb4c5746-6eb6-4975-8ac8-e77303898072.png)

![image](https://user-images.githubusercontent.com/11478317/151485919-ab81ff6f-eb44-4f3a-8796-fd8928f0375a.png)

**Comment by vydax** [comment]
thumbs up for me, lots of nice wildlife

**Comment by itsdinkd** [comment]
Great suggestion and wonderful models. Though since we're already using Better Animals Plus, this would just clog up spawn pool.
